### ISSUE TITLE
Feature Request: Make compatible with Progressive Automation

### ISSUE THREAD

**Issue by captcookie** [stal111/Forbidden-Arcanus#1]
The chopper in the progressive automation will lay the saplings but does not chop the trees. Example: Cherry Trees do not get harvested. When attempting to add the sapling to the bonsai tree dirt, it refuses to right click. So, I was wondering if you could look in this as a nice way to harvest your wood from your mod. :D Thanks!

![2019-06-03_12 29 28](https://user-images.githubusercontent.com/19790335/58821886-b3b85b80-85fb-11e9-80b6-79b1703b4bbf.png)
![2019-06-03_12 37 52](https://user-images.githubusercontent.com/19790335/58822190-87510f00-85fc-11e9-89bd-0f355ab36c01.png)

**Comment by stal111** [comment]
I will look what I can do ^^ But thanks for the report!

**Comment by stal111** [comment]
The Chopper issues should be fixed in forbidden_arcanus-1.12.2-1.1.1. However the Bonsai Tree Compability you can add yourself: https://minecraft.curseforge.com/projects/bonsai-trees?gameCategorySlug=mc-mods&projectID=278993#title-2-3
