### ISSUE TITLE
Suggestion: Blacklist and Smithing Table support for Eternal Stella tool enchanting

### ISSUE THREAD

**Issue by vectorwing** [stal111/Forbidden-Arcanus#101]
Greetings! ^^

Recently I've been testing mod interactions, particularly in the Valhelsia 3 modpack on 1.16, and I found an issue involving the Eternal Stella item.

It seems to scan for tools and certain damageable items to add an enchanting recipe for them, granting the item the _Indestructible_ enchantment. However, some modded tools might override the container method to take damage when used in crafting. Currently, the recipe is allowing **duplication** of such items. It's not too severe, since Eternal Stella seems to be rare, but still something to consider.

![image](https://user-images.githubusercontent.com/5566692/93028760-5aa3e980-f5ec-11ea-9014-599397f7523a.png)

So far, I've found this to affect Farmer's Delight Knives, and Immersive Engineering crafting tools. I'm looking into a different tool-crafting solution on FD's end, to make interactions more predictable and fix a bug with the Grindstone.

In the meantime, I'd like to propose a few suggestions for the Eternal Stella:

1. **Tool blacklist in the configs**, to disable specific items from being added to the Eternal Stella's crafting list;
2. **Smithing Table support**; the recipe would fit 1.16's Smithing Table nicely, avoiding duplication and unexpected crafting interactions.

Thanks for the attention! =)

**Comment by stal111** [comment]
Thank you for the feedback, but there is already an Item Blacklist for the Indestructible Enchantment (enchantments.indestructible.item_blacklist in the client config) and the recipes were originally planned for the Smithing Table but at the time I implemented these, JEI didnt have support for the Smithing Table, which means most people wouldnt have known about the recipe. Now that JEI added support for it I will probably change them to Smithing Recipes when I have time. :)

**Comment by vectorwing** [comment]
Ah, it was in the client config? Woops, should have checked first, sorry. x)
And glad to know it was planned! Thanks for your answer. 👍

**Comment by stal111** [comment]
Changed it to a Smithing Recipe in 1.16.3-1.0.2 :)

**Comment by Shorepion** [comment]
Plans to implement this config option to 1.16.5 please?

**Comment by stal111** [comment]
In 1.16.5 it has been changed to an item tag, so if you want to blacklist an item just add it to the forbidden_arcanus/tags/items/indestructible_blacklisted.json tag.

**Comment by Shorepion** [comment]
Alright! Thank you for the information 👍🏻
