### ISSUE TITLE
[1.16.3] Crash

### ISSUE THREAD

**Issue by WhitePhant0m** [stal111/Forbidden-Arcanus#103]
https://paste.gg/p/wphant0m/6a02ed1f151f4b5a92f39c309637fe0e
Seems to cause a crash _randomly_ as in, I've got no clue when it crashes, it just does. Something to do with the saplings?

**Comment by WiiZavV** [comment]
I can replicate by growing both "Forbidden and Arcanus"s sapling with bones meal in single player. Doing so does not crash the internal server but world generation thread does (it's just a little harder to replicate).

forge: `34.0.13`
Forbidden-Arcanus: `1.16.3-1.0.0`
note: clean install, with only forge and Forbidden-Arcanus

**Comment by stal111** [comment]
Was fixed in 1.16.3-1.0.1
