### ISSUE TITLE
[1.16.3][forge]conflict with Apotheosis to load Jei on server

### ISSUE THREAD

**Issue by Prophious** [stal111/Forbidden-Arcanus#104]
link to JEI issue https://github.com/mezz/JustEnoughItems/issues/2101

it seems that while both Apotheosis and Forbidden & Arcanus(with library mod) and JEI are installed JEI has trouble loading first time on a server, usually requiring a relog or starting in single player first then able to play on server with JEI just normally

have tested with minimum mods, where both Apotheosis and Forbidden & Arcanus can have JEI work individually together Jei does not work first time 

mirrored here https://github.com/Shadows-of-Fire/Apotheosis/issues/233

**Comment by stal111** [comment]
Is this still a problem with 1.16.3-1.0.2?

**Comment by UnseenAcademical** [comment]
Yes
