### ISSUE TITLE
Unable to find recipe for Runic tenebris frame

### ISSUE THREAD

**Issue by llRedbonell** [stal111/Forbidden-Arcanus#109]
Title. I've searched on the internet for about an hour now and the only times I've seen this item crafted are with four arcane ingots, one in each corner, four runic darkstone bricks, and dark matter in the middle. This recipe does not work for me. No idea how to craft this. 

pic related.

![frame](https://user-images.githubusercontent.com/72976146/96252495-ec45a480-0f66-11eb-8876-fe70930e5f41.png)

**Comment by stal111** [comment]
The recipe was broken, but I fixed it in 1.16.3-1.0.2.
