### ISSUE TITLE
[1.14.4] Request for Dark Stone

### ISSUE THREAD

**Issue by kwpugh** [stal111/Forbidden-Arcanus#11]
Hi,

I am the author of the Gobber mod. I have an item called the Ring of the Miner, that clears away vanilla stone and such, leaving ores exposed for mining.

I was wondering if you would consider tagging your Dark Stone with the Forge tag "STONE" so that I can easily identify them with if(Block.isRock() method?

isRock checks: net.minecraftforge.common.Tags.Blocks.STONE.contains(blockIn);

If you can add the forge tags for that block, it would make life a lot easier.

This would be a great help.

Thank you for considering.

Regards.

**Comment by stal111** [comment]
Done in forbidden_arcanus-1.14.4-1.0.

**Comment by kwpugh** [comment]
Thank you.
