### ISSUE TITLE
 forbidden_arcanus:soul

### ISSUE THREAD

**Issue by Thecatasuarus** [stal111/Forbidden-Arcanus#110]
The game crashed whilst rendering overlay
Error: java.lang.IllegalStateException: Failed to load description for particle forbidden_arcanus:soul
Exit Code: -1

**Comment by stal111** [comment]
I would need some more information (what forge version are you using, minecraft version, forbidden&arcanus version,...)

**Comment by Thecatasuarus** [comment]
I am using 1.16.3 -forge- 34.1.29

**Comment by Thecatasuarus** [comment]
i am using the most recent version of forbidden&arcanus

**Comment by andrewsf** [comment]
This ticket will probably exist longer than "the most recent version" is accurate. Please provide specific version numbers.

Perhaps a crash log? There should be a "crash-reports" directory.
