### ISSUE TITLE
Bug : Config files aren't working

### ISSUE THREAD

**Issue by Blugori** [stal111/Forbidden-Arcanus#111]
Hi, I ran into an issue, the config files aren't working (for cherrywood trees) :(

Minecraft : 1.16.3
F&A : 1.16.3-1.0.2
Forge : 34.1.25

I want to disable the generation of cherrywood trees. 
I tried to disable the option in the config file in the configs folder, then tried to disable it in the config file in the serverconfig folder (after creating a world), and then tried to put an edited config(serverside) file in the defaultconfig folder.
On every try I could found cherrywood trees in the worlds

I am only using F&A

**Comment by Neko2n** [comment]
Same, gonna bump this in the discord. Hoping for a fix soon.

**Comment by mosharky** [comment]
Same

**Comment by stal111** [comment]
Should be fixed in 1.16.4-1.0.0 :)
