### ISSUE TITLE
Server Crash: Ticking entity

### ISSUE THREAD

**Issue by ClaudiusMinimus** [stal111/Forbidden-Arcanus#115]
This morning I noticed my server was down and found the following:

[crash-2020-11-19_13.58.06-server.txt](https://github.com/stal111/Forbidden-Arcanus/files/5567877/crash-2020-11-19_13.58.06-server.txt)

Minecraft: 1.16.4
Forge: 35.0.17
Forbidden & Arcanus: 1.16.3-1.0.2

**Comment by Bright625** [comment]
I had the exact same thing... unable to launch my server now.

EDIT: nvm after using NBTExplorer I got it to launch, not using the pearls anymore tho.

**Comment by stal111** [comment]
Fixed in 16.2.0-beta-1.
