### ISSUE TITLE
Ticking entity - Black Hole

### ISSUE THREAD

**Issue by Nyctaeus** [stal111/Forbidden-Arcanus#119]
Hello. I play on Valhelsia 3.1.0 modpack and stumbled across server-crashing bug with Black Hole. Attaching log:

[crash-2020-12-23_02.46.43-server.txt](https://github.com/stal111/Forbidden-Arcanus/files/5732962/crash-2020-12-23_02.46.43-server.txt)

The affected Black Hole entity was collecting exp from Blaze exp farm and was placed above vanilla hopper. After restart I was able to rejoin server for 5-10 seconds then another crash was happening. After 2 or 3 times, I managed to reach the Black Hole and destroy it with pickaxe, effectively solving the issue.

**Comment by stal111** [comment]
Fixed in 16.2.0-beta-1.
