### ISSUE TITLE
[1.14.4] Client Crash on client update to forge 28.1.10

### ISSUE THREAD

**Issue by ProsperCraft** [stal111/Forbidden-Arcanus#12]
![2019-09-18_13 35 20](https://user-images.githubusercontent.com/4427684/65180187-88764280-da19-11e9-930f-30de57ddf9c3.png)

forbidden_arcanus-1.14.4-1.0

Log excerpt-
https://gist.github.com/ProsperCraft/a87f5f0eb1137927bbfb30f44e46a2f6

Full log-
https://gist.github.com/ProsperCraft/e15d0fd5f6af7171b7926e5839588de1

Modpack-
https://www.curseforge.com/minecraft/modpacks/the-adventures-of-halk

**Comment by ProsperCraft** [comment]
Server crashed as well - 
https://paste.fedoraproject.org/paste/E7eO5BbXJnIEt917He0umg

**Comment by stal111** [comment]
Fixed in forbidden-arcanus-1.14.4-1.1
