### ISSUE TITLE
Broken Ore Textures

### ISSUE THREAD

**Issue by knoxhack** [stal111/Forbidden-Arcanus#121]
Minecraft Version 1.16.4
Mod Version: forbidden_arcanus-1.16.4-1.0.0

[img]https://i.imgur.com/vPFRpCN.png[/img]

**Comment by VyProductions** [comment]
I just noticed this issue as well. It doesn't happen in valhelsia 3 where I was introduced to Forbidden and Arcanus, however it is happening in a separate modpack I put together.

**Comment by stal111** [comment]
Fixed in 16.2.0-beta-1.
