### ISSUE TITLE
1.6.14 Forbiddenmicon Blank

### ISSUE THREAD

**Issue by JustZoeExe** [stal111/Forbidden-Arcanus#122]
Howdy,

I saw an issue had been opened regarding this but was closed with no answer that I could see. I am currently starting the mod and wanted to use the Forbiddenmicon to help guide me however, it is currently blank, saying that it will be able to be read soon. Is this a feature of the mod that I need to figure out or is this a known issue with or without a fix?

Thanks in advance.

**Comment by Vaelzan** [comment]
When it says "will be able to be read soon", they mean that they haven't implemented it fully yet. It is still in development.

So it isn't a bug, just an incomplete feature that still requires work.
