### ISSUE TITLE
1.16.4 1.0.0 Crash interaction with CyclopsCore suite of mods

### ISSUE THREAD

**Issue by ZephyrWindSpirit** [stal111/Forbidden-Arcanus#123]
https://paste.ee/p/9u3Ft

Using a modified version of Enigmatica6, with forbiddenArcanus 1.0.0 1.16.4, and the just updated suite of mods for cyclopscore. It mentioned a resourcelocation null but keeps pointing at other mods. If you can find it, good luck. I spent over an hour trying to track it down.

**Comment by stal111** [comment]
Is this still an issue?
