### ISSUE TITLE
Spectral Eye Amulet causes high network usage on server

### ISSUE THREAD

**Issue by CorgiZero** [stal111/Forbidden-Arcanus#124]
1.16.4 / TNP Limitless 3 / Multiplayer

Whenever I turn on the spectral eye amulet on the official TNP server, my network usage spikes from around 0.5 - 1 Mbps to 5+ Mbps, to the point where ping spikes and I eventually time out. The issue occurs regardless of who is using the amulet, as long as I can see the effect that the amulet provides, network use spikes.

 I wasn't sure where to take this issue as it is partially a fault of my internet, but the sudden spike during use seemed like a problem that could be looked at.

**Comment by stal111** [comment]
1.16 is no longer supported. If this issue still occurs to you in 1.18 feel free to open a new issue and I will try to find a solution.
