### ISSUE TITLE
[Feature Request] Change recipes that use Arcane Gold Ingots or Nuggets to use the tag instead of the item.

### ISSUE THREAD

**Issue by Vaelzan** [stal111/Forbidden-Arcanus#127]
Since the Eidolon mod now also adds Arcane Gold and uses the same tags that Forbidden & Arcanus does, changing all the recipes that use Arcane Gold Ingots or Nuggets would allow for cross-compatibility between the two mods. 

Arcane Gold is similarly challenging to obtain in both mods, so any balance concerns are fairly minimal.

Both mods appeal to a similar type of player given the slightly dark magical theming and also have very compatible art styles, so I can see people wanting to use both mods together in a build and this would assist greatly.

Cheers Stal!

**Comment by stal111** [comment]
Took a while but I think all recipes use the deorum tags now. I guess it's unlikely we'll see another clash anytime soon with it being renamed do deorum but you never know.
