### ISSUE TITLE
[1.14.4] Update forbidden_arcanus-1.14.4-1.2.jar has a sidedness issue on dedicated servers.

### ISSUE THREAD

**Issue by ProsperCraft** [stal111/Forbidden-Arcanus#13]
https://gist.github.com/ProsperCraft/8fb4fe8138bbf7386848facb84c2385f

java.lang.RuntimeException: Attempted to load class net/minecraft/client/entity/player/ClientPlayerEntity for invalid dist DEDICATED_SERVER

forge-1.14.4-28.1.22

**Comment by ProsperCraft** [comment]
I guess forbidden_arcanus-1.14.4-1.1 doesn't like the forge update either, please update to Forge .22

https://gist.github.com/ProsperCraft/cb7222f297be65d1c47c1cdf1fe91526

**Comment by Rakambda** [comment]
The second comment could be another issue I guess. Though for the main part of the issue concerning the `DEDICATED_SERVER` I have the same on forge 1.14.4-28.1.20.

**Comment by stal111** [comment]
Fixed in forbidden-arcanus-1.14.4-1.3
