### ISSUE TITLE
(Suggestion) Config to disable the indestructible enchantment completely

### ISSUE THREAD

**Issue by honbee** [stal111/Forbidden-Arcanus#131]
As the title suggests, it would be very nice to be able to disable the indestructible enchantment completely in the config for balance reasons.

**Comment by Yourname942** [comment]
Yes, please add this config option!

**Comment by TheLewtz** [comment]
Totally, agree.  Been looking for a way around this, but only way i can find is just making the recipe harder, which would then negate the repair function of item

**Comment by stal111** [comment]
If you don't want the indestructible enchantment you could simply remove the recipe that applies the enchantment (apply_indestructible_enchantment.json).
