### ISSUE TITLE
Blood Magic Indestructible Items Still take damage.

### ISSUE THREAD

**Issue by tyler489** [stal111/Forbidden-Arcanus#132]
Enchanted Explosive Powder with indestructible and it still takes damage in their special ARC furnace. Im 99% sure its on bloodmagic but if you could perhaps explain how your enchant works that would be great.https://github.com/WayofTime/BloodMagic/issues/1754

**Comment by Nubidubi23** [comment]
I'm not entirely sure but i think it only heals in your inventory (just a guess , don't take my word for it)

**Comment by tyler489** [comment]
It makes the item indestructable and not take damage period.
