### ISSUE TITLE
Petrified Roots render incorrectly underwater

### ISSUE THREAD

**Issue by WenXin20** [stal111/Forbidden-Arcanus#134]
`Minecraft v1.16.5`
`Forge v36.0.1`
`F & A v1.0.0`

If Petrified Roots spawn or are placed underwater, it will render incorrectly with water flowing down it's sides. This can be fixed using `shouldDisplayFluidOverlay`.

**Comment by stal111** [comment]
This is now fixed in Minecraft 1.17+ versions.
