### ISSUE TITLE
Tetra items not retaining Indestructible after honing.

### ISSUE THREAD

**Issue by AefRal** [stal111/Forbidden-Arcanus#135]
## Bug Report
I applied Eternal Stella to my Tetra pick in the Smithing Table, and it worked as intended(Became unbreakable).

**Observed Behaviour**
After honing it, it started to take damage during use as before. No longer unbreakable.
_Also didn't list the text "Unbreakable" like other enchants._

I then tested with vanilla enchantment books on another Tetra pick. 
I honed it when it became available, and the vanilla enchantment stayed.

_The Tetra Workbench doesn't seem to accept the Eternal Stella as an enchantment either._

**Expected Behaviour**
For the tool to remain unbreakable.
_(also listing the word "Unbreakable" or "Indestructible" in the tool description.)_

**Minimal setup needed to reproduce**
-Tetra + Dependencies
-Forbidden and Arcanus

- Forge version: 1.16.4 - forge-35.1.29
- Tetra version: tetra-1.16.4-3.5.3.jar
- Tetra configuration: Default
- Forbidden and Arcanus version : forbidden_arcanus-1.16.4-1.0.0.jar
- Forbidden and Arcanus configuration: Default

- Other mods:
Valhesia 3 - 1.16.4 Modpack
**Steps to reproduce**

1. Get Tetra tool via workbench.
2. Apply Eternal Stella in Smithing Table, making tool indestructible.
3. Use until honing becomes available and hone it.
4. Use to break a single block to see green durability bar appear.
...
5. Weep, because it took forever to find a Stellerite Piece.
6. Go in creative to get another Eternal Stella.

**Comment by stal111** [comment]
I think that's an issue on Tetra's side. Could you open an issue on their tracker if there isn't already one?

**Comment by AefRal** [comment]
I believe when I submitted the issue, I did so on both mod's page.
