### ISSUE TITLE
[Suggestion] Config to make Obsidian Skull/Shield not protect from lava.

### ISSUE THREAD

**Issue by Crazydude323** [stal111/Forbidden-Arcanus#136]
It would be nice to have a config option to make the Obsidian Skull (and shield) only protect from fire damage, not lava damage. I know it's two different damage sources on account of things like the Infernal Claws from Reliquary, which protect from fire, but don't stop lava damage.

It would be especially nice for balance reasons, in order to keep the nether somewhat dangerous.

**Comment by stal111** [comment]
Problem is that the current Obsidian Skull gives the player the Fire Resistance potion effect which protects from both damage sources. Because of that a config option to not protect from lava is not possible but I'm open for other suggestions on how to improve and balance the Obsidian Skull.
