### ISSUE TITLE
Bone tools not working

### ISSUE THREAD

**Issue by Explode007** [stal111/Forbidden-Arcanus#137]
Yeah... just bone tools don't bone meal and the hoe crash which is already discussed elsewhere.

**Comment by ClaudiusMinimus** [comment]
Same thing here
Using the hoe on grass was fine, but using it on farmland caused the crash.
forbidden_arcanus-1.16.4-1.0.0
https://paste.ee/p/mJCWY

**Comment by stal111** [comment]
Bone tools have been removed in 16.2.0.
