### ISSUE TITLE
[1.16.4] Canelabras (with candles) do not give off light.

### ISSUE THREAD

**Issue by Sandriell** [stal111/Forbidden-Arcanus#138]
As stated in the title, candelabras, with added candles (no matter the number) do not give off any kind of light.

Minecraft: 1.16.4
Forge: 35.1.28
Mod: 1.16.4-1.0.0

**Comment by ClaudiusMinimus** [comment]
Minecraft: 1.16.5
Forge: 36.1.0
forbidden_arcanus-16.2.0-beta-3

Candelabras still do not give light as shown in the screenshot with Light Level Overlay showing dark spot.

![image](https://user-images.githubusercontent.com/17887664/111855705-fe4bba80-88eb-11eb-9eea-ff707f99d22d.png)

**Comment by stal111** [comment]
Candles and Candelabras are no longer a thing in the 1.18 version of the mod, thus I'm closing this.
