### ISSUE TITLE
Arcane Golden Doors don't work

### ISSUE THREAD

**Issue by Hellpug** [stal111/Forbidden-Arcanus#139]
Hi,

I built an arcane golden door and it doesn't open and close. Tried it in various spots to make sure and yeah just doesn't. Would like this to work as it's a very pretty door!

**Comment by hjpoe** [comment]
Did you try using a button or a pressure plate on an adjacent block? If I had to guess, it would be related to an iron door in that respect.

**Comment by Hellpug** [comment]
My bad! I haven't used iron doors in a while. Thanks!
