### ISSUE TITLE
Can't right-click logs w/ axes to gain Stripped Wood

### ISSUE THREAD

**Issue by WenXin20** [stal111/Forbidden-Arcanus#14]
`Minecraft v1.14.4`
`Forge v28.1.26`
`Forbidden & Arcanus v1.3`

It's is impossible to obtain the stripped variants of logs from this mod.

Right-clicking the cherrywood or mysterywood logs with any axe, modded or otherwise, won't strip the logs

**Comment by stal111** [comment]
Fixed in forbidden_arcanus-1.14.4-1.4-beta-2
