### ISSUE TITLE
Indestructable Blacklist removes Staffs from Elemental Staff Mod

### ISSUE THREAD

**Issue by Asveste** [stal111/Forbidden-Arcanus#140]
If I put "element:staffelectric" in the blacklist for the indestructable enchantment it gets removed on startup.
I dont know if it's a bug or if I need to write it in a different way, so help is appreciated.

**Comment by stal111** [comment]
Does this still happen in 16.2.0-beta-3?

**Comment by stal111** [comment]
my bad, the blacklist is now a tag (forbidden_arcanus/items/indestructible_blacklisted), so this shouldn't be an issue anymore

**Comment by Asveste** [comment]
Yes, it works after giving the staff the tag.
