### ISSUE TITLE
Ores not dropping when mined

### ISSUE THREAD

**Issue by Taccio33** [stal111/Forbidden-Arcanus#142]
Maybe it's just a forge thing but I'm on latest version of the mod, 1.16.5 and forge 36.0.14 and ores like arcane ore, stella arcanum and xpetrified are not dropping. Exploding a stella arcanum near then seem so drop the items itself. On random video I've seen that they are harvestable, but maybe I'm a derp and I need something specific?

**Comment by stal111** [comment]
Just tested and the drops work as they should, if this is still an issue in the most recent version feel free to reopen the issue.
