### ISSUE TITLE
Crash without JavaFX

### ISSUE THREAD

**Issue by Dunkmania101** [stal111/Forbidden-Arcanus#143]
This seems to be an issue on Valhelsia's end since it still happens with only Valhelsia Core installed, but they don't have an issue tracker and it still affects this mod, so I figured I should put this somewhere.

Essentially, my client and server both crash on start with Valhelsia Core, required by 16.2.9-beta-1 (Forge 1.16.5-36.0.22). The log is complaining about a mixin and not being able to find a class called Pair from JavaFX, which my installation (at least as far as I know) lacks.

Debug.log:
[log](https://gist.github.com/Dunkmania101/330431fb6fdc8d1c49e13fbe8ac77384)

**Comment by stal111** [comment]
Should be fixed in Valhelsia Core 16.0.3

**Comment by Dunkmania101** [comment]
Hey, sorry for the delay. It does seem to be fixed, so I'll close this now. Thanks!

As a side note, I managed to completely spell "Thanos" while trying to type "Thanks". What a world we live in!
