### ISSUE TITLE
Most of the client config should be in the common or server config.

### ISSUE THREAD

**Issue by Vaelzan** [stal111/Forbidden-Arcanus#145]
I'm preparing a script to generate the server packs automatically for Valhelsia, which deletes all client configs (which seems logical - servers don't need them), but a lot of the Forbidden and Arcanus config for common or server things is in the client config, so it isn't safe to delete it even on a server.

Of the things currently in the client config, only the rendering section should stay. The rest should probably be in a common config (ideally avoid using the server config except for world generation, since it's per-world).

**Comment by stal111** [comment]
Changed it in 16.2.0-beta-3 :)
