### ISSUE TITLE
(Old Version, 1.12, but need help) No configs? OP Cloth armor?

### ISSUE THREAD

**Issue by Davrial** [stal111/Forbidden-Arcanus#146]
I recently made a modpack just for playing with friends, and I really like this mod as a whole, but there's a few items that are extremely OP, and I was looking to configure them, but when i went to do so, I found out there's no config files at all! Are there supposed to be? How can i fix this?
The specific thing that definitely needed fixed was the cloth armor, which takes literally only normal bones, wool, and string, and makes armor that's better than vanilla diamond. I could theoretically change the recipe but i figured there might be a way to fix this that's just bugged for me? Or perhaps im just missing something? I even tried to find a mod that allows me to just adjust armor on the server side, so i dont have to push yet another update to my friends.
I saw that the recipes are pretty easily changed via JSON in the JAR, but that doesnt help if my friends update via Forge and dont get the jar change from me. Is it possible to overwrite those via a custom config or anything? Or a way to do something similar but with the armor values?
I know this could all be theoretically fixed with just using CraftTweaker to make it more expensive, but id rather just make it weaker if possible, instead of making it more expensive to make to begin with

**Comment by stal111** [comment]
1.12 is no longer supported, please update to a newer version.
