### ISSUE TITLE
Another JavaFX crash

### ISSUE THREAD

**Issue by ZeekDaGeek** [stal111/Forbidden-Arcanus#147]
forbidden_arcanus-16.2.0-beta-1.jar
valhelsia_core-16.0.3.jar

After searching the issues it seems like you're attempting to remove JavaFX related problems (https://github.com/stal111/Forbidden-Arcanus/issues/143), here's another JavaFX crash from Forbidden Arcanus instead of the Core.

Crash log:
https://gist.github.com/ZeekDaGeek/f74861f8dd65afbb41b2d15a2edaebc8

It appears the solution is to use `com.mojang.datafixers.util.Pair` instead of `javafx.util.Pair`? https://github.com/gorilla-devs/GDLauncher/issues/674

**Comment by stal111** [comment]
was fixed in 16.2.0-beta-2
