### ISSUE TITLE
[Bug] Missing Blocks when joining Multiplayer (LAN)

### ISSUE THREAD

**Issue by Syrent93** [stal111/Forbidden-Arcanus#148]
Hello there,

I got the problem while hosting a server with the newest version of forge and forbidden-arcanus16.2.0-beta-2 the following error, while someone tries to join:

Missing registry data for network connection: minecraft:block: forbidden_arcanus:bottle_block minecraft:block: forbidden_arcanus:corrupted_pixie_in_a_bottle_block minecraft:block: forbidden_arcanus:pixie_in_a_bottle_block 
21:15:30.767
Failed to load registry, closing connection.
21:15:30.768
Connection closed, not continuing handshake

We tried to take an older version from the mod and copy the config and replace it without success.

This error reproducible. Any ideas?

Thanks!

**Comment by stal111** [comment]
did you also update f&a on the client to 16.2.0-beta-2?

**Comment by Syrent93** [comment]
Yes thats the strange thing, same version I also tried to copy the config files to the client with zero effort. On the server everything works fine.

**Comment by Syrent93** [comment]
And one more thing I like to add, before the beta-2 update everything worked fine, after that the error comes up. But even if the Server and client install the beta-1 version the error comes still up.

**Comment by Syrent93** [comment]
Any ideas?

**Comment by Syrent93** [comment]
[latest_Server.log](https://github.com/stal111/Forbidden-Arcanus/files/6083297/latest_Server.log)
[latest_client.log](https://github.com/stal111/Forbidden-Arcanus/files/6083298/latest_client.log)

**Comment by Syrent93** [comment]
Found the solution myself, after i created a new world and copy the level.dat and some other stuff to the old world and then it works.
