### ISSUE TITLE
Exception in server tick loop

### ISSUE THREAD

**Issue by ClaudiusMinimus** [stal111/Forbidden-Arcanus#149]
Minecraft Version: 1.16.5
Java Version: 1.8.0_265
Forge: 36.0.43
Forbidden & Arcanus: 16.2.0-beta-1

Not sure what happened, just came back from lunch and the server had crashed.

https://pastebin.com/RXgYihmG

**Comment by stal111** [comment]
Update to 16.2.0-beta-2 or beta-3
