### ISSUE TITLE
[1.14.4] game not launching

### ISSUE THREAD

**Issue by Gbergz** [stal111/Forbidden-Arcanus#15]
Forge Version: 28.1.20
Mod Version: 1.4-beta2
MC Version: 1.14.4

Logs: [https://gist.github.com/Gbergz/23def82f281138eac46a48435643ead3](https://gist.github.com/Gbergz/23def82f281138eac46a48435643ead3)

**Comment by stal111** [comment]
Update to forge 28.1.44
