### ISSUE TITLE
Your mod throws an exception when Minecolonies citizens kill an entity

### ISSUE THREAD

**Issue by ruestJS** [stal111/Forbidden-Arcanus#150]
Modpack: Valhelsia 3 (3.1.9)
Minecraft version: 1.16.5
Forbidden and arcanus version: 16.2.0-beta1

Like said in the title, your mod throws an exception when Minecolonies citizens kill an entity, which crash the AI of certain citizens.

Here's the log i sent to the Minecolonies dev in which they found the problem: https://gist.github.com/Davoskaa/e1d6fc4e71a1bdc83d817c3bbe03bf71

**Comment by stal111** [comment]
Please only report bugs with the newest version installed, the bug was fixed in 16.2.0-beta-3.
