### ISSUE TITLE
The Nether is unplayable, this mod latest versions beta 1-3 in custom modpack. (MYSTERY SOLVED)

### ISSUE THREAD

**Issue by TheWitherlord** [stal111/Forbidden-Arcanus#151]
Hi!
I understand this version is beta, and I have decidedly downgraded it because of a very critical issue with my custom mod pack that I can't seem to figure out.

my modpack: https://www.curseforge.com/minecraft/modpacks/geosmelt-1-16-4

The issue first starts with: forbidden_arcanus-16.2.0-beta-1
and modpack version: 1.33

I checked the latest valhelsia 3 version you guys put out it works fine, there is something messing with Forbidden in my pack and I only have a basic understanding of forge modding.

I have been at this for almost 48 hours now. I have been looking for the mod or mods that are not letting Forbidden and Arcanus do its job. I remove Forbidden and Arcanus (Latest version:forbidden_arcanus-16.2.0-beta-3) and the nether allows me to place blocks and interact with entities. However, when it's in the pack with every mod (I have done some elimination efforts too) the nether lags so bad the game renders it crashed. (TPS lag) 

Here is a log:
https://gist.github.com/TheWitherlord/e7f8c3cab4214bc0adc4ffb4b7d722ab#file-log-latest

No, debug log for some reason.

I am not getting a crash report either...

If you don't have enough info, or you didn't think I looked hard enough, close this issue and I will just settle with the last version of Forbidden-Arcanus which works with every mod. I will keep looking too, I hope this can be helpful if anyone else comes across a weird issue like this.

Thanks!

**Comment by TheWitherlord** [comment]
The world crashes when I hit quit to menu so I have to open task manager to kill it.

**Comment by TheWitherlord** [comment]
Both Rats and Ratlantis causes this error.

**Comment by starmun-0010** [comment]
Flux networks (FluxNetworks-1.16.5-6.1.6.11) installed together with this beta version also causes the very same issue of nether deadlock/freeze.

**Comment by aking4125** [comment]
I JUST narrowed down this problem to this mod. It was driving me nuts trying to figure out the cause of the Nether lag.

Downgrading to the old release completely fixes this problem entirely.

**Comment by Teldenes** [comment]
What version did you Downgrade to?

**Comment by starmun-0010** [comment]
@Teldenes  forbidden_arcanus-1.16.4-1.0.0.jar

**Comment by stal111** [comment]
Disable the spawning of Demon Rats. The issue is something Rats needs to fix.
