### ISSUE TITLE
Edelwood Ladder doesn't work

### ISSUE THREAD

**Issue by CerbTheOne** [stal111/Forbidden-Arcanus#152]
The edelwood ladder doesn't seem to be working at all on the latest version. Trying to climb it using the 'w' key also prevents the player from jumping. I tested it with Forge version 36.0.58, Valhelsia Core version 16.0.6 and Forbidden & Arcanus version 16.2.0 beta 3. These are the latest versions of the mods (and modloader) as of writing this bug report.

**Comment by stal111** [comment]
Fixed in 16.2.0-beta-4.
