### ISSUE TITLE
Feature Suggestion

### ISSUE THREAD

**Issue by desagas** [stal111/Forbidden-Arcanus#156]
If at all possible, it would be nice if Indestructible replaced "unbreaking" rather than being incompatible with it. I do not know if this is possible with the table, but, it would help out a lot.

**Comment by stal111** [comment]
Probably wont add this. Players should pay attention to the enchantments they add to a tool, and besides of that nearly every modpack has a way to remove enchantments from items. Thank you for the suggestion though!
