### ISSUE TITLE
Glass Renders Incorrectly Underwater

### ISSUE THREAD

**Issue by WenXin20** [stal111/Forbidden-Arcanus#16]
#### Versions (Be specific, do not write "latest"):
 * Forbidden & Arcanas: v1.3
 * Forge: v28.1.44

#### Description of a Bug:
- Placing any glass-like block, including End Crystal Gems, Dark Beacons, and Runic Glass, underwater will render incorrectly underwater, with water flowing down the sides. Glass should render similarly to Minecraft Glass
- ~~Custom signs also can only be placed on the ground, but not on walls.~~ (fixed)

#### Image:
![2019-10-12_01 42 13](https://user-images.githubusercontent.com/12000593/66696426-8e1a1d80-ec91-11e9-88c9-778be85f5aa7.png)

**Comment by WenXin20** [comment]
This can be fixed in 1.15+ by using the boolean `shouldDisplayFluidOverlay()`

**Comment by stal111** [comment]
Fixed in 1.16.3-1.0.2 :)
