### ISSUE TITLE
Quantum Catcher Offset Suffocates Mobs

### ISSUE THREAD

**Issue by DereC4** [stal111/Forbidden-Arcanus#160]
If you place the mob in an open area it will be fine but if you want to move mobs into more cramped spaces such as villager trading halls it places the mob at a corner of the block which usually leads to it taking suffocation damage, and sometimes dying. I was wondering if there was a way to make the mob be placed in the center of the block instead.

**Comment by stal111** [comment]
Fixed in 16.2.0-beta-4.

**Comment by DereC4** [comment]
Ok thanks
