### ISSUE TITLE
Suggestion: make Cherrywood and Mysterywood saplings compostable

### ISSUE THREAD

**Issue by Mooncat25** [stal111/Forbidden-Arcanus#161]
### Issue
The 2 saplings from this mod, Cherrywood Sapling and Mysterywood Sapling, are not accepted by the vanilla Composter.

### Suggestion
Make them compostable in Composter with 30% chance to add a layer of compost.

### Environment
Minecraft 1.16.5
Forge 36.1.13
Forbidden & Arcanus 16.2.0-beta-3
Valhelsia Core 16.0.6

**Comment by Mooncat25** [comment]
Side note: I have written a simple KubeJS server script to make them compostable, for those who can't wait for the suggestion to get implemented:
```
onEvent('recipes.compostables', event => {
    event.add('forbidden_arcanus:cherrywood_sapling', 0.3)
    event.add('forbidden_arcanus:mysterywood_sapling', 0.3)
})
```

**Comment by stal111** [comment]
These two saplings are now finally compostable in version 2.1.0-beta1.
