### ISSUE TITLE
Conflict with Apotheosis

### ISSUE THREAD

**Issue by Nubidubi23** [stal111/Forbidden-Arcanus#162]
If you have both mods installed and break a spawner with silk touch , it always drops a Spawner Scrap from F&A. Doesn't happen without F&A obviously

Minecraft 1.16.5 , Forge 36.1.0 ,
forbidden_arcanus-1.16.4-1.0.0 ,
Apotheosis-1.16.3-4.4.1

**Comment by Nubidubi23** [comment]
Mirror : https://github.com/Shadows-of-Fire/Apotheosis/issues/367

**Comment by stal111** [comment]
Should be fixed in 16.2.0-beta-4.
