### ISSUE TITLE
Incorrect rendering of emissives with optifine versions starting from 1.16.5_HD_U_G8_pre3 and shaders

### ISSUE THREAD

**Issue by gri573** [stal111/Forbidden-Arcanus#165]
The issue appears to be the same as this one:

https://github.com/refinedmods/refinedstorage/issues/2919

![unknown.png](https://user-images.githubusercontent.com/66473137/119224887-e4ec0800-bb00-11eb-9fd4-4dcaff4910eb.png)

**Comment by Gaxon1** [comment]
Confirmed, Arcane Crytsal Ore, Arcane Crystal Block, Dark Runestone, Xpetrified Ore and Runestone.
![Glitch](https://user-images.githubusercontent.com/70067651/120084133-83ddaa80-c093-11eb-810d-3f19389d13ff.jpg)

**Comment by stal111** [comment]
Fixed in 16.2.0-beta-4.
