### ISSUE TITLE
Crash on startup 1.14.4

### ISSUE THREAD

**Issue by MelanX** [stal111/Forbidden-Arcanus#17]
Tried to play Unstable 1.14.4 and there the game crashed because of Forbidden Arcanus

Modpack version: 1.10.0
Mod version: 1.4-beta-2
Forge version: 28.1.44
Crash log: https://pastebin.com/nrEVTg1W

You need more information? Let me know!

**Comment by stal111** [comment]
Are you using OptiFine? If so, pleasy try launching without it.
