### ISSUE TITLE
Arcane crystals VERY rarely spawning

### ISSUE THREAD

**Issue by MadHattress** [stal111/Forbidden-Arcanus#170]
It says they're common like iron, but I went strip mining for a while and found 40 diamonds, 18 emeralds, no arcane crystals. I'm looking between 8-15 y. I have found them in the past so I know they exist. But I don't think they're supposed to be this rare according to the wiki? Can anyone help?

**Comment by stal111** [comment]
What version are you on? Just tested and they spawn fine for me.

**Comment by stal111** [comment]
Closing this as there was no response.
