### ISSUE TITLE
Loading Issues

### ISSUE THREAD

**Issue by Cromch** [stal111/Forbidden-Arcanus#172]
The latest version of the mod, with Valhesia Core, consistently causes servers to time out.

**Comment by stal111** [comment]
Without a crash log/latest log I wont be able to do anything about it.

**Comment by brumoen** [comment]
We are seeing the same issue in OverKill SMP, after teleporting to the Nether the server just hangs until Watchdog kills it for not responding within 120 seconds. 
Rolling back to Forbidden Arcanus 1.16.4-1.0.0 from 16.2.0-beta-4 fixes the issue.

[crash-2021-06-19_12.07.51-server.txt](https://github.com/stal111/Forbidden-Arcanus/files/6680472/crash-2021-06-19_12.07.51-server.txt)
[debug.log](https://github.com/stal111/Forbidden-Arcanus/files/6680473/debug.log)
[latest.log](https://github.com/stal111/Forbidden-Arcanus/files/6680474/latest.log)

**Comment by stal111** [comment]
@brumoen Disable the spawning of Demon Rats. The issue is caused on Rat's side and unfortunatly we cannot do anything about it.
