### ISSUE TITLE
Arcane Gold Door and Arcane Pressure Plate not functional

### ISSUE THREAD

**Issue by gehodge** [stal111/Forbidden-Arcanus#174]
Using Valhelsia 3.3.3, Forbidden Arcanus version 16.2.0 beta 4

Placed Arcane Gold door down, not openable with pressure plate or button, can hear door opening sound but no open door animation and cannot walkthrough

Arcane gold pressure plate, unable to open iron door.

**Comment by stal111** [comment]
Cannot reproduce this. Is it still an issue?
