### ISSUE TITLE
[BUG] the flight effect appears by itself

### ISSUE THREAD

**Issue by GitJhopa** [stal111/Forbidden-Arcanus#176]
I use the Mohist core, where I play players on your mod, the players themselves had a flight effect and hung on the timer 00:00, they did not use anything, but just dug a mine, there are also bugs with fire resistance effects, they also appear and disappear for 1 second.

**Comment by GitJhopa** [comment]
![image](https://user-images.githubusercontent.com/86250668/124197474-44154300-dad7-11eb-9d9c-c07a5a54fabc.png)

**Comment by stal111** [comment]
Report this to the Mohist bug tracker. The issue is most likely caused on their end as it works without mohist.
