### ISSUE TITLE
[1.14.4] Logs are being spammed with errors

### ISSUE THREAD

**Issue by Gbergz** [stal111/Forbidden-Arcanus#18]
**Describe the issue**
The logs are being spammed with **[this](https://gist.github.com/Gbergz/2bb80b9435511a4fc0ee22c74299f5a6)**, wondering if there's any possibility of a fix? It's not just this message it's multiple, many lines.

**Version(please complete the following information):**
 - Forbidden & Arcanus: 1.3
 - Forge: 28.1.44

**Comment by stal111** [comment]
Fixed in 1.14.4-1.5-beta-4
