### ISSUE TITLE
Candles don't emit light when on Candelabra

### ISSUE THREAD

**Issue by Darkxel** [stal111/Forbidden-Arcanus#180]
Hi,

I'm playing MC 1.16.4 Modpack ATM6 on Version 1.7.1. 
I don't use Resourcepack or Shaders.

The candles don't emit light when they are on the Candelabras.
When used alone or in candle lamps they work fine.

o7

![javaw_0YZM4HZJBd](https://user-images.githubusercontent.com/11840002/126222211-9fe0f00d-2753-479b-8acf-6c5c3a42cc7e.png)
![javaw_Ggi292hgjL](https://user-images.githubusercontent.com/11840002/126222215-54bb9b43-6eee-4090-8051-7248b37fb44b.png)
![javaw_MDJnrrzYT0](https://user-images.githubusercontent.com/11840002/126222217-b3bebbcd-689a-47ec-8741-1460d13d4f19.png)

**Comment by stal111** [comment]
Candles and Candelabras are no longer a thing in the 1.18 version of the mod, thus I'm closing this.
