### ISSUE TITLE
Mod conflict with Rats

### ISSUE THREAD

**Issue by TheTechPny** [stal111/Forbidden-Arcanus#186]
Using the most recent version of Rats, Citadel, and Valhelsia Core plus ANY BETA version of Forbidden Arcanus produces an easily replicatable server timeout.

With the mods installed just go into the nether and start generating new chunks, very quickly the server will freeze and no more chunks will be generated. The client can still move around and do whatever.

**Comment by stal111** [comment]
As already said in similar issues: disable the spawning of Demon Rats. The issue is caused on Rat's side and unfortunately we cannot do anything about it.

**Comment by theCalcaholic** [comment]
FYI, there's an open issue on rats' side: https://github.com/Alex-the-666/Rats/issues/713
