### ISSUE TITLE
Conflict with Apotheosis

### ISSUE THREAD

**Issue by Cadock** [stal111/Forbidden-Arcanus#188]
When both Apotheosis and Forbidden & Arcanus are installed then spawner scrap does not drop when breaking spawners. Assuming this may be because Apotheosis replaces vanilla spawners with its own.

**Comment by charlielyne1** [comment]
Having this issue too, playing Better Minecraft Plus. Scraps will not drop in the current version - v22

**Comment by stal111** [comment]
Duplicate of #171
