### ISSUE TITLE
Entity duplication w/ Quantum Catcher

### ISSUE THREAD

**Issue by Z4RM** [stal111/Forbidden-Arcanus#189]
When you have Quantum Catchers stacks and you pick an entity, all the stack have the entity in his NBT and when you de-stack ou have many entities (exemple : 4 Quantum Catchers stack and I take blaze, I have 4 blazes)

**Comment by stal111** [comment]
What version of the mod are you using? This should be fixed in the newest beta if I remember correctly.

**Comment by Z4RM** [comment]
I play on Ragnamod VI and it's *forbidden_arcanus-1.16.4-1.0.0*
I will notice MLDEG for the next update if he doesn't

**Comment by stal111** [comment]
Then please update to the latest beta or tell the pack author to update Forbidden & Arcanus in the next release.
