### ISSUE TITLE
Old arcane_dark_stone appearing in JEI

### ISSUE THREAD

**Issue by MarsCBG** [stal111/Forbidden-Arcanus#191]
From what I can tell a remnant from before the switch-up of darkstone is still in the code. Only seems to be the texture and model files but JEI is picking it up as a proper block.
![image](https://user-images.githubusercontent.com/91651668/135393029-736c818c-c1ce-45c9-8f01-25669bd9de26.png)

**Comment by stal111** [comment]
Has been fixed in the the 1.18 version of the mod.
