### ISSUE TITLE
[1.16.5] Don`t respawn 

### ISSUE THREAD

**Issue by Rumaruka** [stal111/Forbidden-Arcanus#196]
Version mod: 16.2.0-beta-4.
Minecraft: 1.16.5
Forge: 36.2.8

After dead (different solution) and click "Respawn" player don`t respawned again

**Comment by stal111** [comment]
Does this happen with only forbidden & arcanus installed? If not I would need to know what other mods you are using and it might be worth checking if the log contains anything relevant.

**Comment by Rumaruka** [comment]
Im found bugs in other mods, sorry

**Comment by notWaterGuy12** [comment]
Hey, sorry to bug people in a old issue, but what mod was causing the problem? I'm having the same issue right now
