### ISSUE TITLE
[1.16.5] World fails to fully load

### ISSUE THREAD

**Issue by HockeyZman2000** [stal111/Forbidden-Arcanus#198]
Latest Log:
[latest.log](https://github.com/stal111/Forbidden-Arcanus/files/7499755/latest.log)

The server does not crash, but when the server startup process hits world loading it stalls/hangs and never fully loads. Version 1.0.0 does not have this problem, however the current version (16.2.0 beta 4) and the past couple versions have had the same problem. Removing the mod allows the world to fully load. Disabled Demon Rats from Rats from naturally spawning but that does not fix the issue either. Please help!

**Comment by stal111** [comment]
Could you try with the new f&a version?

**Comment by Ozzi-Hero** [comment]
Issue is still happening with the most recent version of F&A and Majrusz's Progressive Difficulty on 1.16.5
