### ISSUE TITLE
Sapling in Flowerpot Crash the Game

### ISSUE THREAD

**Issue by kaffeekirsche** [stal111/Forbidden-Arcanus#20]
**Describe the bug**
When I place a Cherrywood Sapling or a Mysterywood Sapling in a flower pot. Crashes the game when I look at this.

**To Reproduce**
1. Place a Flowerpot
2. Place a Cherrywood Sapling or a Mysterywood Sapling in it
3. Target the Flowerpot

**Crash Report**
[crash-2019-11-01_19.31.56-client.txt](https://github.com/stal111/Forbidden-Arcanus/files/3799249/crash-2019-11-01_19.31.56-client.txt)

**Version(please complete the following information):**
 - Forbidden & Arcanus: forbidden_arcanus-1.14.4-1.4
 - Forge: 1.14.4 - 28.1.76

**Comment by stal111** [comment]
Not reproducable
