### ISSUE TITLE
Waterlogged Block bypass Edelwood Bucket Water Limit

### ISSUE THREAD

**Issue by StellaBiscuit** [stal111/Forbidden-Arcanus#203]
When you use an Edelwood Bucket on a Waterlogged block, it will get the water even if the bucket already has 4 water inside it
Also, when there is too much icon, the game will just stop extending the tooltip box

Screenshot (In this case, the bucket icons goes past the screen since I filled it with like 40 unit of water)

![image](https://user-images.githubusercontent.com/53101126/142743091-06157f00-11b0-49a8-9c61-9a91fd4f14dc.png)

**Comment by StellaBiscuit** [comment]
Extra Note, if you bypass the limit, you will be allowed to fill the bucket infinitly even on basic water. In other words, the limit only work when you have 4 water unit in it, going past it will ignore the limit

**Comment by stal111** [comment]
Fixed in 16.2.3
