### ISSUE TITLE
Creating and interacting with Hephaestus Forge crashes on dedicated server

### ISSUE THREAD

**Issue by Verquinox** [stal111/Forbidden-Arcanus#204]
When I right-clicked with Mundabitur dust to create the Hephaestus Forge it crashed the server I was playing on. When it was put back up everything was fine again until I right-clicked the forge to interact with it, at which point it crashed again.

If necessary I will obtain and provide crash logs.

**Comment by stal111** [comment]
Fixed in 16.2.2
