### ISSUE TITLE
Mysterywood sapling crashing server

### ISSUE THREAD

**Issue by ClaudiusMinimus** [stal111/Forbidden-Arcanus#205]
In my mod pack [Create on a Potato PC](https://www.curseforge.com/minecraft/modpacks/create-on-a-potato/files/3529942) it seems the Mysterywood sapling is crashing our server. It seems to crash when the sapling is trying to grow. I tested in a singleplayer world and if I bonemeal it the sapling disappears, but the game does not crash. I had other players test this and they found the same behavior.

Minecraft: 1.16.5
Forge: 36.2.9
Forbidden & Arcanus 16.2.1

[crash-2021-11-21_20.24.00-server.txt](https://github.com/stal111/Forbidden-Arcanus/files/7577044/crash-2021-11-21_20.24.00-server.txt)
Same  report above in Crashy
https://crashy.net/Qul2imuf96DnaMSxlV69

**Comment by starmun-0010** [comment]
Same crash with cherrywood.

**Comment by stal111** [comment]
Fixed in 16.2.2
