### ISSUE TITLE
book crash

### ISSUE THREAD

**Issue by Warbringer12** [stal111/Forbidden-Arcanus#206]
forge version: 1.16.5
mod version: 16.2.1

1. open book
2. clicked on blast furnace in one of the recipes and crashed
[crash-2021-11-24_00.27.33-client.txt](https://github.com/stal111/Forbidden-Arcanus/files/7593970/crash-2021-11-24_00.27.33-client.txt)

**Comment by stal111** [comment]
The Forbiddenmicon is not finished and thus unsupported at the moment.
