### ISSUE TITLE
Edlewood bucket - Immer Enginering Coke Oven Compat

### ISSUE THREAD

**Issue by starmun-0010** [stal111/Forbidden-Arcanus#207]
Empty edlewood bucket placed in an Immersive Engineering coke oven with enough creosote oil gives a vanilla iron bucket as output.
Is this intended?

**Comment by stal111** [comment]
Fixing this would require quite a large rework of the whole Edelwood Bucket system which I don't have the time for in 1.16. The issue should be fixed in 1.18 though.
