### ISSUE TITLE
bug by right click with mods bucket

### ISSUE THREAD

**Issue by GalaxyOfZero** [stal111/Forbidden-Arcanus#208]
Describe the bug:
when right click with a bucket from the mods Forbidden & Arcanus and Wooden buckets on a wooden crucible, turn into an bucket from Minecraft. 
This also happens with the Ex Nihilo: Sequentia wooden crucible
unfortunately I can not say more

To Reproduce

1. Place block ' wooden crucible'
2. Right click on ' Bucket, see describe'
3. Do thing ' turn into Minecraft bucket'

GalaxyOfZero/Skyfriends#1

**Comment by stal111** [comment]
Fixing this would require quite a large rework of the whole Edelwood Bucket system which I don't have the time for in 1.16. The issue should be fixed in 1.18 though.
