### ISSUE TITLE
Lens of Veritatis

### ISSUE THREAD

**Issue by Maurdekye** [stal111/Forbidden-Arcanus#209]
What does it do?

There's no wiki info about it, and I couldn't find anything online elsewhere. We made one in our survival world, and it doesn't appear to have any crafting recipes or interactions with any block or item. We thought it might have some interaction with the forbiddenmicon, but it doesn't affect that either. It lacks a tooltip that might give us a hint as to its purpose, and in the modpack we're using, the advancements are custom configured and don't include ones from Forbidden & Arcanus.

**Comment by Remarnem** [comment]
This post popped up when I was searching for what the lens did and, as far as I can tell, it's used to see aureal entities. Looking at the 'forbidden_arcanus-16.2.0-beta-1.jar' on curse forge the changelog says:
> -Added Aureal Entities:
>     -every friendly entity has a 25% chance to spawn as aureal entity, normally you dont see a difference between aureal entities and normal entities
>     -when you have a Lens of Veritatis in your inventory particles will spawn near aureal entities
>     -killing an aureal entity can increase your corruption by 3 points

Link if you wanna look at the changelog more. Hopefully this helps.
https://www.curseforge.com/minecraft/mc-mods/forbidden-arcanus/files/3202968
