### ISSUE TITLE
[Possible Mod Conflict] Obsidian Shield doesn't work as described?

### ISSUE THREAD

**Issue by IdrisQe** [stal111/Forbidden-Arcanus#211]
Version 16.2.1

The Obsidian Shield states that it gives you Fire Resistance for up to 30 seconds, but in practice it gives you a 30-second Fire Resistance buff which never ticks down as long as the shield is in your inventory, meaning you take no fire damage, ever, no matter how long you spend in fire or lava.

(This is kind of broken considering the relatively low cost)

Ideally, the buff would stop getting refreshed when you're on fire, so that it then counts down from 30 seconds, only coming back once you stop being on fire.

Edit: Okay, so the Fire Resistance DOES tick down if you're in lava, but not when standing in fire for some reason. I'm beginning to think this is a mod conflict with Clear Lava View or something that makes the "burning" overlay not show maybe causing this to not detect when I'm burning unless in lava? I'll have to check more things.

**Comment by stal111** [comment]
The Obsidian Skull Shield should now work as expected in 1.18. The 1.16.5 version is out of support and thus won't receive a fix for this.
