### ISSUE TITLE
(1.16.5) Iron Chain recipe incompatibility with vanilla Minecraft chain recipe

### ISSUE THREAD

**Issue by Ch1216** [stal111/Forbidden-Arcanus#213]
..,, I don't know how it has gone unnoticed in the bug tracker that a recipe is incompatible with vanilla Minecraft, but also, whats the iron change even used for, doesn't seem to have a purpose

**Comment by stal111** [comment]
Closing this as Iron Chains will get removed in the 1.17 version of the mod as they were no longer needed since vanilla now has Chains. For the recipe confilct you could use a datapack to change it for now or a mod like Polymorph.
