### ISSUE TITLE
[16.2.2] Eternal Obsidian Skull effects persist without item?

### ISSUE THREAD

**Issue by IdrisQe** [stal111/Forbidden-Arcanus#215]
So we're playing in a modpack (Create: Above and Beyond 1.3) on a server, and noticed an interesting issue after we obtained Eternal Obsidian Skulls...

The effect doesn't actually go away when we get rid of the skulls? We put them away, and the Fire Resistance is lost... but stepping on fire or magma blocks does nothing. We visibly are set aflame, but take no damage. Doing /effect clear [name] fixes it, oddly, as if we still had Fire Resistance (but we don't)

This doesn't happen with the Obsidian Shield or the normal Skull, so it seems to be some kind of issue with the Eternal Skull itself, unless it's some kind of incompatability with another mod somehow causing it? I have no idea. This surely can't be intended right?

**Comment by stal111** [comment]
1.16.5 is no longer supported. If this issue persists in newer versions please open a new issue.
