### ISSUE TITLE
Incompatibility with Oh th Biomes you'll Go when going in the nether

### ISSUE THREAD

**Issue by craftish37** [stal111/Forbidden-Arcanus#216]
All is in the tittle : Even after disabling most of the features for this dimension in the config (both byg and f&a), the server and client is still crashing when enter in the nether, I'll suppose it's similar with the end

I am using the both last versions of theses mods :
byg-1.3.5
forbidden_arcanus-16.2.2
forge-36.2.20

Hope this will get fixed soon, I tried to find out why but still can't :/

**Comment by stal111** [comment]
Do you have the Rats mod installed? If you have that mod make sure to enable Demon Rats spawning as thats incompatible with Forbidden & Arcanus. If you don't have Rats installed I would need to see your crash log.

**Comment by craftish37** [comment]
I have rats installed, and the demon rat spawning is already turned to true
The facts are that it will be hard to find anything in the crash report, I already asked to some people from the tinker’s discord (yes…) and they just told me that it was because the tick time was done and the server just restart after that :/
Even after disabling the watchdog, the server is marked as running, but it doesn’t answer at all
I’ll post the logs & crash report in few minutes, time to switch on my computer

**Comment by craftish37** [comment]
Welp a friend that encounter the same issue way months ago told me to disable the demon rats, guess you misstyped, so np 😅
This fixed my problem, great thanks and sorry for my missunderstanding
