### ISSUE TITLE
Spectral Eye Amulet is not working v16.2.2

### ISSUE THREAD

**Issue by DexxKnight1** [stal111/Forbidden-Arcanus#217]
I was trying to use the spectral eye amulet but I don't get an outline surrounding any entities. I initially thought it wasn't working altogether, but in third person I can clearly see the effect on me. I'm not using shaders/optifine. I'm using in my modpack [Age of Fate](www.curseforge.com/minecraft/modpacks/age-of-fate/files/3566443). Thanks for any help.

**Comment by AKL55** [comment]
Same with me.playing on medieval minecraft v46 forge 1.16

**Comment by stal111** [comment]
1.16 is no longer supported. If this still happens in 1.18.2 please open a new issue.

**Comment by onesramvil-a11y** [comment]
Hey bro, could you make the amulet stop applying a glow to myself when I activate it? It's really annoying because I don't want to have to glow because of my own amulet. I don't know if there's any way to prevent this.
