### ISSUE TITLE
Black Hole Ticking Block Entity Crash

### ISSUE THREAD

**Issue by NightUndead** [stal111/Forbidden-Arcanus#218]
I thought I'd post it, just in case the reason for the crash is obvious, as I have no real information about what happens around it.
I can post a screenshot of my mob farm setup, but the crashes has happened while I was AFK.

Modpack is Valhelsia 3-3.4.6

Crash logs:
[crash-2021-12-31_14.51.17-client.txt](https://github.com/stal111/Forbidden-Arcanus/files/7796350/crash-2021-12-31_14.51.17-client.txt)
[crash-2021-12-30_20.10.01-client.txt](https://github.com/stal111/Forbidden-Arcanus/files/7796480/crash-2021-12-30_20.10.01-client.txt)

Only mob being farmed is Guardian (the occasional random mob might spawn in there as well)

Edit:
I also have Optifine installed, because I wanted those sweet sweet Shaders
Edit 2:
Dug up another crash log

**Comment by stal111** [comment]
Fixed in 16.2.3
