### ISSUE TITLE
[1.14.4] Planks do not make chests.

### ISSUE THREAD

**Issue by Boomflex** [stal111/Forbidden-Arcanus#22]
In F&A v1.14.4-1.4 the planks from the mod do not make chests.

They seem to make sticks ok and other recipes but not chests?

Using "Just Not Enough Mods" modpack v0.2.0 (https://www.curseforge.com/minecraft/modpacks/just-not-enough-mods/files/2822948)

**Comment by Vaelzan** [comment]
I think Quark is doing it in that pack, as it adds new chest types but limits normal chests to oak planks.
