### ISSUE TITLE
Crafting with edelwood creates vanilla objects

### ISSUE THREAD

**Issue by EmmaEarhart** [stal111/Forbidden-Arcanus#221]
Is this a bug or am I doing something wrong?

**Comment by stal111** [comment]
Please be a bit more descriptive. What exactly are you trying to craft? What version of the mod are you using?

**Comment by EmmaEarhart** [comment]
I am using 1.18.1, Caves and Cliffs. When crafting the edelwood ladder like JEI told me to, with edelwood planks and edelwood sticks, the crafted item box just showed a normal ladder. I had to cheat them in.

**Comment by stal111** [comment]
Fixed in 1.18.1-2.0.1. The Recipe for the ladder got changed.
