### ISSUE TITLE
No comprehensive instructions for how to perform rituals.

### ISSUE THREAD

**Issue by peanutbutterlou** [stal111/Forbidden-Arcanus#224]
I feel like I have the Hephaestus Forge multi-block setup correctly (the forge block formed) and the correct ritual items in place on arcane darkstone pedestals surrounding the forge, but right clicking on the forge with a diamond blacksmith gavel doesn't begin the ritual for the Blast Protection IV enchanted book. 

Would you be able to provide a more comprehensive walkthrough for starting an enchanted book ritual?

**Comment by stal111** [comment]
Have you added enough essenses into the forge? If that's not the problem I would need to know what version of the mod you are using.

**Comment by peanutbutterlou** [comment]
I am playing the 16.2.2 version of the mod as part of the Create: Above and Beyond pack. Here are some screenshots of my setup.

![image](https://user-images.githubusercontent.com/2053219/148704655-4d79e2d2-d0b9-4e30-b9df-dc2a643155fa.png)

![image](https://user-images.githubusercontent.com/2053219/148704738-e804c91b-df98-4af0-aed7-61743a616db3.png)

**Comment by stal111** [comment]
Are you playing on a server? In 1.16.5 it only works in singleplayer and I currently do not plan to fix it for that version as it would require some larger changes.

**Comment by peanutbutterlou** [comment]
I am in a singleplayer world. Does there appear to be anything wrong with the setup shown in the screenshots? (Also, in the screenshots, the items on the pedestals is the recipe for Blast Protection IV).

**Comment by peanutbutterlou** [comment]
So it appears it's the Blast Protection IV recipe that's messed up. I was just able to get Feather Falling IV and Protection IV rituals to work, but Blast Protection IV (as it is defined in JEI) still does not.

**Comment by Derpford** [comment]
I'm also having problems getting the Eternal Stella ritual to work. Are the rituals direction-sensitive? That is, do you have to place the items such that the top of the JEI diagram is facing north? If not, is it position-sensitive?

**Comment by Derpford** [comment]
Looking at the recipe jsons, the slots are specified. Hmmm.

**Comment by Derpford** [comment]
Turns out I missed the part about the blacksmith's gavel. Oops.

**Comment by peanutbutterlou** [comment]
It is the Blast Protection IV ritual alone that appears to not work in the 16.2.2 (1.16.5) version of the mod. Since the 1.16.5 branch is no longer being developed this issue can be closed as "will not fix".
