### ISSUE TITLE
[1.18.1] Edelwood not spawning in Dark Forest biomes / Edelwood log crafting recipe

### ISSUE THREAD

**Issue by ArchieBeepBoop** [stal111/Forbidden-Arcanus#225]
So it seems the old recipe that you could use arcane dust, an oak log and souls and to make Edelwood is missing from the 1.18.1 port.

Not only that, I went pretty far away to generate entirely new dark forests, generated some new chunks with them and the regular logs were not found anywhere. Not sure if this is an incompatibility issue with Terralith, but it doesn't seem to be the case.

Mod ver: 1.18.1 -  2.0.0

**Comment by stal111** [comment]
The recipe was removed on purpose. If you now want to get edelwood without exploring you need to use a dark soul on an oak sapling or dead bush.

Edelwood trees are now also a bit rarer than in previous versions, maybe you have just overseen them? If not it's probably a mod conflict. I would need to see if Terralith just modifies the normal biomes or adds custom ones, cause the edelwood feature only gets added to the minecraft biome.

**Comment by ArchieBeepBoop** [comment]
> The recipe was removed on purpose. If you now want to get edelwood without exploring you need to use a dark soul on an oak sapling or dead bush.
> 
> Edelwood trees are now also a bit rarer than in previous versions, maybe you have just overseen them? If not it's probably a mod conflict. I would need to see if Terralith just modifies the normal biomes or adds custom ones, cause the edelwood feature only gets added to the minecraft biome.

That's... Odd. I went through a lot of dark forest biomes looking for them and got nothing. I know terralith modifies terrain generation but not things that should spawn in biomes, also, JEI does not show a recipe to use a dark soul on a dead bush or oak sapling, so that seems to be missing like the arcane pedestal recipe.

**Comment by stal111** [comment]
It's not in JEI because it's not an actual recipe, it needs to happen in the world. I also tested the generation with a new install that only contains Forbidden & Arcanus and Terralith and they spawned just fine, although pretty rare. Are you sure that you are in the "minecraft:dark_forest" biome? Either way I will bump the generation frequency of them a bit in the next update.

**Comment by ArchieBeepBoop** [comment]
Absolutely positive. I also generated a new world and used /locatebiome to get to a dark forest, lo and behold none of them spawned. Went far away, located another one and finally, out of a huge area I saw a single trunk spawn.

![image](https://user-images.githubusercontent.com/53913550/148694319-c7712de0-6d9d-4729-b439-67244bbba1bb.png)

So apparently it's not an issue of them not spawning, it's just the spawn rate being really, really low as you said. Plus, I didn't know the dark soul on sapling thing existed until now. Perhaps a JEI addon for these small 'rituals' would help.

**Comment by stal111** [comment]
I increased the generation frequency quite a bit now in version 1.18.1-2.0.1, could you check if they now generate more often with Terralith?

**Comment by ArchieBeepBoop** [comment]
> I increased the generation frequency quite a bit now in version 1.18.1-2.0.1, could you check if they now generate more often with Terralith?

Haven't been able to check yet as I've been waiting for the mess that has been forge 39.0.45-59 to settle down as a lot of mods are conflicting due to its changes to some critical methods related to item rendering.
