### ISSUE TITLE
Slimec pickaxe won't stop giving itself silk touch.

### ISSUE THREAD

**Issue by ToonClyde** [stal111/Forbidden-Arcanus#228]
So I made myself the Slimec pickaxe but then I noticed it wouldn't stop giving itself silk touch and it kept going until it booted me off the server back to the title screen.
![image](https://user-images.githubusercontent.com/49804499/148717872-3ea8a469-2ece-475a-bc7c-4d99c4d6176e.png)
I'm on the latest released of the mod.

**Comment by ArchieBeepBoop** [comment]
1.18.1, seconding this.

**Comment by stal111** [comment]
Fixed in 1.18.1-2.0.1
