### ISSUE TITLE
Crash with "No timer found with name: forbidden_arcanus:flight_timer"

### ISSUE THREAD

**Issue by Bylack26** [stal111/Forbidden-Arcanus#230]
Hello.
I played the modpack Ragnamod VI in solo but since 2-3 days, I can launch the pack but it crashes when I play my world.
I used an old backup and it works but it is so old.
Can someone help me ?
Here's the crash report
[crash-2022-01-13_18.42.05-server.txt](https://github.com/stal111/Forbidden-Arcanus/files/7869899/crash-2022-01-13_18.42.05-server.txt)
.

**Comment by SpeedRunHunter** [comment]
Similar issue here, although I'm running a server which only creates a crash-report, but doesn't stop. When a player tries to join the server tries to load all of the player data, and throws invalid statistics and ignored advancement warnings related to Forbidden & Arcanus. Eventually though it errors out, throwing an "Internal server error" for the client, and the server side disconnecting and This happened after updating Ragnamod VI from 6.1.0 to 6.1.2 and using a world, that was generated in 6.0.27 beta. Similar issues prevented us from updating to 6.1.1, as it also had issues with Forbidden & Arcanus. The modpack in 6.1.2 is currently using F&A 1.16.4-1.0.0.

**Comment by stal111** [comment]
This issue means that your playerdata got corrupted/a timer is missing that should never be missing. Pretty sure that this issue was fixed in a newer release of f&a which you should use in any case because of all the bug fixes and new features that got added.
Closing this as I can't support a version that is older than a year.

**Comment by Ayfri** [comment]
Still having an issue with updated f&a with the modpack in 6.1.2, `Failed to synchronize registry data from server. Closing connection`.

**Comment by stal111** [comment]
Seems like the server is running a different f&a version. Make sure that both are updated.

**Comment by Ayfri** [comment]
Modpack updated to 6.1.4 fixed everything, but I still had the same versions, I don't really know what was the problem.
