### ISSUE TITLE
JEI shows modifiers as applicable even when disabled via datapack

### ISSUE THREAD

**Issue by ninyauwu** [stal111/Forbidden-Arcanus#235]
When adding items to the forbidden_arcanus:items/indestructible_blacklisted taglist, or forbidden_arcanus:items/modifier/eternal_incompatible taglist, JEI still shows the modifier recipe in the smithing table with the disabled items, despite that recipe not actually working when tried out in an actual smithing table.
JEI recipe:
![2022-01-20_23 57 02](https://user-images.githubusercontent.com/6775258/150435370-b79fdaaa-e290-4160-a27c-364b2bcac11a.png)
Actual smithing table:
![2022-01-20_23 57 14](https://user-images.githubusercontent.com/6775258/150435402-970b3bf5-dc18-406f-9a49-cbf89e966c15.png)

**Comment by stal111** [comment]
Should be fixed in 1.18.1 - 2.0.3
