### ISSUE TITLE
Soul Extractor 

### ISSUE THREAD

**Issue by Groot6969** [stal111/Forbidden-Arcanus#236]
I am trying to make the soul extractor but when I try to craft the Utrem Jar it makes a regular jar from Ice and Fire...

I've already tried the polymorph mod and nothing happens. Not sure how to get around this but im still having issues. Someone please help!

**Comment by stal111** [comment]
Please add a screenshot of the recipe your trying to use so I can make sure its the correct one.

**Comment by Groot6969** [comment]
![utrem jar](https://user-images.githubusercontent.com/97397530/150696481-88917efb-cc90-4b69-b628-6383b8957ade.png)


I am using this recipe but im using glass and 1 edelwood plank like it says but all it creates is a regular jar from ice and fire

**Comment by stal111** [comment]
Recipe conflicts can happen when using multiple mods together, nothing I can fix. You would need to adjust one of the recipes on your own or ask the ATM-Team to do it in a future pack update. Strange though that Polymorph isn't working for you.
