### ISSUE TITLE
Bug in the 1.16.5 Version

### ISSUE THREAD

**Issue by Lavelly78** [stal111/Forbidden-Arcanus#239]
Hi how are you?

i used your awesome mod in my personal mod pack, and after a few hours playing in my world i tried to make my progression in the nether. But I noticed that the chunks just didn't load, and the mobs were frozen. So I ended up researching the problems, some people said it was because of opfine, I removed it but the problem persisted...

Well then I figured I should check it out to see if any of my mods were conflicting with the Nether. after a few hours of testing I realized that unfortunately it was the mod I was most excited about, Forbidden and Arcanus. This made me very sad. I tried other versions of the old mod to see if it gave any results, but nothing! Unfortunately the FA was the problem.

Please Stal, I beg you to please take a look at this, I'm a big fan of your work, I'd like you to fix it as soon as you can.

for a better understanding here is the list of mods i used:

abnormals_core-1.16.5-3.3.0
alexsmobs-1.12.0
architectury-1.8.130-forge
ArmorPoser-1.16.5-1.0.1
ars_nouveau-1.16.5-1.24.11
Artifacts-1.16.5-2.10.4
astikorcards-1.16.5-1.1.1
Tuna-1.16.5-2.2.8
BackTools-1.16.5-10.1.0
bamboo_blocks-1.16.5-3.0.1
betterendforge-1.16.5-2.5
betternether_reforged-1.2
Better Strongholds-1.16.4-1.2.1
blue_skies-1.16.5-1.1.3
Bookshelf-Forge-1.16.5-10.3.29
buzzier_bees-1.16.5-3.0.3
caelus-forge-1.16.5-2.1.3.1
callablehorses-1.16.3-1.2.1.4
cavebiomeapi-1.16.5-1.3.7
cavesandcliffs-1.16.5-7.1.4
CavesCliffsBackportAdditions2.58
chipped-1.16.5-1.2.0.1-forge
chocolate-1.3.0-1.16.4
citadel-1.8.1-1.16.5
CosmeticArmorReworked-1.16.5-v4
create-mc1.16.5_v0.3.2d
create-stuff-additions1.16.5_v1.0.9
curios-forge-1.16.5-4.0.5.3
DoggyTalents-1.16.5-2.1.0.1
dungeons_enhanced-1.16.5-1.3
dungeons_gear-1.16.5-3.0.17
dungeons_plus-1.16.4-1.1.3
DungeonsArise-1.16.5-2.1.47-release
DynamicSurroundings-1.16.5-4.0.5.0
endergetic-1.16.4-3.0.0
EnigmaticGraves-1.6.3
environmental-1.16.5-1.1.1
expandability-2.0.1-forge
FarmersDelight-1.16.5-0.5.0
flywheel-1.16-0.2.4
forbidden_arcanus-16.2.0-beta-4 AND LAST VERSION
FpsReducer-forge-1.24-mc1.16.5
geckolib-forge-1.16.5-3.0.46
goblintraders-1.6.0-1.16.3
guardvillagers-1.16.5.1.2.6
horse_colors-1.16.5-1.6.1.1
horsesstatsmod-MC1.16.x-1.4.1
Hwyla-forge-1.10.11-B78_1.16.2
iceandfire-2.1.9-1.16.5
iChunUtil-1.16.5-10.5.1
je-1.16.5-7.7.1.121
journeymap-1.16.5-5.7.1
Kobolds-1.5.1.2
kotlinforge-1.15.1-obf
LibraryFerret-Forge-1.16.5-1.0.1
magnesium-1.5
Mantle-1.16.5-1.6.127
minecolonies-1.16.5-1.0.309-RELEASE
MmmMmmMmmMmm-1.16.5-1.3.1
moarmorstands-1.0-1.16.5
mostructures-forge-1.2.0-1.16.5
mowziesmobs-1.5.18
nether-s-exoticism-1.16.5-1.1.3
observerlib-1.16.5-1.5.3
outvoted-1.16.5-1.2.4
Paraglider-1.16.5-1.3.2.5
parrying-2.2.2
Patchouli-1.16.4-53.2
personality-1.16.5-1.0.3
Prehistoric_Fauna_2.1.2
ratlantis-1.0.0-1.16.3
rats-7.2.0-1.16.5
savageandravage-1.16.5-3.2.0
selene-1.16.5-1.9.0
Shrines-1.16.5-1.8.1]sit-1.16.2-v1.3
sit-1.16.2-v1.3
SkyVillage_1.0.0_1.16.5
slimy-stuff-1.16.5-1.0.5
smallships-1.16.5-1.8.1
sons-of-sins-1.16.5-1.0.8
SpawnInVillage-1.16.4-1.3
stalwart-dungeons-1.16.5-1.1.7
structure_gel-1.16.5-1.7.7
structurize-0.13.252-ALPHA-universal
supplementaries-1.16.5-0.18.0
twilightforest-1.16.5-4.0.546-universal
UnionLib-1.16.5-3.2.4
upgrade_aquatic-1.16.5-3.1.2
useless-sword-1.16.5-V1.3.6
valhelsia_core-16.0.10
valhelsia_structures-1.16.5-0.1.5
VillagersAndMonstersLegacy3,5Bugfix
wandering-bag-1.16.5-1.0.3
WAWLA-1.16.5-8.0.1
Waystones_1.16.5-7.6.4
wings-2.0.1-1.16.5
YungsApi-1.16.4-Forge-12

Hope I have some help with this list, thanks anyway, I just want you to know that I love your work.

Ty

**Comment by stal111** [comment]
Make sure to disable the spawning of Demon Rats. It's something the Rats mod would need to fix on their end.

**Comment by Lavelly78** [comment]
> 

Ok, i'm try.

**Comment by Lavelly78** [comment]
> Certifique-se de desativar a geração de Demon Rats. É algo que o mod Rats precisaria consertar.

Oh, thanks for the reply and conclusion of my problem.

You are the best, I had never thought of that, what the rats mod that was causing problems. I will report this on rats github as well.

anyway thanks for everything, i love your work! :)
