### ISSUE TITLE
Conflicting recipe

### ISSUE THREAD

**Issue by LemADEC** [stal111/Forbidden-Arcanus#24]
**Describe the bug**
Soul is made from smelting soulsand, this is conflicting with Soul Shard Respawn which makes Vile dust the same way.

**To Reproduce**
1. Check SSR recipes

**Expected behavior**
Propose an alternate recipe or ingredient to avoid such conflict.

**Version(please complete the following information):**
 - Forbidden & Arcanus: 1.12.2-1.1.4
 - Forge: 14.23.5.2847
- SoulShardRespawn: 1.12.2-1.1.1-13

**Comment by stal111** [comment]
1.12.2 is no longer supported, please update to a newer Version.
