### ISSUE TITLE
Wiki Not updated

### ISSUE THREAD

**Issue by alexrsosa97** [stal111/Forbidden-Arcanus#240]

**Comment by stal111** [comment]
What exactly did you find that isn't updated? Everything seems up to date to me.

**Comment by alexrsosa97** [comment]
thanks for the response. for one example the mob page is empty, and i went to see what the zombie arm does and theres no info for it. there are a few other things i went to look into on the wiki page and didnt see them there. also the link to the wiki goes to the outdated one instead of the new valhelsia one.  from what i see it is listed on the changelog though
