### ISSUE TITLE
Server crash with Macaw's Trapdoors

### ISSUE THREAD

**Issue by evhub** [stal111/Forbidden-Arcanus#242]
**Describe the bug**

The server crashes occasionally when initializing with Forbidden Arcanus and Macaw's Trapdoors. I don't know exactly what's happening, but it looks to me like some sort of race condition due to non-threadsafe access.

**Crash report**

https://gist.github.com/evhub/ef44f19ec90e0cafeaf2781a63d5ac5d

**Versions**
 - Forbidden & Arcanus: 2.0.3
 - Valhelsia Core: 0.3.2
 - Forge: 39.0.75
 - Minecraft: 1.18.1

**Comment by stal111** [comment]
Is this still an issue?
