### ISSUE TITLE
TConstruct & Eternal Stella

### ISSUE THREAD

**Issue by Raawkun** [stal111/Forbidden-Arcanus#243]
**Describe the bug**
Added the Eternal Stella to my TConstruct Cobalt Pickaxe (full durability at this point) via the Smithing Table - Pickaxe is loosing durability when mining blocks with it.

**Expected behavior**
It... not to lose durability?

**Versions**
 - Forbidden & Arcanus: 2.0.3
 - Valhelsia Core: 0.3.2
 - Forge: 39.1.2
 - TConstruct: 3.4.1.46

**Additional context**
Maybe I'm doing anything wrong? Idk

**Comment by stal111** [comment]
This is cause TConstruct handles the durability somehow different than vanilla. Nothing we can do about it in f&a.

**Comment by DefinitelyAlec** [comment]
Are you not able to give the item the NBT tag "Unbreakable" when combining an item with the eternal stella? That feels like it would be a more universal solution for mods that override the vanilla durability mechanics.
