### ISSUE TITLE
1.18.1 obsidian skull failed to give the effects to the player 

### ISSUE THREAD

**Issue by LeviathanEcho** [stal111/Forbidden-Arcanus#244]
game version:1.18.1
mod version: 2.0.3
Describe the bug: obsidian skull , eternal obsidian skull and obsidian skull shield can't give the effects to the player

**Comment by stal111** [comment]
Have you actually tried if they protect you from fire damage? In 1.18 they no longer give the Fire Resistance effect and instead use a custom system.

**Comment by LeviathanEcho** [comment]
eternal obsidian skull will protect me from fire damage while still have the sound and screen shake.
obsidian skull and obsidian skull shield can't protect me from fire whether it's in the armor bar or in the backpack.

**Comment by stal111** [comment]
Hard to tell why it isn't working. Could you maybe try with just f&a installed to make sure it isn't caused by another mod?

**Comment by LeviathanEcho** [comment]
I tried with just f&a  and Valhelsia Core installed. 
The obsidian skull and the shield won't work if I put it in the armor slots or in the off-hand slot. It looks like that the Fire Resistance effect won't work if these items are not put in the storage slots or hotbar slots.

**Comment by stal111** [comment]
Could you update to 1.18.2? Pretty sure it was fixed in that version.

**Comment by LeviathanEcho** [comment]
You're right. 1.18.2 version doesn't have this bug. Thank you.
