### ISSUE TITLE
Combing Eternal Stella with Enchanted Items [1.16.5]

### ISSUE THREAD

**Issue by CFlatFlat** [stal111/Forbidden-Arcanus#249]
Only being able to add the Eternal Stella to unenchanted items is very annoying. By the time you'll be making any, your items are going to be well-enchanted. Your only option to have both is to apply the eternal stella first and then use (multiple) enchanted books. This is already annoying by default, but also prevents using it alongside some modded forms of enchanting, such as the ones added by Enchanting Infuser and Astral Sorcery.

I think the best solution is to make the eternal stella compatible with items that are already enchanted, in addition to not being considered an enchantment itself (if possible) This way, you could enchant an item by whatever means you'd like and then make it indestructible, or vice versa. Way more convenient, and not any less balanced.

I also thought of being able to apply the eternal stella to enchanted books, and then using those to apply it to indestructable items. It would be closer to how the item is currently implemented, just adding some extra flexibility with how you apply your enchantments.

I am currently running Astral Sorcery and am approaching the point of using the Stellar Refraction Table to enchant items. However, the way the Eternal Stella is currently implemented arbitrarily prevents using the two together.

**Comment by CFlatFlat** [comment]
I've found a temporary solution by using a disenchanter mod to put it on a book, but I'd still like to see this functionality implemented.

**Comment by stal111** [comment]
In my testing it definitely worked on already enchanted items, so I guess it's some sort of mod conflict. Furthermore, Indestructible has already been changed to an item modifier in 1.18 and is no longer an enchantment. However, this change won't be backported as 1.16.5 is out of support.
