### ISSUE TITLE
Runic Stone nearly unfindable

### ISSUE THREAD

**Issue by FreddysChild** [stal111/Forbidden-Arcanus#250]
**Describe the bug**
Not sure if it is a bug or a just me problem, but for the live of god I cannot find any runic stone. D:
I am playing on a server so I thought maybe I am just unlucky so I switched to a new single player created world and changed some of the config but after 30 Minutes of destroying mines I finally found ONE single runic stone.

**To Reproduce**
2. Use '...' on '....'
3. See error

**Screenshot**
![Screenshot_1386](https://user-images.githubusercontent.com/104069915/164213889-c56fdfe6-4475-4259-ae6d-a226b6898029.png)
Configuration
![Screenshot_1387](https://user-images.githubusercontent.com/104069915/164215039-0888a801-c26a-4b5f-a405-6356cd9501be.png)
The only one I could find in single player mode - it was only one without more connecting :<

**Expected behavior**
I didn't expect it to be so rare since it is used in a few recipes. 

**Versions**
 - Forbidden & Arcanus: 1.18.2 - 2.0.0
 - Valhelsia Core:
 - Forge: 1.18.2
 - I am using ATM 7 0.3.12

**Comment by stal111** [comment]
I slightly bumped their generation chance in version 2.1.0-beta1. If you feel like it's still to low feel free to open a new issue or ask me in the f&a discord.
