### ISSUE TITLE
1.18.2: Test Tube in offhand does not collect blood

### ISSUE THREAD

**Issue by Derpford** [stal111/Forbidden-Arcanus#251]
**Describe the bug**
When held in the offhand, the Test Tube does not collect blood via the Mystical Dagger.

**To Reproduce**
1. Hold the test tube in your offhand slot.
2. Kill a mob with the Mystical Dagger.
3. Blood does not fill the tube.

**Expected behavior**
The Test Tube should recover blood from kills with the Mystical Dagger, even when in the offhand slot.

**Screenshots**

**Versions**
 - Forbidden & Arcanus: 2.0.0
 - Valhelsia Core: 0.3.0
 - Forge: 40.1.0

**Comment by stal111** [comment]
Fixed in version 2.1.0-beta1. Thanks for reporting :)
