### ISSUE TITLE
Minecraft Failed to start

### ISSUE THREAD

**Issue by GruiaYT** [stal111/Forbidden-Arcanus#253]
Minecraft Failed to start!
An error during the startup prevented Minecraft from starting.
The following mod(s) have been identified as pottential causes:Forbidden and Arcanus

**Screenshots**
![image](https://user-images.githubusercontent.com/68369902/166001198-b422c657-7b43-45b8-b983-0d4d2a49d6df.png)

**Versions**
 - Forbidden & Arcanus:
 - Valhelsia Core:no
 - Forge:14.23.5.2860

**Comment by stal111** [comment]
Update to a newer version. Forge 14.x.x should be Minecraft 1.12.2 or something like that which has been unsupported for quite a few years now.

**Comment by UnknownForTheForce** [comment]
![image](https://user-images.githubusercontent.com/109116067/178378842-bef65a35-2f1d-47ba-9c26-c2be7b22c33b.png)
This is my problem...
