### ISSUE TITLE
Items get voided when inputting into the Hephaestus Forge

### ISSUE THREAD

**Issue by Swedz** [stal111/Forbidden-Arcanus#255]
**Describe the bug**
When items are inserted via hopper or other item routing methods, they first insert into the unused slot, and beyond that, the inserted items are voided.

**To Reproduce**
1. Construct a Hephaestus Forge
2. Place a hopper on top of or the side of the forge, facing into the forge
3. Put an item into the hopper
4. Put a different item into the hopper
5. The second item will be voided

**Expected behavior**
The second item would either not be inserted at all, or be inserted into the center slot. I did expect the item to go into the center slot originally, which is why I tried putting in a different item to see if it would work that way.

**Versions**
 - Forbidden & Arcanus: 2.0.0
 - Valhelsia Core: 0.3.1
 - Forge: 40.1.20

**Additional info**
I think having items first insert into the center slot and then the secondary slots would be more intuitive. Additionally, being able to insert souls, blood vials (and extract, so that it can be refilled later), and xpetrified orbs into their respective slots would be incredible. Generally, just being able to automate the forge would be preferred.

**Comment by stal111** [comment]
This has been fixed in version 1.19.3-2.2.0-beta1.
