### ISSUE TITLE
No default tool for Tiled Polished Darkstone Bricks

### ISSUE THREAD

**Issue by SerranoPancake** [stal111/Forbidden-Arcanus#257]
**Describe the bug**
When trying to mine Tiled Polished Darkstone Bricks, there is not tool defined to break block resulting in block not dropping.

**To Reproduce**
1. Create block
2. Place block in world
3. Try to break block

**Expected behavior**
Pickaxe should be default tool and block should drop itself when mined

**Screenshots**

**Versions**
 - Forbidden & Arcanus:2.1.0-beta1
 - Valhelsia Core: 0.3.1
 - Forge: 40.1.19

**Additional context**

**Comment by stal111** [comment]
Fixed in 1.18.2-2.1.0-beta2.
