### ISSUE TITLE
Wood stairs has wrong recipe

### ISSUE THREAD

**Issue by Sunekaer** [stal111/Forbidden-Arcanus#258]
All wooden stairs have the same recipe as slabs.

https://cdn.floatingmonkey.dev/screenshots/2022/06/06/1654512733_javaw.png
https://cdn.floatingmonkey.dev/screenshots/2022/06/06/1654512770_javaw.png
https://cdn.floatingmonkey.dev/screenshots/2022/06/06/1654512774_javaw.png
https://cdn.floatingmonkey.dev/screenshots/2022/06/06/1654512778_javaw.png

**Comment by stal111** [comment]
Fixed in 1.18.2-2.1.0-beta2.
