### ISSUE TITLE
Please set modloader on curseforge.com

### ISSUE THREAD

**Issue by pavog** [stal111/Forbidden-Arcanus#259]
On curseforge.com you can set supported modloaders for your releases.
When I go to https://www.curseforge.com/minecraft/mc-mods/forbidden-arcanus/files/all I can see only the game version, but I'd like to filter for forge / fabric, too.
So that I know that it's for forge.

See like this example:
https://www.curseforge.com/minecraft/mc-mods/absent-by-design/files/all?filter-game-version=2020709689%3A7498

**Comment by stal111** [comment]
The latest uploaded files for 1.16.5 and 1.18.2 have now been tagged as forge.
