### ISSUE TITLE
[1.14.4] Override of loot table of Enigmatic Legacy

### ISSUE THREAD

**Issue by Thanjar** [stal111/Forbidden-Arcanus#26]
#### Versions:
 * Enigmatic Legacy: 1.6.2
 * Curios API: 1.0.5.3
 * Forge: 28.1.106
 * Forbidden & Arcanus: 1.4
#### Description:
Forbidden & Arcanus overrides loot table from Enigmatic Legacy on End City chests.
#### Expected behavior:
Loot from Enigmatic Legacy and Forbidden & Arcanus spawning in End City chests.
#### How to Reproduce:
1. Install the respective version mods.
2. In the creative inventory search for "The One Box" (Looks like an item version of an ender chest) and right-click until the item indicate the loot table from the end city chests in the item description.
3. with "The One Box", shift-right-click the bottom of any chest. this will initiate a test of loot found in a total of 32000~ instances.
4. Check the end of the file: "Latest.log", there is a list of the items spawned.
5. And, as you can see, no loot (Like: Mending Mixture, Etherium Ore, etc.) from Enigmatic Legacy.
#### Logs:
https://hastebin.com/valenecoti.sql
#### Note:
there is some stuff from Corail Tombstone, but is just the warning of minecraft that didn't detected the mod, because i thought that may had caused the issue, but no issue happened with it.

**Comment by stal111** [comment]
Fixed in 1.14.4-1.5
