### ISSUE TITLE
Combatibility with all the ores 

### ISSUE THREAD

**Issue by Kurinchi01** [stal111/Forbidden-Arcanus#260]
**Describe the bug**
All Ore Hammers i have tried arent "Eternal" as they should be. They are craftable but when used they disapear.
**To Reproduce**
Craft Ore Dust with  e.g. Eternal Copper Ore Hammer
Hammer disapears.

**Versions**
 - Forbidden & Arcanus: 1.18.2-2.1.0-beta1
 - Valhelsia Core: 1.18.2-0.3.1
 - Forge: 40.1.31

**Additional context**
Okay, after some testing, shift right click, to craft all the ores doesnt work. but makins one by one is fine, hammer doesnt lose durability. so the question is, ist this comming from forbidden arcanus or from all the ore...

**Comment by stal111** [comment]
I'd like to investigate this, but unfortunately All the Ores source code is private so I can't find the cause.
