### ISSUE TITLE
[Bug] Smelter Prism on Pickaxe voids Ender-Tank

### ISSUE THREAD

**Issue by TheonlyTazz** [stal111/Forbidden-Arcanus#266]
**Describe the bug**
Mine Ender-Tank with a Fiery Pickaxe (tested with Diamond and Netherite-Diamond)
upon breaking, the Ender-Tank gets voided

**To Reproduce**
1. Create a Pickaxe
2. Apply Smelter Prism
3. Mine Ender-Tank
4. No Ender-Tank is dropped

**Expected behavior**
Ender-Tank should be dropping as item

**Screenshots**

**Versions**
 - Forbidden & Arcanus: 1.18.2-2.1.0
 - Valhelsia Core: 1.18.2-0.3.1
 - Forge:40.1.47

**Additional context**
This Issue got originally submitted to the FTB-Modpack Issue tracker, forwarding this, because its a Mod issue
https://github.com/FTBTeam/FTB-Modpack-Issues/issues/997

**Comment by TheonlyTazz** [comment]
Are we getting an update on this issue? is it getting resolved?

**Comment by stal111** [comment]
As said in Discord, please open an issue on the bug tracker of the Ender Tanks mod as I won't be able to look into this due to them keeping the source code private.
