### ISSUE TITLE
[Bug] Hephaestus Forge pedestal items can be reclaimed and still give the initial ritual output

### ISSUE THREAD

**Issue by NyvexOfShadows** [stal111/Forbidden-Arcanus#267]
**Describe the bug**
After starting a ritual, the player can remove items used in the ritual from the pedestals. After the ritual completes, the initial output of the ritual will still be generated.

**To Reproduce**

1. Set up the Hephaestus Forge.
2. Supply the required essences (aureal, souls, blood, experience) to the forge.
3. Add the recipe items to the Hephaestus Forge and its Darkstone Pedestals.
4. Initiate the ritual with any Blacksmith Gavel.
5. Remove items from the Darkstone Pedestals.
6. Wait for the ritual to complete.
7. Encounter the item output of the initiated ritual.

**Expected behavior**
I expected the ritual to stop completely or not produce any results.

**Screenshots**
![2022-06-23_14 39 54](https://user-images.githubusercontent.com/58571419/175373488-ef29b906-b864-4f37-9acb-6c7bc37b7423.png)
![2022-06-23_14 40 42](https://user-images.githubusercontent.com/58571419/175373495-f2d51833-25ed-4bb4-9e28-185a1177d02c.png)

**Versions**
 - Forbidden & Arcanus: 1.18.2-2.0.0
 - Valhelsia Core: 1.18.2-0.3.1
 - Forge: 40.1.30

**Additional context**
This was done in a client with multiple other mods, as well as some custom datapacked recipes for use with the forge. Bug is reproducible in these cases, as well as without any other mods than F&A and Valhelsia Core

**Comment by stal111** [comment]
This has been fixed in version 1.19.3-2.2.0-beta1.

**Comment by Selsus74** [comment]
Are you planning on back porting these progression breaking bugs?
I really like ur mod. It has a nice vibe and i like the items and mechanics
there are not so many cool magic mod concepts for 1.19.2
Astral and Blood Magic not being ported and so on
This bug and the fact that there is no in game documentation will very likely have the consequence of your mod not being used in our mod pack ( we arr currently developing a hard survival tech pack)
Therefore my question. It would be awsome if you would atleast back port bugs like these( content is not that important)

**Comment by stal111** [comment]
> Are you planning on back porting these progression breaking bugs? I really like ur mod. It has a nice vibe and i like the items and mechanics there are not so many cool magic mod concepts for 1.19.2 Astral and Blood Magic not being ported and so on This bug and the fact that there is no in game documentation will very likely have the consequence of your mod not being used in our mod pack ( we arr currently developing a hard survival tech pack) Therefore my question. It would be awsome if you would atleast back port bugs like these( content is not that important)

Unfortunately I don't have the time to support multiple versions. I know it would be good to backport these important bug fixes but in 1.20 we completely rewrote the Hephaestus Forge internals for this and it required lots of testing. If someone wants to do the work feel free to do it and I'll happily upload it.
