### ISSUE TITLE
couldn't load tag [arcane_gold_block]

### ISSUE THREAD

**Issue by tetriminoss** [stal111/Forbidden-Arcanus#268]
I'm getting a red error on my server,

Please see the logs below:

https://pastebin.com/29hNyCJU

will list mod list on request,

will give more info on request,

Thank you!

**Comment by MrRobotjs** [comment]
Same issue here.
https://mclo.gs/VReGThC

**Comment by fgthfrt** [comment]
I had the same issue but after i installed a mod called valhelsia it worked maybe that solves your problem

**Comment by tetriminoss** [comment]
Valhelsia core? If so I would say most of the guys who uses forbidden
arcanus has it considering it's a requirement.

I have it too on my server, though the version of it is the same as when I
had posted this thread.

**Comment by MrRisbert** [comment]
> I had the same issue but after i installed a mod called valhelsia it worked maybe that solves your problem

[Crash Loggs](https://mclo.gs/Rl4QCJU)

Have the same problem, But I also have Valhelsia core included, and I still crash. Not sure how to fix it. There's also an error code about the recipe for forbidden_arcanus:arcane_golden_axe. Not sure what it means. I'm guessing all arcane gold related items are bugged, could be wrong.

**Comment by stal111** [comment]
Fixed in forbidden_arcanus-1.19.2-2.1.0-beta2
