### ISSUE TITLE
Error when joining server running 1.19 Forge

### ISSUE THREAD

**Issue by LetheGamin** [stal111/Forbidden-Arcanus#269]
I'm trying to connect to my server when I run the mod, but I cant connect and instead get the error

 'Internal Exception: io.netty.handler.codec.DecoderException:java.lang.IllagalArgumentExecption: Unknown recipe serializer forbidden_arcanus:apply_modifier'

**Comment by stal111** [comment]
Which Forge version is your client and the server running?
