### ISSUE TITLE
Yellow Orchid configuredfeature not registering

### ISSUE THREAD

**Issue by Frzncore** [stal111/Forbidden-Arcanus#270]
****************** Blame Report Unregistered Worldgen 1.16.5-3.7.0-forge ******************

 These ConfiguredFeature was found to be not registered. Look at the JSON info and try to
 find which mod it belongs to. Then go tell that mod owner to register their ConfiguredFeature
 as otherwise, it will break other mods or datapacks that registered their stuff.

 Unregistered ConfiguredFeature JSON info : {
  "config": {
    "feature": {
      "config": {
        "feature": {
          "config": {
            "feature": {
              "config": {
                "feature": {
                  "config": {
                    "can_replace": false,
                    "project": true,
                    "need_water": false,
                    "xspread": 7,
                    "yspread": 3,
                    "zspread": 7,
                    "whitelist": [],
                    "blacklist": [],
                    "tries": 10,
                    "state_provider": {
                      "state": {
                        "Name": "forbidden_arcanus:yellow_orchid"
                      },
                      "type": "minecraft:simple_state_provider"
                    },
                    "block_placer": {
                      "type": "minecraft:simple_block_placer"
                    }
                  },
                  "type": "minecraft:flower"
                },
                "decorator": {
                  "config": {},
                  "type": "minecraft:spread_32_above"
                }
              },
              "type": "minecraft:decorated"
            },
            "decorator": {
              "config": {
                "outer": {
                  "config": {},
                  "type": "minecraft:square"
                },
                "inner": {
                  "config": {},
                  "type": "minecraft:heightmap"
                }
              },
              "type": "minecraft:decorated"
            }
          },
          "type": "minecraft:decorated"
        },
        "decorator": {
          "config": {
            "count": 14
          },
          "type": "minecraft:count"
        }
      },
      "type": "minecraft:decorated"
    },
    "decorator": {
      "config": {
        "whitelist": [],
        "blacklist": [
          "minecraft:the_end"
        ]
      },
      "type": "forbidden_arcanus:dimension_placement"
    }
  },
  "type": "minecraft:decorated"
}

 Biome affected : [minecraft:flower_forest]

**Comment by stal111** [comment]
1.16.5 is no longer supported. If this is still an issue in newer versions please open a new issue.
