### ISSUE TITLE
Server crashes when players are nearby carved edelwood log

### ISSUE THREAD

**Issue by Hearlex** [stal111/Forbidden-Arcanus#273]
**Describe the bug**
The server crashes sometimes when using Frobidden Arcanus. After restarting the server it works again until a few minutes after which the crash happens again.

**Versions**
 - Forbidden & Arcanus: 2.0.0
 - Valhelsia Core: 0.4.0
 - Forge: 40.1.68
 - Minecraft: 1.18.2

**Crash report**
https://gist.github.com/Hearlex/4225f17427a1299c227af17348d7f196

**Comment by stal111** [comment]
Fixed in 1.18.2-2.1.0-beta3
