### ISSUE TITLE
Items re-appearing and Disappearing on pedestals after chunks unloaded

### ISSUE THREAD

**Issue by Mini-Madmiddle** [stal111/Forbidden-Arcanus#274]
**Describe the bug**
From what I can tell, whenever an item is placed in a pedestal, the block data for the pedestal wont save properly, or something along those lines, resulting in either loss of items, or duplicate items being produced. 

I'm not entirely clear on how the bug is caused, if it is the pedestals entirely, and how to reproduce reliably, So I apologize. Your best bet is to do a ritual or 2, then leave the chunk for a bit.

**Versions**
-  Forbidden & Arcanus: 2.0.0
-  Forge: 40.1.25
-  Minecraft: 1.18.2
(Unsure What else might be needed)

**Comment by stal111** [comment]
This has been fixed in version 1.19.3-2.2.0-beta1.
