### ISSUE TITLE
Nipa structures generate even when disabled in config [1.18.2-2.0.0]

### ISSUE THREAD

**Issue by kalisture** [stal111/Forbidden-Arcanus#275]
**Describe the bug**
Even when blacklisted for minecraft:overworld And 
[world_gen.nipa]
		#Generate Nipas? [default: true]
		generate = false
generate is set to false

Nipa structures still generate. New game restart, new world.

**To Reproduce**
1. Go to config/forbidden_arcanus-common.toml
2. set world_gen.nipa - generate = false
3. start game, generate new world, observe nipa structures

**Expected behavior**
Nipa structures should not be generated if set to false

**Versions**
 - Forbidden & Arcanus: 1.18.2-2.0.0
 - Valhelsia Core: 1.18.2-0.4.0
 - Forge: 40.1.68

**Additional context**
Blacklisting/disabling generation of other features such as ores seems to work just fine

**Comment by stal111** [comment]
This config option is an remnant from the old system. In 1.18.2 you need to use biome tags to configure which biomes should generate structures. 

Tags for Nipas are:
worldgen/biome/has_structure/nipa.json
worldgen/biome/has_structure/nipa_always_floating.json
