### ISSUE TITLE
[1.16.5] Mod conflict: Respawn fails when there's another mod that checks for a respawn clone event.

### ISSUE THREAD

**Issue by Akrae42** [stal111/Forbidden-Arcanus#276]
**Describe the bug**
As title, attempting to respawn does nothing when there's another mod listening for respawns. In this case, Dragon Survival.

**To Reproduce**
1. Die.
2. Click Respawn.
3. Nothing happens.

**Expected behavior**
Being able to respawn.

**Screenshots**
Not a screenshot, but a pastebin of the java error: https://pastebin.com/PjbxJWuw

**Versions**
 - Forbidden & Arcanus: 16.2.3
 - Valhelsia Core: 16.0.15
 - Forge: 36.2.34
 - Dragon Survival: 0.10.6

**Additional context**
Also tested in Forge 36.2.39 with no change in behavior.
Problem does not persist in the 1.18.2 versions of these mods.
Problem also existed with a previous version of Pixelmon(9.0.0), but does not in the current version.
Also, be wary of testing this in any mainline Valhelsia pack as there's an additional conflict between Valhelsia Tweaks and Dragon Survival, causing much of the dragon UI to cause a clientside crash.
A user on the Dragon Survival discord had this to say: "The clone progress of dragon survival invalidate the capabilities of player entity. Caused other mod's clone handler after dragon survival unable to fetch their Capability then crash,unable to complete the respawning."
I am also submitting a bug report on the Dragon Survival side.

**Comment by stal111** [comment]
Thanks for reporting the issue, however, 1.16.5 is no longer supported and won't receive any future updates.
