### ISSUE TITLE
[1.18.2] Tiled Polished Darkstone Bricks don't break

### ISSUE THREAD

**Issue by INooBTooMuch** [stal111/Forbidden-Arcanus#278]
**Describe the bug**
Tiled Polished Darkstone Bricks say they require no tool to break and take too much time (19-20 sec) to break (eff 7 emerald pickaxe) and when it breaks it doesn't drop.

**Expected behavior**
Display in "The One Probe" it requires a pickaxe (this might be a TOP problem, don't really know) and drop the item

**Screenshots**
![2022-07-27_13 36 34](https://user-images.githubusercontent.com/107572028/181227077-df35012e-307d-45b4-ba15-55e0c0327d9b.png)

**Versions**
 - Forbidden & Arcanus: 1.18.2-2.0.0
 - Valhelsia Core: 1.18.2-0.4.0
 - Forge: 40.1.68

**Additional context**
This might be the case with other blocks from this mod.

**Comment by stal111** [comment]
Thanks for reporting. However, this issue has already been fixed in the newest beta for 1.18.2.
