### ISSUE TITLE
[1.18.2] Config for spawning trees

### ISSUE THREAD

**Issue by Reshy** [stal111/Forbidden-Arcanus#280]
**Is your feature request related to a problem? Please describe.**
When using a modded list of biomes, it can become nearly impossible to find things like Edel Trees as they don't spawn in any similar biomes, and there is no config to add them manually.

**Describe the solution you'd like**
A config that allows you to add to an array a list of valid biomes for thing like the Edel Tree, Mystery Tree, Cherry Tree, etc.

**Comment by stal111** [comment]
The 1.18.2 version has reached its end of support and won't be updated any longer. I'd suggest updating to 1.19.2 as all features including the trees can now be configured using normal vanilla datapacks.

**Comment by Reshy** [comment]
Sadly the mod that I really want to use isn't being supported on newer versions due to the developer departing.
