### ISSUE TITLE
Game crashes at the when loading mod java.lang.NoSuchFieldError: LOOT_MODIFIER_SERIALIZERS 1.19

### ISSUE THREAD

**Issue by Mikeson21529** [stal111/Forbidden-Arcanus#282]
Every time i load the game there's an error while loading the mods, with valhelsia core and forbidden & arcanus  java.lang.NoSuchFieldError: LOOT_MODIFIER_SERIALIZERS

here's the crash report.
[crash-2022-08-02_08.31.10-fml.txt](https://github.com/stal111/Forbidden-Arcanus/files/9242713/crash-2022-08-02_08.31.10-fml.txt)

**Comment by MercuryMaiden** [comment]
I am also having this issue... I ponder if a mod is conflicting with it... Have you tried isolating the mod to see if it starts up? By itself?

**Comment by stal111** [comment]
Forbidden & Arcanus for 1.19 requires Forge version 41.0.33. Newer versions won't work due to a few breaking changes in Forge.
