### ISSUE TITLE
Game Crashes when loading Valhesia Core:

### ISSUE THREAD

**Issue by Guslloween** [stal111/Forbidden-Arcanus#283]
I updated both forbidden and Valhelsia Core and minecraft started crashing out of nowhere every time I tried to load Valhelsia Core.

Tried am both java versions: 17 and 18, I'm submitting java version 17.

[crash-2022-08-02_12.29.24-client.txt](https://github.com/stal111/Forbidden-Arcanus/files/9253378/crash-2022-08-02_12.29.24-client.txt)

**Comment by stal111** [comment]
Uhm I guess you attached the wrong file? At least this one isn't very helpful with finding the crash cause lol

**Comment by Guslloween** [comment]
OPS!
[crash-2022-08-03_12.58.58-client.txt](https://github.com/stal111/Forbidden-Arcanus/files/9253215/crash-2022-08-03_12.58.58-client.txt)

**Comment by stal111** [comment]
This issue is caused by an incompatibility between Valhelsia Core & Optifine. 
Only way to solve this will be to remove Optifine.

**Comment by Guslloween** [comment]
Thanks
