### ISSUE TITLE
forbidden_arcanus-1.18.2-2.1.0-beta3.jar Another Quality Modpack 3

### ISSUE THREAD

**Issue by glucho** [stal111/Forbidden-Arcanus#284]
When setting up the alter to make anything such as Eternal Stella or anything that requires the alter, does not work. Nothing happens. 

**To Reproduce**
Set up alter, place the ingredients for Eternal Stella
Use the Blacksmiths Gavel and right click 

**Expected behavior**
Animation plays and Eternal Stella or  any item need the ritual, is created  

**Screenshots**

**Versions**
 - Forbidden & Arcanus: forbidden_arcanus-1.18.2-2.1.0-beta3
 - Valhelsia Core: valhelsia_core-forge-1.18.2-0.4.0.jar

 - Forge:  40.1.55 

**Additional context**
Using: Another Quality Modpack 3
this bug also occurred on All the Mods 7 ver. 0.4.22

**Comment by stal111** [comment]
Are you using the Radium Reforged mod? It's known to break the Hephaestus Forge.
