### ISSUE TITLE
Game Crashes when loading Valhesia Core

### ISSUE THREAD

**Issue by Guslloween** [stal111/Forbidden-Arcanus#285]
I updated both forbidden and Valhelsia Core and minecraft started crashing out of nowhere every time I tried to load Valhelsia Core.

Tried am both java versions: 17 and 18, I'm submitting java version 17

[crash-2022-08-03_12.58.58-client.txt](https://github.com/stal111/Forbidden-Arcanus/files/9259298/crash-2022-08-03_12.58.58-client.txt)
.

**Comment by stal111** [comment]
Why did you open another issue with the same contents?

**Comment by Guslloween** [comment]
I put the wrong file and the duplicated the issue for accident, the changes didn't save (internet problems). I opened a new one to make sure the issue file was sent.

Sorry by problems
