### ISSUE TITLE
Item Duplication

### ISSUE THREAD

**Issue by PyroBurnem** [stal111/Forbidden-Arcanus#286]
**Describe the bug**
While messing about in my server, one of my players found that the Mystical Dagger was duplicated while trying to repair it using a Mending Mixture from Enigmatic Legacy. Further testing within my personal singleplayer testing world resulted in the following video.

**To Reproduce**
https://cdn.discordapp.com/attachments/889158030644621342/1007122530605223986/idontthinkthatissupposedtohappen.mp4
(Apparently the file is too big for github so a discord link will have to do.)
Attempting to craft 2 Mystical Daggers together results in the output similar to vanilla MC's tool repair via crafting, however when actually crafted will leave the two daggers used in the craft behind. This bug may possibly be derived from the Dragon Head to Dragon Scales craft, as each dagger loses 10 durability each upon every craft, resulting in the extremely negative damage values nearer to the end of the video.

**Expected behavior**
For the daggers to not duplicate.

**Versions**
 - Forbidden & Arcanus: 1.18.2-2.1.0-beta3
 - Valhelsia Core: 1.18.2-0.4.0
 - Forge: 40.1.68

**Comment by XionioXMaster** [comment]
how to fix this dupe?

**Comment by DonorKrovi** [comment]
Когда это уже исправлят? На моем сервере дюпают эту вещь тонами!

**Comment by stal111** [comment]
The Mystical Dagger has been removed in 1.21, thus this can no longer happen.
