### ISSUE TITLE
Config option to disable rain consequence

### ISSUE THREAD

**Issue by NullOrNaN** [stal111/Forbidden-Arcanus#288]
**Is your feature request related to a problem? Please describe.**
It's very frustrating on servers with multiple players doing things when corruption causes rain.

**Describe the solution you'd like**
Separate config options for change corruption consequences due to servers.

**Describe alternatives you've considered**
Fully disabling debuffs/consequences. This is ideal as it impacts player experience.

**Additional context**
This is happening on forbidden arcanus - 1.18.2 - 2.1.0 beta 3

**Comment by stal111** [comment]
Consequences have been completely removed in newer versions.
