### ISSUE TITLE
[Suggestion] 1.12.2 Please add CT Support.

### ISSUE THREAD

**Issue by Silverrain2004** [stal111/Forbidden-Arcanus#29]
It is a wonderful Mod so far, but atm for me, and i think for many others of no use.

Becouse there isnt the possibility to Tweak, or create Recipes. So please can you Add Crafttweaker support?

https://github.com/CraftTweaker

**Comment by stal111** [comment]
Maybe in the future but only for 1.14+ as 1.12.2 is no longer supported
