### ISSUE TITLE
hephaestus forge not working 1.18.2

### ISSUE THREAD

**Issue by Pavranium2411** [stal111/Forbidden-Arcanus#290]
Tried to craft eternal stella but the gavel isnt doing anything
![Screenshot 2022-08-29 181310](https://user-images.githubusercontent.com/110339407/187256682-739cfbb8-85fd-4a57-8c24-db430d650062.jpg)

**Comment by stal111** [comment]
Are you using the Radium Reforged mod? Cause that is known to break the Hephaestus Forge and many other mods.

**Comment by Pavranium2411** [comment]
Idont have radium reforged but i have radium

**Comment by stal111** [comment]
That's Radium Reforged then. Remove that mod and it should work again. I can't do anything to fix this, unfortunately.

**Comment by Pavranium2411** [comment]
Does rubidium cause issues as well?

**Comment by stal111** [comment]
I at least don't know any issues caused by Rubidium.

**Comment by pouffy** [comment]
> Does rubidium cause issues as well?

I use rubidium to play on my server with F&A and so far I've had no issues with it. so it should be fine.

**Comment by Pavranium2411** [comment]
Still dont work
