### ISSUE TITLE
Ticking entity Crash

### ISSUE THREAD

**Issue by Merithor** [stal111/Forbidden-Arcanus#291]
Mod Pack: ATM 7 , latest patch.
Was being raided by Barbarians, the only thing thats changed was my villagers armor since the last raid, could be an enchant or a bow from the Twilight Forest (as per some of the changes I want to make my Guards stronger).

Current Behavior
Crashing on a Ticking Entity, something incompatible with Minecolonies. One of the new pieces of armor or weapons I have given my guards.
Dev of Minecolonies sent me this way, appearantly its from this mod

Expected Behavior
Not to crash.

Reproduction Steps
Have a raid, give Guards armor dropped from Apotheosis Boss mobs (End Dimension dropping), this includes Twilight Forest Bows.
One of my guards may have something enchanted with F&A , but I cannot figure out what would be it.

Logs
https://pastebin.com/mzMN72qM

**Versions**
 - Forbidden & Arcanus: 2.1.0 Beta2
 - Valhelsia Core:
 - Forge:

**Additional context**
It some how can be avoided if I dont participate in the battle by flying away, but that makes keeping my soldiers from dying.
https://github.com/ldtteam/minecolonies/issues/8600  ; As proof that the Dev sent me here.

**Comment by Merithor** [comment]
To also note, no one including myself have any of the Weapons/Tools of F&A, and since the only Enchant is Permafrost from F&A, Nothing in my village has it in use.. So I don't know what really causes the crash.

**Comment by stal111** [comment]
This was fixed in 1.19.2-2.1.0-beta-1. Not sure if I will backport this at a later point.
