### ISSUE TITLE
indestructible enchant no implement with apotheosis

### ISSUE THREAD

**Issue by ComeBelin** [stal111/Forbidden-Arcanus#292]
Good evening, 
I come to report a problem I have with apotheosis. I desperately try to put the indestructible forbidden arcanus enchanted book but whatever I do it does not want to be created. on the other hand the permafrost enchantment is well implemented. I have already contacted the creators of apotheosis. I just come to keep informed.
minecraft version 1.18.2 
apotheosis version 1.16.5-4.8.99F 
forbidden arcanus version 1.18.2-2.0.0

**Comment by stal111** [comment]
Your issue is that you can't get an enchanted book with Indestructible? That's intended as the Eternal modifier is no longer an actual enchantment and instead a completely custom system.
