### ISSUE TITLE
Issue : Contact

### ISSUE THREAD

**Issue by AbsolemJackdaw** [stal111/Forbidden-Arcanus#293]
Hello ! 

I'm seeking an audience with cesar zorak, but none of the discord invites on the mod pages work, 
so i came here to seek an invite link to discord for discussion

**Comment by pouffy** [comment]
https://discord.gg/sMfUTfCpMf

**Comment by AbsolemJackdaw** [comment]
Im reopening this because clicking the link didnt work. It says the link expired

**Comment by AbsolemJackdaw** [comment]
![Screenshot_2022-09-07-01-28-48-90](https://user-images.githubusercontent.com/3628535/188757736-f9d68eb6-f405-487b-8710-2847d69d5cc0.jpg)

**Comment by pouffy** [comment]
were you banned?

**Comment by AbsolemJackdaw** [comment]
I cannot recall ever having joined the discord, and i have only ever been banned from one discord because of a petty argument on art.

**Comment by pouffy** [comment]
I've only seen something like that happen if you're banned from a server.

**Comment by AbsolemJackdaw** [comment]
I have send this github issue to my brother who lives a country over, and asked for some discord contacts to try and join the discord.
None of them could. 

I'm now on my pc, and everyone else got the same message "Unable to accept invite"

I'm just going to put the question in here, 
I initially wanted to join the discord to ask why the mod wasn't allowed distribution. 
The distribution prevents people, like me, to use curseforge's maven to download the mod as a dependency trough gradle. 
I was looking to make an addon for it, and automatisation like gradle and maven are a must and a blessing when working with other people's mods. 
I guess my question is if the restriction will ever be lifted, so people can make addons for the mod without hassle

**Comment by stal111** [comment]
Thanks for notifying me that the links didn't work. Somehow all invites got paused, but I've enabled them again now so you should be able to join now. 

Regarding your question: Do you mean the third-party distribution toggle? Cause last time I checked, it allowed third-party downloads, but I can ask Cesar to double check. 

I'm also a bit interested in what type of addon you want to create :)
