### ISSUE TITLE
Hephaestus forge structure requires air

### ISSUE THREAD

**Issue by dutch-gamer** [stal111/Forbidden-Arcanus#294]
The Hephaestus forge needs a structure to be created this structure is a flat 9x9x1 square with the corners missing.
![image](https://user-images.githubusercontent.com/33627535/188920568-28ca2d81-a910-44d0-a1a2-40c4988f745b.png)
weirdly requires this structure that the corners are air blocks. if these are any other block the structure fails to create the forge.
![image](https://user-images.githubusercontent.com/33627535/188921445-f86b4fa0-83c1-47e3-a092-091ae1eb6cf5.png)
I don't know if this is intentional but if it is please update the wiki with the the required air blocks/empty space

**Comment by stal111** [comment]
This issue has been resolved in newer versions. If this still happens for you in 1.19 please comment again and the issue will be reopened.
