### ISSUE TITLE
I can't load forbidden and arcanus on 1.18.2

### ISSUE THREAD

**Issue by Adriaaa17** [stal111/Forbidden-Arcanus#295]
I don't know how I can start the game. The game crashes with the forbbiden and arcanus mod and it appears this:
The game crashed whilst initializing game
Error: java.lang.NoClassDefFoundError: net/valhelsia/valhelsia_core/core/registry/RegistryManager$Builder

**Comment by stal111** [comment]
Do you have Valhelsia Core installed? That mod is a required dependency for Forbidden & Arcanus. 
https://www.curseforge.com/minecraft/mc-mods/valhelsia-core

**Comment by Adriaaa17** [comment]
yes I have it, when I put it and I try to open minecraft it appears this: 
The game crashed whilst initializing game
Error: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered

**Comment by stal111** [comment]
You probably have Optifine installed which is incompatible. If not please provide more context (upload the full crash log).

**Comment by Adriaaa17** [comment]
Optifine is incompatble?I will try to update the Optifine version. This is all the crash text I don't know why don't show more details.
thanks for your attention.

**Comment by Adriaaa17** [comment]
It doesn't works with Optifine UHD 7

**Comment by stal111** [comment]
Yeah it's known and we cannot really fix it since Optifine is closed source which means we can't see how it changes the stuff we need

**Comment by Adriaaa17** [comment]
Oh ok, thanks for your atention.
