### ISSUE TITLE
Missing Cherry Boat recipe

### ISSUE THREAD

**Issue by brnbrd** [stal111/Forbidden-Arcanus#297]
**Describe the bug**
Cherry Boat has no crafting recipe.

**To Reproduce**
Use any recipe viewer (such as JEI) to check crafting recipe.

**Expected behavior**
Should be craftable with 5 Cherry Planks in a U shape.

**Screenshots**
N/A

**Versions**
 - Forbidden & Arcanus: 1.19.2-2.1.0-beta1
 - Valhelsia Core: 1.19.2-0.4.0
 - Forge: 43.1.25

**Additional context**
N/A

**Comment by stal111** [comment]
Added the missing recipes in forbidden_arcanus-1.19.2-2.1.0-beta2
