### ISSUE TITLE
1.19.2 Valhelsia Core and + Crash upon startup

### ISSUE THREAD

**Issue by xd4rkzghost01** [stal111/Forbidden-Arcanus#298]
English is not my native language, syntaxe may be wrong. Im sorry
**Describe the bug**
Game Crash upon startup. Says Valhelsia Core or 2 more are the problem.

**Version**
Minecraft 1.19.2
Forge 43.1.25
Optifine 1.19.2 HUD U H9
Mods list : See screenshots

**Expected behavior and Step to reproduce**
Lunch the game with all these mods and hope it work perfectly ?

**Screenshots**
![ModList](https://user-images.githubusercontent.com/63568312/190338979-3e86e031-42a2-4bae-8086-09c2183febcb.jpeg)

**Versions**
 - Forbidden & Arcanus: 1.19.2 - 2.1.0 (beta)
 - Valhelsia Core: 1.19.2 - 0.4.0
 - Forge: 43.1.25

**Additional context**
The crash log say Valhelsia Core have the error but the in the log i can see that EnhancedCelestials and AwesomeDungeonEnd seem to conflict But, if i deactivate Forbidden (and Valhelsia at the same time) Everything works fine.

[latest.log](https://github.com/stal111/Forbidden-Arcanus/files/9572789/latest.log)
[crash-2022-09-15_02.55.01-client.txt](https://github.com/stal111/Forbidden-Arcanus/files/9572791/crash-2022-09-15_02.55.01-client.txt)

**Comment by xd4rkzghost01** [comment]
**Update**
After research (and finding Discord comment from other) it is Optifine that is not compatible.
Removing Optifine solve the issue and all those mods work perfectly.

**Comment by stal111** [comment]
Yes, Valhelsia Core is currently incompatible with Optifine and we can't really fix it as Optifine is closed source.
