### ISSUE TITLE
Issue with Zombie Arm that is possibly related to applied math

### ISSUE THREAD

**Issue by GoldenFurredFox** [stal111/Forbidden-Arcanus#299]
**Describe the bug**
The Zombie Arm item doesn't work when trying to cure a zombie more than once, and can actually reverse previously performed cures, as it seems to set the number of times a zombie has been cured to 1 instead of incrementing it by one.

**To Reproduce**
1. Zombify a villager with the Zombie Arm
2. Cure the villager
3. The villager's trades will be reduced once, and not again. If you have already cured a villager without using the Zombie Arm, their number of times cured is reset to 1 regardless.

**Expected behavior**
It is expected that the amount of times cured should be incremented by one versus being changed to 1 regardless of original cures applied.

**Screenshots**

**Versions**
 - Forbidden & Arcanus: 1.18.2-2.1.0-beta3
 - Valhelsia Core: 1.18.2-0.3.1
 - Forge: 1.18.2-40.1.74

**Additional context**
I am using the All the Mods 7 modpack version 0.4.30.

**Comment by GoldenFurredFox** [comment]
I'm genuinely not even sure if leaving a reply brings this to the front or not, so my apologies if it does and bumping the report isn't allowed or something.

~~This hasn't been touched in 7 days and I'm genuinely curious why bugs made less than a day ago are being considered prior to this one. Is something unspoken occurring because this issue has already been reported a million times and it won't be fixed or is working as intended? I need answers here.~~

My apologies, I somehow failed to notice my report was the most recent one made. I'll shut my impatient self up now.

**Comment by stal111** [comment]
This will be addressed whenever I get some time for it, please don't be impatient.

**Comment by GoldenFurredFox** [comment]
I'm genuinely sorry, I know some modpacks have really small teams, I just assumed with the massive amount of content you manage to push that you probably had a decently sized team behind you who regularly checked issues.

**Comment by stal111** [comment]
I made some changes to the Zombie Arm in forbidden_arcanus-1.19.2-2.1.0-beta2 which _hopefully_ should fix the issue. Would be awesome if you could try it out.
