### ISSUE TITLE
Arcane Crystal Obelisk can't be waterlogged

### ISSUE THREAD

**Issue by WenXin20** [stal111/Forbidden-Arcanus#30]
**Describe the bug**
The Arcane Crystal Obelisk can't be waterlogged, which could make for a great underwater decoration.

**To Reproduce**
1. Place the Arcane Crystal Obelisk underwater

**Expected behavior**
It should be waterloggable.

**Version(please complete the following information):**
 - Forbidden & Arcanus: v1.5-beta-4
 - Forge: v28.1.107

**Comment by WenXin20** [comment]
Also found out that the Candelabra can be waterlogged but can't be placed underwater?

**Comment by stal111** [comment]
Added Waterlogging to the Arcane Crystal Obelisk in 1.15.2-1.3 :)
