### ISSUE TITLE
Cannot get nipa to generate in the Twilight Forest despite config and tag set to allow it

### ISSUE THREAD

**Issue by saltyseadoggo** [stal111/Forbidden-Arcanus#303]
**Describe the bug**
I cannot get the nipa structures to generate in the Twilight Forest dimension, despite having added its biomes to the `has_structure/nipa` tag *and* ensuring that the TF dimension is not blacklisted or excluded by a whitelist in `forbidden_arcanus-common.toml`. This mod's config file implies that nipa should be able to generate in every dimension that isn't blacklisted if the whitelist is empty, which it is by default.

**To Reproduce**
1. Add this mod and Twilight Forest to a testing installation.
2. Create a datapack that adds `#twilightforest:in_twilight_forest` to the biome tag `has_structure/nipa`. That biome tag contains all of TF's biomes, meaning that, according to the config, nipa should be able to generate anywhere in the TF when this datapack is loaded.
3. Load this datapack either by adding it to a new world on creation, or via OpenLoader.
4. Enter a new world, then run `/execute in twilightforest:twilight_forest run tp ~ ~ ~` to enter the Twilight Forest dimension.
5. Run `/locate structure forbidden_arcanus:nipa` to try to find nipa structures.
6. Observe that the command will not locate any nipa structures, indicating that none generated.

**Expected behavior**
If the nipa structure's dimension whitelist and blacklist are set to not exclude the Twilight Forest dimension, and biomes in the TF are added to the `has_structure/nipa` biome tag, nipa should generate in the Twilight Forest in the specified biomes.

**Versions**
 - Forbidden & Arcanus: 2.1.0-beta1
 - Valhelsia Core: 0.4.0
 - Forge: 43.1.26
 - Twilight Forest: 4.2.1392

**Comment by stal111** [comment]
I'd invite you to join the Discord server as it would make it easier to find the cause on why it isn't working for you. Pretty sure it should be achievable if done correctly with the `has_structure/nipa` biome tag.
