### ISSUE TITLE
Cannot make edelwood generate in biomes that aren't dark forests

### ISSUE THREAD

**Issue by saltyseadoggo** [stal111/Forbidden-Arcanus#304]
**Describe the bug**
There is no biome modifier or tag that players can modify to get edelwood to spawn in biomes that aren't the default dark forest. In addition, making one's own biome modifier to add the edelwood feature to other biomes doesn't work; the edelwood trees simply do not generate.

**To Reproduce**
1. Make a datapack containing this biome modifier to add edelwood to the plains biome:
{
  "type": "forge:add_features",
  "biomes": "minecraft:plains",
  "features": "#test:edelwood",
  "step": "vegetal_decoration"
}
2. Add this tag to `data/test/tags/worldgen/placed_feature`:
{
  "values": [
    "forbidden_arcanus:edelwood"
  ]
}
The tag is needed because, if we reference the placed feature in the biome modifier directly, we can't create a new world, as an error pertaining to datapacks will be thrown. I found this solution by referencing Ars Nouveau.
3. Load this datapack either by adding it to a new world, or with OpenLoader.
4. Enter a new world.
5. Find a plains biome.
6. Observe the lack of edelwood in the plains biome.

**Expected behavior**
- Edelwood should be added to the vanilla dark forest biome using a forge biome modifier so players and modpack makers can see how it's added to worldgen, and change what biomes it's added to with datapacks.
- Edelwood should *not* ignore custom biome modifiers that add it to other biomes; it should generate in any biome it is told to generate in.

**Versions**
- Forbidden & Arcanus: 2.1.0-beta1
- Valhelsia Core: 0.4.0
- Forge: 43.1.26

**Comment by stal111** [comment]
Edelwood Trees are already added through biome modifiers. This is the one for them: https://github.com/stal111/Forbidden-Arcanus/blob/1.19/src/generated/resources/data/minecraft/forge/biome_modifier/add_edelwood_trees.json which you missed. Adding more biome modifiers or overwriting this one also allows them to spawn in other biomes.
