### ISSUE TITLE
Obsidian skull/shield doesn't work as expected

### ISSUE THREAD

**Issue by portega** [stal111/Forbidden-Arcanus#307]
**Describe the bug**
Obsidian shield doesn't work in the offhand. Also any of them will protect armor from lava

**To Reproduce**
1. Use obsidian shield in offhand
2. Jump on lava/over fire
3. Shield has no effect.

Tried both shield and skull, shield in both hands and inventory. Offhand does't protect. Items gives fire protection when in inventory but doesn't protect chestplate (fire resistance potion does).

**Expected behavior**
Same behaviour as fire resistance potion

**Screenshots**

**Versions**
 - Forbidden & Arcanus: 2.0.3
 - Modpack: Create Automation 1.18.1 Expert
 - Forge: 39.1.2

**Additional context**

**Comment by stal111** [comment]
1.18.1 is an unsupported version. We made some changes to how the skulls work in 1.18.2 so I guess this is fixed. Please try if you can reproduce this in newer versions (ideally 1.19.2), otherwise I'll close this.
