### ISSUE TITLE
Crash on startup 1.19.2 on Forge 43.1.1 with  OptiFine HD U H9

### ISSUE THREAD

**Issue by Viuiq** [stal111/Forbidden-Arcanus#308]
Minecraft 1.19.2 crashes on startup - only ghost processes are visible in Task Manager
Minecraft won't start the launcher if those processes won't be killed.
Taking OptiFine out of the mods folder results in no crash.

1. Install Minecraft Java 1.19.2
2. Install Forge 43.1.1 (newest stable release)
3. Add to mod folder the downloaded mods for Forbidden and Arcanus (newest release) and OptiFine (newest release "HD U H9"):
"forbidden_arcanus-1.19.2-2.1.0-beta1.jar"
"valhelsia_core-forge-1.19.2-0.4.0.jar"
"OptiFine_1.19.2_HD_U_H9.jar"
4. Launch Minecraft - observe that it crashes leaving only the ~6 boundeled proceses in Task Manager

**Expected behavior**
Minecfart loads into Menu

**Versions**
 - Forbidden & Arcanus: 1.19.2-2.1.0-beta1
 - Valhelsia Core: 1.19.2-0.4.0
 - Forge: 43.1.1
 - OptiFine: HD U H9

**Crash Log**
In attachment.

[crash-2022-10-07_01.06.16-client.txt](https://github.com/stal111/Forbidden-Arcanus/files/9729128/crash-2022-10-07_01.06.16-client.txt)

**Comment by stal111** [comment]
It's known that Valhelsia Core is currently incompatible with Optifine and we cannot do anything about it at this moment. There are many Optifine alternatives you could use.
