### ISSUE TITLE
[1.18.2] Unable to make any reinforced arcane gold tools

### ISSUE THREAD

**Issue by KajesLorian** [stal111/Forbidden-Arcanus#309]
**Describe the bug**
Unable to craft or find online any way to make the reinforced Arcane gold Gavel and other tools

**Versions**
 - Forbidden & Arcanus: 1.18.2-2.0.0
 - Valhelsia Core: 0.4.0
 - Forge: 1.18.2 40.1.68

**Comment by stal111** [comment]
Not an issue, they simply don't have a way of obtaining yet which is intended.
