### ISSUE TITLE
Game crashes while mousing over the Cilbano Combusting recipe for Arcane Crystal: No ResidueType found

### ISSUE THREAD

**Issue by jangro** [stal111/Forbidden-Arcanus#312]
**Describe the bug**
When hovering the mouse over the Cilbano Combusting recipe for Arcane Crystal dust in REI or JEI, the game crashes with a No ResidueType found error.

**To Reproduce**
1. Search for arcane crystal dust in JEI
2. View the recipe in the Cilbano Combusting and hover the mouse over it.
3. Crash

**Expected behavior**
No crash

**Screenshots**

Here's the crash log...
https://crashy.net/0cVgErgKLELbJhz259Tu

**Versions**
 - Forbidden & Arcanus: forbidden_arcanus-1.19.2-2.1.0-beta2
 - Valhelsia Core: valhelsia_core-forge-1.19.2-0.4.0
 - Forge: 43.1.47

**Additional context**
This is on Valhelsia 5.0.4

**Comment by stal111** [comment]
Fixed in the 2.1.0 release.
