### ISSUE TITLE
Edelwood buckets convert baby chickens to adults

### ISSUE THREAD

**Issue by jangro** [stal111/Forbidden-Arcanus#313]
**Describe the bug**
Picking up a baby chicken with an edelwood bucket turns it into an adult after putting it back down. 

**To Reproduce**
1. breed a baby chicken so you know it's fresh!
2. pick it up with an edelwood bucket
3. put it down
4. observe adult chicken

**Expected behavior**
I guess either put a baby chicken back down, or don't allow baby chickens to be picked up.

**Screenshots**

Versions

Forbidden & Arcanus: forbidden_arcanus-1.19.2-2.1.0-beta2
Valhelsia Core: valhelsia_core-forge-1.19.2-0.4.0
Forge: 43.1.47
Additional context
This is on Valhelsia 5.0.4

**Comment by Vaelzan** [comment]
I just went to report this, only to find that you beat me to it, Jangro. :)

**Comment by HeroBrianMack** [comment]
This problem persists in future versions, and it seems that the bucket doesn't save things like names or damage either, it's a tad late but I'll include this in my pull request for 1.20.1

**Comment by stal111** [comment]
Edelwood Buckets can no longer contain entities in 1.21.
