### ISSUE TITLE
Cherry Blossom Leaf Carpets spawn above the tree

### ISSUE THREAD

**Issue by milkev** [stal111/Forbidden-Arcanus#314]
**Describe the bug**
Cherry blossom leaf carpet spawns on the 'highest block in the column' rather than on the ground under the tree.

**To Reproduce**
1. Place a platform of blocks above a cherry blossom tree
2. Break the cherry blossom tree (tested with vein miner & create mechanical saw)
3. Check on the top platform, there is almost always a couple leaf carpets on it.

**Expected behavior**
leaf carpet is created below the tree

**Screenshots**
![2022-11-08_17 13 18](https://user-images.githubusercontent.com/22010128/200704417-33a41f7d-c8cc-4ffa-b5f0-c4dba63ae36a.png)
![2022-11-08_17 13 15](https://user-images.githubusercontent.com/22010128/200704422-96840eec-8149-4fe3-8827-498184a82578.png)

**Versions**
 - Modpack: ATM7 (1.18.2)
 - Forbidden & Arcanus: 1.18.2-2.1.0beta3
 - Valhelsia Core: 1.18.2-0.3.1
 - Forge: 40.1.80

**Additional context**
is an extremely niche thing, but for people doing indoor tree farms, or making their base underground, this would be weird to see. in my case its easy to avoid since i dont really care where my tree farm is, though its kind of annoying that i have to move it if i dont want leaf carpet on my (to be created) flying ship.
I am running on a dedicated server, and have not tested in singleplayer. I doubt that will make a difference in this case though.

**Comment by stal111** [comment]
This got fixed now in the 1.19 version. Due to how old 1.18.2 already is and this bug being very niche I currently do not plan to backport it.
