### ISSUE TITLE
Crash at start

### ISSUE THREAD

**Issue by Adlez8475** [stal111/Forbidden-Arcanus#315]
It just crash, without any question. It worked yesterday, and today the mod has decide to not work anymore.

**Versions**
 - Forbidden & Arcanus: 1.19.2-2.1.0-beta2
 - Valhelsia Core: 1.19.2-0.5.0
 - Forge: 43.2.0

Here is the crashlog and the log files:
[latest.log](https://github.com/stal111/Forbidden-Arcanus/files/10247755/latest.log)
[crash-2022-12-16_18.16.35-fml.txt](https://github.com/stal111/Forbidden-Arcanus/files/10247760/crash-2022-12-16_18.16.35-fml.txt)

**Comment by stal111** [comment]
Please update to the newest Forbidden & Arcanus version if you want to use Valhelsia Core 0.5.0
