### ISSUE TITLE
Netherite Blacksmith Gavel item is not environment-immune

### ISSUE THREAD

**Issue by Twisted-Code** [stal111/Forbidden-Arcanus#317]
**Describe the bug**
the Netherite Blacksmith Gavel can be destroyed by environmental damage sources, e.g. explosions or lava, despite being made out of netherite.

**To Reproduce**
1. Obtain a Netherite Blacksmith Gavel
2. Throw it in lava/into fire/cause an explosion near it (take your pick or do all three with different gavels)
3. POOF, Nether tool destroyed!

**Expected behavior**
As a netherite tool, Netherite Gavel should not take environment damage e.g. from explosions or lava

**Screenshots**

**Versions**
 - Forbidden & Arcanus: 1.18.2-2.1.0-beta3
 - Valhelsia Core: 1.18.2-0.4.0
 - Forge: 40.1.84

**Additional context**
I realize this is kind of on the fence between bug and feature, since the mod never explicitly says Netherite Gavels are environment-proof, but... like, it's made of Netherite, and that's a key feature of the vanilla tools, right?
to simplify implementation for yourself, you may want to look at how http://github.com/SlimeKnights/TinkersConstruct implements the Netherite modifier for Tinker tools.

**Comment by stal111** [comment]
Fixed in the newest release for both 1.18.2 and 1.19.2.
