### ISSUE TITLE
Forbidden and Arcanus & Shaders

### ISSUE THREAD

**Issue by Zapzidus** [stal111/Forbidden-Arcanus#319]
I'm using rubidium to use my shaders while playing this mod but when I use my Hephaestus forge I cant see the particles. The shaders I am using are complimentary shaders is there any way to fix the particle issue?

**Comment by stal111** [comment]
Are you talking about the Magic Circle or the actual Aureal Particles that spawn when completing a ritual? It is known that the Magic Circle is currently incompatible with certain shaders, but I don't know how to fix that.
