### ISSUE TITLE
Flower Pots Duplicate Saplings

### ISSUE THREAD

**Issue by WenXin20** [stal111/Forbidden-Arcanus#32]
**Describe the bug**
- Placing a Cherrywood or Mysterywood Sapling in a flower pot will consume two saplings
- Right-clicking the potted saplings will return 2 saplings if the hand is empty.

**To Reproduce**
1. Place Cherrywood/Mysterywood Saplings in a flower pot.
2. Right-click it to get two back.
3. Placing it in a flower pot will consume two if holding more than one.

**Expected behavior**
Flower pots should consume and return one sapling only.

**Version:**
 - Forbidden & Arcanus: v1.5 beta 4
 - Forge: v28.1.109

**Comment by stal111** [comment]
Will be fixed in forbidden_arcanus-1.15.2-1.2-beta-5
