### ISSUE TITLE
Crash MixinTransformerError

### ISSUE THREAD

**Issue by ClaudiusMinimus** [stal111/Forbidden-Arcanus#322]
**Describe the bug**
While updating my pack, the latest versions Forbidden & Arcanus and Valhelsia Core crash the client. If I revert to the previous version the game launches fine.

**To Reproduce**
1. Updated to Forbidden & Arcanus 1.18.2-2.1.1 and Valhelsia Core 1.18.2-0.4.0
2. Game crashes on startup

**Versions**
 - Minecraft: 1.18.2
 - Forbidden & Arcanus 1.18.2-2.1.1
 - Valhelsia Core 1.18.2-0.4.0
 - Forge 40.1.85

Crash Report: [Formatted](https://crashy.net/32503c4e-02d9-4d52-aceb-c98d9e7fe20d) / [Raw](https://crashy.net/32503c4e-02d9-4d52-aceb-c98d9e7fe20d/raw.txt)

**Comment by stal111** [comment]
Optifine is incompatible with Valhelsia Core as it removes some vanilla code the mod relies on. You should use Rubidium and Oculus as Optifine replacement.

**Comment by ClaudiusMinimus** [comment]
Thanks for letting me know. Unfortunately, I am forced to use Optifine for my pack because Conquest Reforged has it listed as a dependency. I have tried to replace it with  Rubidium and Oculus, but it just does not work. I hate dropping Forbidden & Arcanus, but that is it. Oh well...
Thanks again!
CM

**Comment by GnomTocha** [comment]
I have been looking for a problem for a very long time. If a problem is known, then such exceptions and incompatibilities are usually indicated in the description. Sorry, but a little depressed.
