### ISSUE TITLE
guide with patchouli

### ISSUE THREAD

**Issue by Developer2704** [stal111/Forbidden-Arcanus#326]
Mabey use patchouli as an optional dependency to implement an in game guide

**Comment by Developer2704** [comment]
You could also internally integrate patchouli so there is no dependency

**Comment by pouffy** [comment]
Afaik, the Forbiddenomicon will be the in-game guidebook and will not use Patchouli due to how the devs want it to function.

**Comment by stal111** [comment]
Yes we plan to create our own guidebook which is planned for one of the next updates. Writing a Patchouli one before would mostly be a waste of our resources as we could spend that time on new features.
