### ISSUE TITLE
Using test tube crashes server

### ISSUE THREAD

**Issue by XDgamer4** [stal111/Forbidden-Arcanus#328]
**Describe the bug**

**To Reproduce**
1. Go to 'Aternos.org and create server on modpack create: above and beyond'
2. Use 'test tube' on 'anythink that gives blood'
3. See error

**Expected behavior**
give me blood to test tube

**Versions**
 - Forbidden & Arcanus: forbidden_arcanus-16.2.2.jar
 - Valhelsia Core: valhelsia_core-16.0.13a.jar
 - Forge: 36.2.20

**Additional context**
run with curseforge
Minecraft crash report: https://mclo.gs/YIoNh4n

**Comment by stal111** [comment]
The 1.16 version has been unsupported for quite some time now and is usually pretty stable. I'd guess it's caused by a mod conflict but I don't have the time to investigate. The easiest solution would be to update to a newer version.
