### ISSUE TITLE
endless menu bug

### ISSUE THREAD

**Issue by captcookie** [stal111/Forbidden-Arcanus#33]
Latest 1.15.1 beta 2 version
Load mod and cant click or play mc due to the endless loading screen, and just when it shows the menu buttons it loops again. Very strange encounter.

**Comment by stal111** [comment]
Which forge version are you using?

**Comment by captcookie** [comment]
30.0.30

**Comment by Shindur** [comment]
I've had this happen on the latest 30.0.35 as well. Was going through all the different mods that I have to see what was causing it. 1.15.1 - 1.0 - beta 2.

**Comment by stal111** [comment]
Should be fixed in 1.15.1-1.0-beta-3 :)
