### ISSUE TITLE
Cherry tree config problem

### ISSUE THREAD

**Issue by ianm1647** [stal111/Forbidden-Arcanus#330]
**Describe the bug**
Disabling cherry trees in the config doesn't disable them in game, as I am still finding them all over the world

**To Reproduce**
1. Go to config file
2. Change true to false under cherry tree generation
3. See error

**Expected behavior**
Cherry trees to be disabled

**Versions**
 - Forbidden & Arcanus: 1.19.2-2.1.2
 - Valhelsia Core: 1.19.2-0.5.0
 - Forge: 43.2.7

**Comment by stal111** [comment]
The world gen config options have been removed back in October of last year. You're now required to use datapacks to configure anything related to world gen. If you want to remove the cherry trees from spawning you'd need to overwrite the add_cherry_trees.json biome modifier the mod adds `forbidden_arcanus/forge/biome_modifier/add_cherry_trees.json`.
