### ISSUE TITLE
Fiery Modifier not working in 1.18.2

### ISSUE THREAD

**Issue by pouffy** [stal111/Forbidden-Arcanus#333]
**Describe the bug**
When using a tool with the "Fiery" Modifier, any blocks broken will not drop anything.

**To Reproduce**
1. Apply the Fiery modifier to a tool using a Smelter Prism
2. Break a block using the modified tool.
3. See error

**Expected behavior**
The block would drop it's output as if it were cooked in a furnace.

**Versions**
 - Forbidden & Arcanus: forbidden_arcanus-1.18.2-2.1.2
 - Valhelsia Core: valhelsia_core-forge-1.18.2-0.4.0
 - Forge: 40.2.1

**Comment by stal111** [comment]
Did this just start happening with the last release? Cause pretty sure it worked before. Would maybe be good if someone else could also verify it isn't working.
