### ISSUE TITLE
My launcher is crashing after I installed ( Forbidden and Arcanus) and ( Valhelsia Core)

### ISSUE THREAD

**Issue by EDMvibes** [stal111/Forbidden-Arcanus#337]
**Describe the bug**
So I just downloaded the mods and put them in my mod folder along with some other mods and when I try to press play I get an error code -1, so I try to test something and I removed both mods and the game launches fine, I put it back crashes.

**Versions**
 - Forbidden & Arcanus:
 - Valhelsia Core:
 - Forge:

**Additional context**
[crash-2023-04-22_20.30.33-client.txt](https://github.com/stal111/Forbidden-Arcanus/files/11302762/crash-2023-04-22_20.30.33-client.txt)
[crash-2023-04-22_20.30.33-client.txt](https://github.com/stal111/Forbidden-Arcanus/files/11302764/crash-2023-04-22_20.30.33-client.txt)
![SPOILER_image](https://user-images.githubusercontent.com/48347662/233820139-d2916ea0-9291-4d73-b246-21d268cd3f74.png)
 ( These are the list of mods I have when I try to load up my launcher and crashed error code -1 ( when added ( Forbidden and Arcanus) and ( Valhelsia Core)

**Comment by stal111** [comment]
Optifine removes some code the mod relies on. Your only option will be to remove Optifine and replace it with other alternatives like Rubidium and Oculus.
