### ISSUE TITLE
Use IRecipe to Distinguish Hephauestus Forge recipetype

### ISSUE THREAD

**Issue by Explode007** [stal111/Forbidden-Arcanus#338]
As a modpack dev, I Would like to be able to add and change recipes to the hephaestus forge as need be,
as is it's much harder to do so because the forge does not have it's own 'recipetype'

add 'type: hephaestus_forge' to the JSON

Alternatives: Not use the mod :(

**Comment by pouffy** [comment]
You can add recipes to the Hephaestus Forge by using the same directories as the original recipes. I have a guide for adding custom rituals in the F&A discord.

**Comment by Explode007** [comment]
May you link me? I can't seem to find the plug for F&A discord.

**Comment by pouffy** [comment]
https://discord.com/channels/574476444366012420/574487653592989697/1013566730313945238

**Comment by Explode007** [comment]
No like, the actual server :)

**Comment by pouffy** [comment]
https://discord.gg/2FpJXHbKyb

**Comment by stal111** [comment]
I'm sorry but this won't happen. The reason that we don't use the default mc recipe system is that we have rituals that don't create items as a result (for example the rituals that increase the forge level or soon the rituals that summon mobs).

As pouffy already said, all rituals can be modified/removed/added through datapacks though.
