### ISSUE TITLE
[1.19.4-2.2.0-beta1] Am I missing something?

### ISSUE THREAD

**Issue by EDMvibes** [stal111/Forbidden-Arcanus#339]
**Describe the bug**
So I got the mod to work for my launcher, and it works for my server but when I logged in to see what kind of stuff would be added compared to the other version I've seen on YouTube I felt like I don't see much from what I've seen, I know it says 1.19.4 beta, but it doesn't tell me if I'll be getting this and some items were removed, so It's hard to tell what I'm getting out of this mod, also when I try to search some of these items on JEI mod nothing shows up.

Don't get me wrong after seeing YouTube video on this mod it's really cool, I just want to know if this version is not done yet, or I need something else to run it.

**Versions**
 - Forbidden & Arcanus: 1.19.4-2.2.0-beta1
 - Valhelsia Core: [[Forge] Valhelsia Core - 0.5.0]
 - Forge: 1.19.4 - 45.0.49

**Additional context**

https://user-images.githubusercontent.com/48347662/234154281-63e1758b-9ea1-4120-aab9-af6db558fe77.mp4

**Comment by stal111** [comment]
This is a known issue. Minecraft changed the way creative tabs are done in 1.19.3 (items now need to be added manually) and I haven't had time yet to adjust all items. There is also a note in the changelog for the version stating that.
 
![image](https://user-images.githubusercontent.com/48628578/234276918-0cd7cd8f-5d40-4eec-8410-3a1505d7f69d.png)
