### ISSUE TITLE
Clibano Refuses to work

### ISSUE THREAD

**Issue by Mrtrex525** [stal111/Forbidden-Arcanus#340]
I spent ages making the clibano just for it to not work all i did was make the clibano and it does not work even if i put fuel in it like oak

**Comment by stal111** [comment]
What are you exactly trying to smelt in the clibano? All valid recipes can be seen in JEI.

**Comment by Mrtrex525** [comment]
That's the problem it does not have a crafting recipe and I had to spawn in the core just to use it and I'm not using JEI because I'm playing on Dawn Craft and I put the mod into the ModPack.

**Comment by stal111** [comment]
If something does not have a crafting recipe it's not intended to be used. The clibano was never finished in 1.18, so there are no recipes for it.

**Comment by Mrtrex525** [comment]
then how am i meant to progress?
