### ISSUE TITLE
The Hephaestus Smithing don't work !

### ISSUE THREAD

**Issue by Rapid0x** [stal111/Forbidden-Arcanus#341]
**The Hephaestus Smithing don't work !**
I'm playing on the Create Back and Track mod pack I tried to make a hephaestus forge however when I came across a recipe it didn't work.

**To Reproduce**
1. try to make a recipe in the hephaestus smithing and it's don't work
2. No error in the console

**Expected behavior**
The recipe work and the hephaestus smithing work

**Versions**
 - Forbidden & Arcanus: 1.18.2-2.1.1
 - Valhelsia Core: 1.18.2-0.4.0
 - Forge: 40.2.2

**Comment by stal111** [comment]
The modpack includes the Radium Reforged mod which prevents the forge from working. Remove it and replace all pedestals.
