### ISSUE TITLE
book guide

### ISSUE THREAD

**Issue by Thunderrock424242** [stal111/Forbidden-Arcanus#342]
**Is your feature request related to a problem? Please describe.**
no

**Describe the solution you'd like**
a book ingame with rituals that you can do with guides in the book. becasue for a beginner you have no clue how to do anything

**Describe alternatives you've considered**

change up the wiki to add that

**Additional context**
if you put it on all versions that would be da best but i am hoping you do it for 1.18.2

**Comment by stal111** [comment]
A guide book is already planned although not sure when we will actually get to implement it. If you want to see the valid rituals please use the JEI mod for now.
