### ISSUE TITLE
shader bug with the ring on black hole. 1.19.2  

### ISSUE THREAD

**Issue by kaairu** [stal111/Forbidden-Arcanus#343]
**Describe the bug**
there is normally a purple ring around the black hole without shaders, with them the purple ring dissapears

**To Reproduce**
get ocoulus/rub and get any shader. i was using complementary reimagined

![image](https://github.com/stal111/Forbidden-Arcanus/assets/121336317/64804cc0-3bea-4eff-8a88-ec650d16cfec)
![image](https://github.com/stal111/Forbidden-Arcanus/assets/121336317/de83fb82-73d3-4ff1-85c3-06f0e6a8da1f)

**Versions**
 - Forbidden & Arcanus: 2.1.3
 - Valhelsia Core: 0.5.0
 - Forge: 43.2.8

**Comment by stal111** [comment]
Please reopen if this is still an issue in 1.21.
