### ISSUE TITLE
Edelwood null bucket

### ISSUE THREAD

**Issue by Eternus95** [stal111/Forbidden-Arcanus#344]
Conflict with mod "Supplementaries"

when trying to use a jar from that mod on a slime it returns a null bucket crashing the game 
(the slime is supposed to get trapped in the jar)

"java.lang.NullPointerException: Bucketable modded entity minecraft:slime returned a null bucket!"

I saw a bunch of reports related to the edelwood bucket, not sure if this is already known or not, it's my first time reporting an issue here.

**Comment by stal111** [comment]
This should no longer happen in 1.21.
