### ISSUE TITLE
Some issue compatibility with Alex Mobs and Forbidden Arcanus, dont know which mod is causing the issue

### ISSUE THREAD

**Issue by lSherozl** [stal111/Forbidden-Arcanus#347]
<img width="980" alt="image" src="https://github.com/stal111/Forbidden-Arcanus/assets/65663746/e8474e4e-6709-4a35-9e04-9623b761cf4d">

https://github.com/AlexModGuy/AlexsMobs/issues/1624#issue-1719029470

**Comment by lSherozl** [comment]
When you load back in the world, the mob is found inside the cube

**Comment by lSherozl** [comment]
The squid for sure crashes the game, the whale sometimes 
<img width="660" alt="image" src="https://github.com/stal111/Forbidden-Arcanus/assets/65663746/133d2b64-04f5-41b0-92f5-d249b654b547">

**Comment by lSherozl** [comment]
Mod was tested with just Forbidden and Arcanus and Alex mobs, game still crashes when you try to capture the squid, whale does too, it worked first time but it seems to happen sometimes especially when you do it under water 
<img width="1195" alt="image" src="https://github.com/stal111/Forbidden-Arcanus/assets/65663746/6520f172-7e0b-4e99-a5eb-ed46a0ea5c70">
[latest.log](https://github.com/stal111/Forbidden-Arcanus/files/11528393/latest.log)
<img width="1280" alt="image" src="https://github.com/stal111/Forbidden-Arcanus/assets/65663746/d69d3799-da67-49a3-ad99-80a8348ec011">

**Comment by stal111** [comment]
> Mod was tested with just Forbidden and Arcanus and Alex mobs, game still crashes when you try to capture the squid, whale does too, it worked first time but it seems to happen sometimes especially when you do it under water <img alt="image" width="1195" src="https://user-images.githubusercontent.com/65663746/239839485-6520f172-7e0b-4e99-a5eb-ed46a0ea5c70.png"> [latest.log](https://github.com/stal111/Forbidden-Arcanus/files/11528393/latest.log) <img alt="image" width="1280" src="https://user-images.githubusercontent.com/65663746/239840471-d69d3799-da67-49a3-ad99-80a8348ec011.png">

Could you please also upload the crash log for this with just f&a and Alex Mobs?

**Comment by lSherozl** [comment]
> > Mod was tested with just Forbidden and Arcanus and Alex mobs, game still crashes when you try to capture the squid, whale does too, it worked first time but it seems to happen sometimes especially when you do it under water <img alt="image" width="1195" src="https://user-images.githubusercontent.com/65663746/239839485-6520f172-7e0b-4e99-a5eb-ed46a0ea5c70.png"> [latest.log](https://github.com/stal111/Forbidden-Arcanus/files/11528393/latest.log) <img alt="image" width="1280" src="https://user-images.githubusercontent.com/65663746/239840471-d69d3799-da67-49a3-ad99-80a8348ec011.png">
> 
> Could you please also upload the crash log for this with just f&a and Alex Mobs?

Sure Ill try to get it to create a crash report, since it wasnt making one

**Comment by lSherozl** [comment]
[debug.log](https://github.com/stal111/Forbidden-Arcanus/files/11528544/debug.log)


> Could you please also upload the crash log for this with just f&a and Alex Mobs?

I apologize no matter what I do, it does not create a crash report, I was able to have a debug file with just the 4 mods needed to make these two work, if I can create a crash report like I was able with all the other mods, ill post it here as soon as I keep testing

**Comment by lSherozl** [comment]
> Could you please also upload the crash log for this with just f&a and Alex Mobs?

Please let me know if the debug was helpful, if not I can continue trying to get a crash, it just seems to move me to the server, not crash the game now
