### ISSUE TITLE
Crash on mod loading

### ISSUE THREAD

**Issue by SodiumZH** [stal111/Forbidden-Arcanus#348]
**Describe the bug**
Error on load mods, unable to enter the main menu

**To Reproduce**
Simply open the game.

**Expected behavior**

**Screenshots**
![image](https://github.com/stal111/Forbidden-Arcanus/assets/46860829/4a4aa87a-f2bd-43d0-b63f-ee9c738e9e06)

**Versions**
 - Forbidden & Arcanus: 2.1.2
 - Valhelsia Core: 0.5.0
 - Forge: 43.2.0 or 43.1.42

**Additional context**
[latest.log](https://github.com/stal111/Forbidden-Arcanus/files/11602653/latest.log)
[crash-2023-05-31_01.14.31-fml.txt](https://github.com/stal111/Forbidden-Arcanus/files/11602655/crash-2023-05-31_01.14.31-fml.txt)

**Comment by stal111** [comment]
You are trying to use the 1.19.4 version of Valhelsia Core in 1.19.2.

**Comment by SodiumZH** [comment]
Sorry for the stupid problem....
