### ISSUE TITLE
Lost souls are broken

### ISSUE THREAD

**Issue by SurgeXs** [stal111/Forbidden-Arcanus#351]
Lost souls spawn very frequently, and there is almost no way to get rid of them.  The soul extractor is unreliable when used on them, and even the kill command does nothing.  Additionally, lost souls often drift into lava in the nether, where they will sit making an annoying damage noise for all eternity, with no way to remove them.

**Comment by stal111** [comment]
I'd invite you to join our discord server for better communication. You're only the second person to report very frequent spawning of them so it cannot really be a common issue, maybe a mod conflict?

**Comment by StevenJBurns** [comment]
Can confirm this behavior as well.   It's not that Lost Souls are spawning en masse, but over time in the Nether they continue to spawn while earlier spawns drift into lava and do not die.  After just several hours of playing in a fresh 1.19.2 world I have hundreds of them trapped in lava on the Nether side around my portal which is already starting to take a toll on game performance

**Comment by twosky2000** [comment]
![Screenshot 2023-10-21 010825](https://github.com/stal111/Forbidden-Arcanus/assets/9808216/4a841e42-69d3-411c-899d-995e3622f3b1)

![Screenshot 2023-10-21 011326](https://github.com/stal111/Forbidden-Arcanus/assets/9808216/c142421a-383e-4692-a26b-416ce47f1cd4)

Same and the kill command does not work.
I have almost no ghast spawn

this is in the direwolf20 modpack 1.20  version 1.2.0 with Forbidden-Arcanus 1.20.1-2.2.1

**Comment by SurgeXs** [comment]
I think an easy solution is to make them actually take damage from lava, the kill command, and the void.  As it is, they're just immune to all damage types, and it's annoying.  Even when there's one just floating around your base, it's annoying, because there's almost no way to get rid of it, and the soul collector is a pain to iluse on them, maybe just make it so you can kill them but they don't drop anything, and instead of the soul extractor damaging them, it sucks them in and gives you the item.  I feel like that makes more sense, would be more fun, and fixes this problem.

**Comment by djcprone** [comment]
> I'd invite you to join our discord server for better communication. You're only the second person to report very frequent spawning of them so it cannot really be a common issue, maybe a mod conflict?

Any update on fixing this? It *is* an issue. Over time, because they can't be killed they get to be too much. Can you maybe just add a way as suggested above that we can kill them but without getting anything, so then the /kill command will work. Or add something to the config for spawn rate or max entities or let us blacklist dimensions like the nether, etc. There's a lot of ways to go about it. Your mod is awesome and the big update was great. We just need a fix on the unkillable entity thing cuz.. Minecraft and entities and server tps is kinda a whole thing and always has been lol

**Comment by wrincewind** [comment]
I'm chiming in to report the same issue. Admittedly the only reason i have so many is because they're spawning in from my Delightful Dirt mob spawner from Mob Spawning Utilities, but i've got about 60 of them floating around my base and they're just not dying, even with the /kill command.

**Comment by all-yall** [comment]
It wasn't mentioned here, but a fix was done on the 7th to allow the lost souls to die to the `kill` command

**Comment by bradreslam** [comment]
I build a ghast farm in a soulsand valley and no ghasts are spawning at all. I deleted forbidden and arcanus and then it worked like a charm. I don't know if this is because of this issue but I thought I mention it anyway.

**Comment by vivabyte** [comment]
I'm having the same problem with Delightful Dirt mob spawner from Mob Spawning Utilities. I left this mob grinder set up running and ended up with probably over 100 of them flying around my base and my frame rate was down to like 5fps. This is in All the mods 9. So this has ruined my mob farm meaning ibaicaly can't use it. There might need to be a config for what mobs can spawn lost souls or a blacklist. Or something like 200 seconds despawn time. It is really annoying all together when I turn the farm on and I have 20 lost souls flying around annoying me and also they get stuck in the waterfall I have and constantly make suffocating sounds. Or maybe you could add a block with a radius to kill them or block them from Spawning. or something like a grave stone they are attracted to which makes them despawn.

**Comment by stal111** [comment]
Lost Souls no longer spawn in the Soul Sand Valley biome as of 1.21.1-2.5.8-beta
