### ISSUE TITLE
Hephaestus Forge needs to see the sky

### ISSUE THREAD

**Issue by faeldray** [stal111/Forbidden-Arcanus#355]
**Describe the bug**
The wiki entry for the Hephaestus Forge does not mention that the structure needs to see the sky. Took me a good while to figure out what I was doing wrong when I tried to build it underground.

**To Reproduce**
1. Build the Hephaestus Forge structure underground.
2. Use the Mundabitur Dust on the smithing table.
3. Nothing happens.

**Expected behavior**
Either the forge should still be created underground or the wiki should mention that it can't be created underground.

**Versions**
 - Forbidden & Arcanus: 1.19.2-2.7.0
 - Valhelsia Core: 1.19.2-0.5.0
 - Forge: 43.2.14

**Comment by stal111** [comment]
Normally the Forge does not need to have sky access. I've seen multiple people build them underground successfully.
Could you please join our Discord and share a screenshot of the not working underground structure?https://discord.com/invite/cwqwNx3TGE
