### ISSUE TITLE
Quantum Catcher Blaclist

### ISSUE THREAD

**Issue by norfaremc** [stal111/Forbidden-Arcanus#358]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

Please make a config feature so we can add our own mob blacklist. Right now there's a few mobs from other mods that cause crashes when you try to place catch them in a quantum catcher. Rather than having you do all this work, it would be easiest I think for all, especially server owners and modpack devs to just create their own blacklist, rather than you creating compatibility for every mod out there. Right now we know for sure that some Alex's Mobs crash the game as well as Human Companions. :)

**Comment by stal111** [comment]
Why need a config if there's already a tag that does exactly that? Simply add the crashing entities to `data/forbidden_arcanus/tags/entity_types/quantum_catcher_blacklisted.json` and you will no longer be able to catch them.

**Comment by norfaremc** [comment]
Oh I apologize, I never thought of that or knew about that. Thank you!! :)
