### ISSUE TITLE
Mob Spawners with Silk Touch no longer generate fragments [1.20.1]

### ISSUE THREAD

**Issue by immovably0** [stal111/Forbidden-Arcanus#359]
**Describe the bug**
In the latest version 1.20.1 of the Minecraft mod "Forbidden and Arcanus," it was during my own gaming experience that I discovered a notable issue. This problem concerns Mob Spawners and their interaction with the Silk Touch enchantment. In the past, breaking Mob Spawners with a tool enchanted with Silk Touch allowed players to collect valuable fragments as a result. However, this expected functionality has been disrupted. It appears that Mob Spawners no longer generate fragments when broken using a tool enchanted with Silk Touch.

**To Reproduce**
1. Access the latest version 1.20.1 of the Minecraft mod "Forbidden and Arcanus." (modpack : Valhelsia 6)
2. Progress through the game until encountering a Mob Spawner.
3. Utilize a tool enchanted with Silk Touch on the Mob Spawner.
4. Observe that the Mob Spawner no longer produces fragments as it did in previous versions.

**Expected behavior**
I anticipated that, based on the previous functionality, breaking a Mob Spawner with a tool enchanted with Silk Touch in the latest version 1.20.1 of the Minecraft mod "Forbidden and Arcanus" would result in the generation of valuable fragments.

**Screenshots**

**Versions**
 - Valhelsia 6: 6.0.0-beta_13
 - Forbidden & Arcanus: 1.20.1-2.2.0-beta1
 - Valhelsia Core: 1.20.1-1.1.0
 - Forge: 47.1.3

**Additional context**
N/A

**Comment by elpideus** [comment]
Same problem here. Waiting for a fix

**Comment by stal111** [comment]
Spawner Scraps once again drop in the latest 1.20.1 release.
