### ISSUE TITLE
[1.15.1] Latest version crashes on servers.

### ISSUE THREAD

**Issue by Gbergz** [stal111/Forbidden-Arcanus#36]
Title^

Forge Version: **30.0.41**
MC Version: **1.15.1**
Mod Version: **1.15.1-1.0-beta-4.jar**

**Crash-Report**: https://gist.github.com/Gbergz/1ad9cc118a396c4d96dc1b16769f7a7a

**Comment by ghost** [comment]
I have the same problem.

**Comment by stal111** [comment]
Should be fixed
