### ISSUE TITLE
[1.20.1] Harvesting spawner with EnderIO installed makes EnderIO drop 2 broken spawners instead of just one.

### ISSUE THREAD

**Issue by Gbergz** [stal111/Forbidden-Arcanus#360]
**Describe the bug**
Crossmod interaction bug:
Harvesting spawner with EnderIO installed makes EnderIO drop 2 broken spawners instead of just one.

**To Reproduce**
1. Install Forbidden and Arcanus 
2. Install EnderIO
3. Harvest a spawner
4. Two broken spawners drop instead of just one.
profit.

**Expected behavior**
That just one spawner drops from EnderIO

**Screenshots**
![screen](https://github.com/stal111/Forbidden-Arcanus/assets/26634554/ac4e1dbe-486c-455b-aa97-af28bc167bec)

**Versions**
 - Forbidden & Arcanus: 2.2.0
 - Valhelsia Core: 1.1.1
 - EnderIO: 6.0.18-alpha
 - Forge: 47.1.3

**Additional context**
Additional mods used: EnderIO, to reproduce the issue.
Removing Forbidden and Arcanus fixes the issue.

Also downgrading Forbidden and Arcanus to `v2.2.0-beta1` & Valhelsia Core to `v1.1.0` also "fixes" the issue. 
Although now no Spawner Scrap drops from Forbidden and Arcanus anymore.

**Comment by stal111** [comment]
Please also report this on the EnderIO github. It's likely that the issue lies on their side.

**Comment by Rover656** [comment]
I've left some commentary on the Ender IO repo for this issue - I have reason to believe this is on the Forbidden and Arcanus side, as opposed to our side, but would appreciate a second opinion :) https://github.com/Team-EnderIO/EnderIO/issues/513#issuecomment-2093801980

**Comment by HeroBrianMack** [comment]
Hi there everyone, I have confirmed the issue lies in how this mod programmed its loot table modifiers, I'm looking into fixing this right now.

**Comment by stal111** [comment]
This should have been fixed in the 1.21 version of the f&a.
