### ISSUE TITLE
[1.19.2] [Server-side] Hephaestus Forge assembling issue

### ISSUE THREAD

**Issue by Igneaalis** [stal111/Forbidden-Arcanus#361]
**Versions**
 - Forbidden & Arcanus: 1.19.2-2.1.3
 - Valhelsia Core: 1.19.2-0.5.0
 - Forge: 1.19.2-43.2.21

**All mods list**

- ad_astra-forge-1.19.2-1.12.7
- Ad-Astra-Giselle-Addon-forge-1.19.2-1.16
- Applied-Botanics-1.4.2
- appliedenergistics2-forge-12.9.5
- architectury-6.5.85-forge
- ars_creo-1.19.2-3.2.1
- ars_nouveau-1.19.2-3.17.5
- AutoRegLib-1.8.2-55
- badpackets-forge-0.2.1
- biomancy-forge-1.19.2-2.1.11.3
- block_log-1.0.0-1.19.2
- Botania-1.19.2-440-FORGE
- BotanicalMachinery-1.19.2-2.0.2
- botarium-forge-1.19.2-1.8.2
- buildinggadgets-3.16.2-build.22+mc1.19.2
- bwncr-forge-1.19.2-3.14.1
- caelus-forge-1.19.2-3.0.0.6
- cccbridge-mc1.19.2-forge-v1.5.1
- cc-tweaked-1.19.2-1.101.3
- cfm-7.0.0-pre35-1.19.2
- cgm-1.3.4-1.19.2
- ChickenChunks-1.19.2-2.9.4.97-universal
- cloth-config-8.2.88-forge
- CodeChickenLib-1.19.2-4.3.1.481-universal
- CorgiLib-forge-1.19.2-1.0.0.34
- CosmeticArmorReworked-1.19.2-v1a
- CraftTweaker-forge-1.19.2-10.1.46
- create-1.19.2-0.5.1.b
- createaddition-1.19.2-20230623a
- CreateTweaker-1.19.2-3.0.0.6
- Cucumber-1.19.2-6.0.7
- curios-forge-1.19.2-5.1.4.1
- dankstorage-1.19.2-5.1.6
- DivineRPG-1.9.6.9
- dragonmounts-1.19.2-1.1.4a
- DragonSurvival-1.19.2-1.5.56
- DungeonsArise-1.19.2-2.1.54-release
- EnigmaticLegacy-2.26.5
- ExtendedCrafting-1.19.2-5.1.6
- FarmersDelight-1.19-1.2.1
- FluxNetworks-1.19.2-7.1.4.13
- forbidden_arcanus-1.19.2-2.1.3
- foregoing_tweaker-1.19.2-1.1.5
- framework-0.4.2-1.19.2
- ftb-library-forge-1902.3.19-build.214
- ftb-quests-forge-1902.4.17-build.240
- ftb-teams-forge-1902.2.14-build.123
- geckolib-forge-1.19-3.1.40
- immersive_paintings-0.6.1+1.19.2-forge
- industrial-foregoing-1.19.2-3.3.2.3-5
- item-filters-forge-1902.2.9-build.51
- jei-1.19.2-forge-11.6.0.1016
- journeymap-1.19.2-5.9.7-forge
- LibX-1.19.2-4.2.8
- longerlogintimes-1.0.0-forge-mc1.19.2
- Mekanism-1.19.2-10.3.9.13
- MekanismAdditions-1.19.2-10.3.9.13
- MekanismGenerators-1.19.2-10.3.9.13
- MekanismTools-1.19.2-10.3.9.13
- moonlight-1.19.2-2.2.43-forge
- MouseTweaks-forge-mc1.19-2.23
- MythicBotany-1.19.2-3.0.2
- NethersDelight-1.19-3.0
- Oh_The_Biomes_You'll_Go-forge-1.19.2-2.0.1.4
- PackagedAuto-1.19.2-3.2.3.13
- PackagedExCrafting-1.19.2-3.2.1.9
- Patchouli-1.19.2-77
- pneumaticcraft-repressurized-1.19.2-4.3.6-27
- pneumaticcraft-repressurized-1.19.2-4.3.6-27-api
- Quark-3.4-405
- resourcefulconfig-forge-1.19.2-1.0.20
- resourcefullib-forge-1.19.2-1.1.24
- SandBox-1.19.2-1.0.1
- shutupexperimentalsettings-1.0.5
- SimpleDiscordRichPresence-forge-3.0.4-build.27+mc1.19.2
- simpleplanes-1.19.2-5.2.2
- supermartijn642configlib-1.1.7-forge-mc1.19
- supplementaries-1.19.2-2.3.20
- swingthroughgrass-1.19.2-1.10.0
- TerraBlender-forge-1.19.2-2.0.1.136
- titanium-1.19.2-3.7.3-27
- valhelsia_core-forge-1.19.2-0.5.0
- voicechat-forge-1.19.2-2.4.18
- wthit-forge-5.16.2

Hephaestus Forge can't be assembled on the server. But it does work in the singleplayer. We did the same thing multiple times, in the same world, in a different world. Only works in the singleplayer. Other mods are working great.

**Comment by stal111** [comment]
Please join our Discord server as it will be easier to figure out the cause there than here. 
https://discord.com/invite/cwqwNx3TGE
