### ISSUE TITLE
[1.19.2] compatability issues with create item drains and edelwood buckets

### ISSUE THREAD

**Issue by Lottie1s** [stal111/Forbidden-Arcanus#363]
**Describe the bug**
edelwood buckets filled with lava or water do not deposit their fluids into item drains at all. Edelwood milk buckets DO deposit the milk, but the item glitches and is replaced with a normal vanilla iron bucket. (survival only)

**To Reproduce**
1. go into creative mode and give yourself a few item drains, and an edelwood bucket of each fluid
2. set gamemode to survival and use the buckets on the item drain
3. the water and lava buckets don't empty and the milk bucket bugs out

**Expected behavior**
the buckets are supposed to empty their contents into the item drain and then either return to your inventory or drop on the ground depending on the method of use

**Screenshots**
https://streamable.com/8umqbd here's a streamable clip of the issue

**Versions**
 - Forbidden & Arcanus: 1.19.2  2.1.3
 - Valhelsia Core: 1.19.2  0.5.0
 - Forge: 1.19.2  43.2.21

**Additional context**
This could also be an issue with create but seeing as the bucket seems to the catalyst I think it's F&A

I have a bunch of other mods too so if you want me to disable them to replicate I can try to do that, too. thanks!

**Comment by stal111** [comment]
Please reopen if this is still an issue in 1.21.
