### ISSUE TITLE
No Aurum Saplings

### ISSUE THREAD

**Issue by Maltory** [stal111/Forbidden-Arcanus#364]
**Describe the bug**
Aurum Trees do not drop saplings in 1.20.1.  We have chopped down about 50 aurum trees but no saplings or gold nuggets dropped

**To Reproduce**
1. Go to flower forest biome and find aurum trees
2. cut down tree
3. See no drops besides logs

**Expected behavior**
Logs, Saplings, and gold nuggets should be dropping

**Screenshots**

**Versions**
 - Forbidden & Arcanus: 
 - Valhelsia Core: 6
 - Forge:

**Additional context**

**Comment by stal111** [comment]
Fixed in 1.20.1-2.2.1
