### ISSUE TITLE
Clibano Core refuses to be Broken + Visual "X-Ray" Glitch +Weird stuff happening

### ISSUE THREAD

**Issue by DarianStardust** [stal111/Forbidden-Arcanus#366]
**Describe the bug**
After making the multi-block structure "Clibano Core", Saving the game, Loading the same Save, and attempting to Break Any of the blocks that compose the Clibano Core, instead of the Multi-Block textures disappearing and the blocks separating, it stays together, the first block that was broken is placed again instantly,  the rest of the structure can be broken but turn invisible, if viewing the inside of the core it has an "X-Ray" effect as you can see the far away caves looking through it, those blocks can be broken with the exception of the first block, and the now existent Clibano core "Center", a block that spawns inside and isn't placed by the player, that also replaces itself when broken.

**To Reproduce**
1. Build the Multi-Structure Clibano Core, and use Mundabitur powder on the Core itself, Clibano Core is Ready
2. Save game, Re-enter the same save
3. Attempt to break the Clibano Core and see bizarre things happen

**Expected behavior**
The Multi-Structure to transform Back into separate blocks, and drop their blocks back (as the bug also deletes the blocks originally used)

**Screenshots**
![2023-09-23_10 49 34](https://github.com/stal111/Forbidden-Arcanus/assets/145576730/ff7e74f4-b073-4d1b-a855-3613ca3bb9a7)
![2023-09-23_14 59 46](https://github.com/stal111/Forbidden-Arcanus/assets/145576730/657fa96c-f0c3-4e84-ad5e-16085ac95cc9)

(Ignore the black textures, they are a a minor glitch with Rubidium 0.6.5)

**Versions**
 - Forbidden & Arcanus: 2.20
 - Valhelsia Core: 1.1.1
 - Forge: 47.1.43

**Additional context**
The first time I got this issue, I used a spell from Ars Nouveau to break the core, and it caused a crash, not sure why, it doesn't crash when using a pickaxe or this mod's Hammer, or even a simpler "Projectile>Break" spell from ars nouveau, I assume it's because since the Clibano core was already bugged, using other mod spells made the bug worse.

This is specially problematic as, if it in any way causes instability or save corruption then I have no way to remove this Multi-Block entity from my game, as it refuses to break, unless there are commands I could use to safely remove it

LOG 
[debug.log](https://github.com/stal111/Forbidden-Arcanus/files/12743410/debug.log)
[latest.log](https://github.com/stal111/Forbidden-Arcanus/files/12743411/latest.log)

PS: Pls buff this Clibano core thing, the effort made creating it really doesn't feel much rewarding, the  bonus ore gained from using it barely makes 1/3 of a stack, the Dark Souls seem to generate more bonus ores but those are **Annoying** to get, and I have no idea where enchanted souls are. a buff to the base values of Bonus ore, or a relic to boost the generated ore, please

**Comment by stal111** [comment]
Could you please attach the latest.log after this behavior happening? I'm sure I'll contain some error as to why the block didn't break correctly.

**Comment by DarianStardust** [comment]
> Could you please attach the latest.log after this behavior happening? I'm sure I'll contain some error as to why the block didn't break correctly.

Aye, will do soon enough, need to backup my save first, meanwhile, have you been able to reproduce the bug?

**Comment by DarianStardust** [comment]
> Could you please attach the latest.log after this behavior happening? I'm sure I'll contain some error as to why the block didn't break correctly.

Edited post, Logs sent

**Comment by stal111** [comment]
I think this should no longer be possible to happen in 1.21. If you still manage to get this crash please reopen the issue.

**Comment by Igneaalis** [comment]
Can someone backport it to 1.20.1?

**Comment by Igneaalis** [comment]
@stal111
