### ISSUE TITLE
[Bug][1.20.1] Orb of Temporary Flight does nothing when used.

### ISSUE THREAD

**Issue by grundyboy34** [stal111/Forbidden-Arcanus#367]
**Describe the bug**
Using the orb of temporary flight grants no buff and does not grant the ability to fly.

**To Reproduce**
1. Use orb of temporary flight
2. Double tap space, notice can't fly

**Expected behavior**
That you could fly for the buff time of orb of temporary flight

**Versions**
 - Forbidden & Arcanus: 1.20.1-2.2.0
 - Valhelsia Core: 1.20.1-1.1.1
 - Forge: 47.1.3

**Comment by all-yall** [comment]
In debugging, it looks like the `CounterProvider.CAPABILITY.isRegistered()` is false, and that there is no function to register it in Valhelsia Core `1.20.x` branch.

**Comment by stal111** [comment]
Yep, I didn't include it in 1.20 Valhelsia Core as the whole Counter system needs to be rewritten. It's on my todo list for once Neoforge releases the capability rework.

**Comment by stal111** [comment]
Closing this as the Orb of Temporary Flight got removed from f&a in the 1.21 version.
