### ISSUE TITLE
[Bug][1.20.1] Crash due to empty consequences list.

### ISSUE THREAD

**Issue by grundyboy34** [stal111/Forbidden-Arcanus#368]
**Describe the bug**
I've come across a rare crash, but it happens 100% of the time once it occurs, even if the server restarts.
The crash occurs at https://github.com/stal111/Forbidden-Arcanus/blob/1.20.x/src/main/java/com/stal111/forbidden_arcanus/common/aureal/consequence/Consequences.java#L41
with the fatal error `Bound must be positive`.
I'm guessing somehow the consequences arraylist is empty when this is called in this instance.

**To Reproduce**
Not sure

**Expected behavior**
Not to crash.

**Work around**
Disable corruption consequences in the config for now

**Versions**
 - Forbidden & Arcanus: 1.20.1-2.2.0
 - Valhelsia Core: 1.20.1-1.1.1
 - Forge: 47.1.3

**Additional context**
Seems to have occurred while a player was exploring new chunks.

**Comment by stal111** [comment]
Fixed in 1.20.1-2.2.1
