### ISSUE TITLE
Ancient debris dupe with Gavel

### ISSUE THREAD

**Issue by Manwe03** [stal111/Forbidden-Arcanus#369]
**Describe the bug**
The gavel alows you to get infinite ancient debris

**To Reproduce**
1. Make the gavel and find one ancient debris
2. Place the ancient debris
3. Break the ancient debris
4. Repeat 2 and 3

**Expected behavior**
To have the possibility of doubling ancient debris only when naturally generated not ones placed by players

**Versions**
 - Forbidden & Arcanus: 1.19.2-2.1.3
 - Valhelsia Core: 1.19.2-0.5.0
 - Forge: 43.2.14

**Comment by stal111** [comment]
Fixed in 1.19.2 and 1.20.1 now.
