### ISSUE TITLE
Game Crashes on Mod entity death

### ISSUE THREAD

**Issue by Attemiff** [stal111/Forbidden-Arcanus#370]
Game crashes when I shoot a Herobrined Sheep with a bow (Doesn't crash when other weapons are used or when kill commands are used, I've updated the mod and this continues to happen. I thought it was an issue with the end of herobrine mod, but the crash log seems to be focused on this one)

**To Reproduce**
1. Summon End of Herobrine Sheep
2. Kill it a few times so it duplicates
3. Run away and try to shoot it with a bow
4. Weep as your game crashes

**Expected behavior**
Game should continue to run with sheep duplicating or just dying.

**Screenshots**
N/A

**Versions**
 - Forbidden & Arcanus: 1.20.1-2.2.0
 - Valhelsia Core: 1.20.1-1.1.1
 - Forge: 47.1.44

**Additional context**
Removed Rubidium and Occulus and updated other mods, and deleted config file. Problem still persists.
[crash-2023-09-30_09.34.28-server.txt](https://github.com/stal111/Forbidden-Arcanus/files/12775050/crash-2023-09-30_09.34.28-server.txt)

**Comment by stal111** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [#370 Game can crash on Entity Death](https://trello.com/c/zkEbLCPr/45-370-game-can-crash-on-entity-death)

**Comment by stal111** [comment]
This issue has the same cause as #368, thus I'm going to close this as a duplicate.
