### ISSUE TITLE
[1.20.1] Mixin injecting SynchedEntityData into entities not owned by Forbidden Arcanus is dangerous

### ISSUE THREAD

**Issue by TelepathicGrunt** [stal111/Forbidden-Arcanus#378]
Entity Data Accessors should only be ever set by the creator of the entity. Never added to by other mods.

The reason for this is because Entity Data Accessors are order dependent so if multiple mods tries to add these entity data accessors to mobs and on client, they run in a different order than the server did (because mod load order is not guaranteed), the client will get forcibly disconnected from server when the entity spawns.

Instead, this mixin part needs to be removed and migrated properly to a Forge Capability because capabilities were designed specifically for this use case of attaching data to arbitrary entities. It is safer for mods as the vanilla system is designed specifically only for vanilla and unsafe for mods. Then you would use your own packet to send the data to client when needed.

https://github.com/stal111/Forbidden-Arcanus/blob/579498a04d770872aba46f86438115421787f91f/src/main/java/com/stal111/forbidden_arcanus/core/mixin/SlimeMixin.java#L32

This is especially a problem in large modpacks where many mods are doing this. Example is TNPLimitless 7 where there's many mods injecting SynchedEntityData onto entities and are getting out of order due to mod load order. Which is causes a lot of reports of people getting disconnected from server due to: 
![image](https://github.com/stal111/Forbidden-Arcanus/assets/40846040/f2f84ffe-a637-4720-a008-d577ef6d8ac7)

**Comment by TelepathicGrunt** [comment]
Hmm. I think your data usage can be entirely serversided so you could simply just rid the synced data accessor and make it a normal field

**Comment by stal111** [comment]
I've decided to just remove the mixin for now. The whole Edelwood Bucket system is on my list to rewrite anyway.
