### ISSUE TITLE
Trees frequency

### ISSUE THREAD

**Issue by KaIiguIa** [stal111/Forbidden-Arcanus#38]
Hi, can You reduce fequency of spawning trees that this mod implements?

They are very common and this makes exploring less entertaining.

NOTE:
->Minecraft version: 1.14.4
->Biomes O' Plenty on version: 1.14.4-9.0.0.262
->Forge version: 28.1.106

**Comment by stal111** [comment]
You probably mean especially the Cherrywood Trees? Because Mysterywood is pretty rare and to get Edelwood you need to find a Dark Forest Biome

**Comment by KaIiguIa** [comment]
Yes, I mean the Cherrywood Trees.

**Comment by stal111** [comment]
Reduced the Cherrywood spawning frequency a bit in forbidden_arcanus-1.15.2-1.0. It still generates pretty often but I dont want to make it to rare as it's meant to be very common
