### ISSUE TITLE
Forge 1.20.1, Edelwood Ladder isn't climbable.

### ISSUE THREAD

**Issue by katubug** [stal111/Forbidden-Arcanus#382]
**Describe the bug**
The Edelwood Ladder is not climbable.

**To Reproduce**
1. Place ladders
2. Attempt to climb them

**Expected behavior**
I expect to go up and/or down

**Versions**
 - Forbidden & Arcanus: 2.2.4
 - Valhelsia Core: 1.1.1
 - Forge: 47.2.17

**Additional context**
I did see this issue: https://github.com/stal111/Forbidden-Arcanus/issues/152

But it's very old, so I decided to make a new thread.

**Comment by Ciyuzuna** [comment]
I'm also having this problem on a fresh install with no other mods.
I've also tried several older versions of F&A.

The Edelwood Ladder does not work

**Comment by stal111** [comment]
Fixed in v1.20.1-2.2.5
