### ISSUE TITLE
Black Hole giving nothing

### ISSUE THREAD

**Issue by whyleviathan** [stal111/Forbidden-Arcanus#385]
**Describe the bug**
I feed the black hole with stacks and stacks of gold, gold nuggets, rotten flesh, etc. Since i have a farm and i got too many resources but the hole is not dropping any xpetrified orb.

**Expected behavior**
He should drop at least one xpetrified orb .-. (He's a good trash can tho ngl)

**Versions**
 - Forbidden & Arcanus: 1.19.2 - 2.1.5
 - Valhelsia Core: 0.5.0
 - Forge: 43.3.5

**Comment by bradreslam** [comment]
The wiki say's that you need to drop in xp not items for the black hole to spit out xpetrified orbs.

**Comment by stal111** [comment]
Yes, it requires experience.

**Comment by peterromfeldhk** [comment]
so how do you feed it XP?

edit: you throw the bottle o enchanting with right click and NOT with "alt+q"
