### ISSUE TITLE
[1.20.1] Arcane Crystal Block doesn't drop when mined

### ISSUE THREAD

**Issue by jinkhya** [stal111/Forbidden-Arcanus#386]
**Describe the bug**
Arcane Crystal Block doesn't drop when mined, I tried with different pickaxes and nothing.

**To Reproduce**
1. Make an instance with F&A and Valhelsia core
2. place down arcane crystal block
3. try to mine it with any pickaxe

**Expected behavior**
For the block to drop :)

**Screenshots**

**Versions**
 - Forbidden & Arcanus: 2.2.4
 - Valhelsia Core: 1.1.1
 - Forge: 47.2.16

**Additional context**

**Comment by stal111** [comment]
Fixed in v1.20.1-2.2.5
