### ISSUE TITLE
GTCEU & Eternal Stella Compatibility Feature Request

### ISSUE THREAD

**Issue by Ghostipedia** [stal111/Forbidden-Arcanus#387]
**Is your feature request related to a problem? Please describe.**
**YES**
GregTech:Modern has Recently released a tool refactor which Makes the eternal stella incompatible with most of their tools, and It would be amazing to see Stella support added for their toolsets

**Describe the solution you'd like**
Presently the Eternal Stella only applies visually to tools (Naming them Eternal, Giving a nice border, etc) But doesn't actually restore/keep the durability Maximum

**Describe alternatives you've considered**
Worst Case, when adding an eternal Stella to a GT Tool, it sets the unbreakable flag, as they do that with tools made of "Neutronium," which would also resolve this issue.

**Additional context**
Some screens of NBT between a Compressed Iron Chestplate (Which works with the Stella) and a Steel hammer (Which does not)
![image](https://github.com/stal111/Forbidden-Arcanus/assets/46772882/06d6c233-8263-424a-b71c-fefc190ab872)

**Comment by mikerooni** [comment]
Imo, setting the unbreakable tag automatically when applying Eternal Stella would be best indeed.  
Doing so wouldn't require any additional compatibility changes for each individual mod, as that is a vanilla feature already and can just be hooked into.

For GTCEu Modern specifically, we can't use Minecraft's regular durability system unfortunately, as we need two independent durability values used for separate purposes. We do, however, respect the unbreakable tag.

**Comment by stal111** [comment]
I think the Eterna Stella should be compatible with it in the 1.21 version now.
