### ISSUE TITLE
Hephaestus Forge automation

### ISSUE THREAD

**Issue by JWTHDYTWA** [stal111/Forbidden-Arcanus#389]
Pls add some way to automate the main `Hephaestus Forge` block I/O.

Now it's completely not-automatible. Machines don't see its inventory at all.

It would be great if `Ferrognetic Mixture` could be applied to the Forge itself. As an option, as one of the 4 upgrades.
It could also throw the ritual output as an item entity which is to be collected by some item collector.

**Comment by stal111** [comment]
What exact version are you playing? I've seen people fully automate it with other mods on the newest release.

**Comment by JWTHDYTWA** [comment]
I'm playing on 2.2.0-beta1. I've seen them too, but it was quite long time ago.
Also I'm playing on TNP Limitless 7 modpack.
People mostly use `Integrated Dynamics` because it has precise control over which slot the item is pushed to. But there's no ID on LL7.

**Comment by stal111** [comment]
That version is heavily outdated. It's fully possible to automate the forge on the latest 1.20 release.

**Comment by JWTHDYTWA** [comment]
Really. Seems like curseforge auto-update doesn't switch between **beta** and **release** versions of mods...
