### ISSUE TITLE
Orb of Temporary Flight breaks if you activate with slow falling

### ISSUE THREAD

**Issue by RagingEnby** [stal111/Forbidden-Arcanus#390]
**Describe the bug**
If you use an Orb of Temporary Flight with the slow falling effect, you do not gain flight.

**To Reproduce**
1. Gain slow falling (I personally did this using the Vault book from Ars Nouveau
2. Use an orb of temporary flight
3. It does not give you flight

**Expected behavior**
You gain flight for 5 minutes

**Screenshots**

**Versions**
 - Forbidden & Arcanus: 1.20.1-2.2.4
 - Valhelsia Core: 1.1.1
 - Forge: 1.20.1-forge-47.2.20

**Additional context**

**Comment by stal111** [comment]
Closing this as the Orb of Temporary Flight got removed from f&a in the 1.21 version.
