### ISSUE TITLE
Slimec pickaxe doesn't work as a silk touch item anymore (1.20.1)

### ISSUE THREAD

**Issue by ZephyrWindSpirit** [stal111/Forbidden-Arcanus#395]
**Describe the bug**
The slimec pickaxe, previously described as a built in silk touch item, no longer breaks blocks with silk touch. 

**To Reproduce**
1. Create/give yourself a slimec pickaxe.
2. Mine block (grass, stone, spawner)
3. Get block (dirt, cobblestone, spawner scrap)

**Expected behavior**
Expected to have a spawner drop when mining a zombie spawner out of my mob grinder when breaking it with the slimec pickaxe. Not a scrap. 

**Screenshots**

**Versions**
 - Forbidden & Arcanus: 1.20.1-2.2.4
 - Valhelsia Core: 1.20.1-1.1.1
 - Forge: 47.2.20

**Additional context**

**Comment by HeroBrianMack** [comment]
Did you cheat the item in, as it seems to be functional, excluding spawners, after being crafted in the version I'm using (although it is 2.2.6).
Or has the item's functionality been restored?

**Comment by stal111** [comment]
The Slimec Pickaxe was removed in the 1.21 version of the mod. Fixing this in older versions is currently not planned.
