### ISSUE TITLE
fill the test tube

### ISSUE THREAD

**Issue by sphinxnine9** [stal111/Forbidden-Arcanus#396]
**Describe the bug**
you can fill the test tube with the training dummy

**To Reproduce**
2. Use 'the mystical dagger' on 'training dummy with on you an test tube'
3. it's fillng the test tube

**Expected behavior**
it's not supposted to fill the test tube

**Screenshots**

**Versions**
 - Forbidden & Arcanus: on 1.18.2
 - Valhelsia Core: idk
 - Forge: dik

**Additional context**

**Comment by stal111** [comment]
We don't support 1.18.2 anymore. Please verify if this bug is also in the 1.20.1 version and update the issue accordingly. If not I'll close this issue in a few days.

**Comment by sphinxnine9** [comment]
Hi, after testing it's also work on 1.20.1. Have a good day

**Comment by HeroBrianMack** [comment]
What exactly is the training dummy?

**Comment by stal111** [comment]
A test_tube_blacklisted.json entity tag was added in version 2.5.6-beta for 1.21.1.You can add the training dummy to that tag to prevent it from filling test tubes.
