### ISSUE TITLE
New Problem

### ISSUE THREAD

**Issue by nodamnusername** [stal111/Forbidden-Arcanus#397]
com.electronwill.nightconfig.core.io.ParsingException:Not enough data available

**Comment by nodamnusername** [comment]
![image](https://github.com/stal111/Forbidden-Arcanus/assets/157940005/3518c27b-7fd1-4487-bb24-5d66c17fb9ff)

**Comment by stal111** [comment]
The config file seems to be corrupted. Simply deleting it should fix this. If you still have issues, please join our Discord Server as this is not the right place for basic support.
