### ISSUE TITLE
[1.14.2] (Forge) - The Arcane Gold helmet is labeled as Obsidian Helmet and Vice Versa

### ISSUE THREAD

**Issue by ghost** [stal111/Forbidden-Arcanus#4]
The Arcane Gold Helmet shows as the Obsidian Helmet and the Obsidian as the Arcane Gold.

MC Version: 1.14.2
Forge Version:  26.0.43
Forbidden Arcanus Version: 1.14.2-1.0-Beta-3 

![2019-06-22_09 46 11](https://user-images.githubusercontent.com/51269679/59965413-3cc40380-94d3-11e9-890a-93919904172e.png)

![2019-06-22_09 46 13](https://user-images.githubusercontent.com/51269679/59965414-3cc40380-94d3-11e9-8f6c-c3825f51c131.png)

**Comment by stal111** [comment]
Fixed in forbidden_arcanus-1.14.3-1.0-Beta-1
