### ISSUE TITLE
Edelwood Lava Bucket with Permafrost enchant

### ISSUE THREAD

**Issue by Quu1337** [stal111/Forbidden-Arcanus#40]
Place lava, pick lava up, crash server.

1.15.1
1.0-beta-5

**Comment by Quu1337** [comment]
Also crashes server with picking up water.

**Comment by stal111** [comment]
I would need the crash log in order to fix it

**Comment by Quu1337** [comment]
https://pastebin.com/W74a9vae

hacked into mainframe to get logs from server i dont own.
is this enough or do you need logs also?

**Comment by Quu1337** [comment]
Apparently picking up liquids works now, but crafting the buckets crashes?

1.15.2
1.0-beta-3

https://pastebin.com/BhRZ6y81

**Comment by stal111** [comment]
Should all be fixed now :)
