### ISSUE TITLE
1.20.1 Hephaestus Forge in 1.19.2 would be awesome.

### ISSUE THREAD

**Issue by SGZ-Creations** [stal111/Forbidden-Arcanus#400]
**Is your feature request related to a problem? Please describe.**
I'm always sad and disappointed when the 1.20.1 features of the Hephaestus Forge don't get ported to 1.19.2 :(

**Describe the solution you'd like**
Have the functions ported 

**Describe alternatives you've considered**
Non

**Additional context**
Really want the multi tier Forge for my 1.19.2 modpack

**Comment by stal111** [comment]
I agree that it would be nice, however, I don't have the time to backport features.
