### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by DelviousCrafts** [stal111/Forbidden-Arcanus#403]
**Describe the bug**
Game crashes with latest version of Valhelsia Core

**To Reproduce**
1. Update Valhelsia core to version 1.1.2
2. launch game
3. crash

**Expected behavior**
For the game not to crash

**Versions**
 - Forbidden & Arcanus: 2.2.5
 - Valhelsia Core: 1.1.2
 - Forge: 47.2.20
 - Minecraft: 1.20.1

**Additional context**
[Crash Report](https://gist.github.com/DelviousCrafts/7b90803e1084dfd8a62ab86aec638b14)

**Comment by uhloin** [comment]
+1
upgrade Valhelsia Core from 1.1.1 to 1.1.2 generates crush

[crash-2024-03-17_23.06.06-client.txt](https://github.com/stal111/Forbidden-Arcanus/files/14628604/crash-2024-03-17_23.06.06-client.txt)

**Comment by micmou** [comment]
Another +1
Upgraded Valhelsia Core to 1.1.2 and the mod took exception to that.

**Comment by suerion** [comment]
Same Issue here

**Comment by katubug** [comment]
Also same issue

**Comment by kendofriendo** [comment]
[Here's my crash log as well, using much fewer mods.](https://mclo.gs/GgfvkX2)

**Comment by MrCatlio** [comment]
try downgrading the Valhelsia Core mod since the latest version of the mod cause forbidden & arcanus to crash on start-up

**Comment by stal111** [comment]
Just downgrade Valhelsia Core for now. Fix should be coming out either later today or tomorrow.

**Comment by stal111** [comment]
Fixed now in the newest release.
