### ISSUE TITLE
Obsidian Skull, Eternal Obsidian Skull and Obsidian Skull Shield broken

### ISSUE THREAD

**Issue by etherealgears** [stal111/Forbidden-Arcanus#407]
**Describe the bug**
The Obsidian Skull and Obsidian Skull shield's fire immunity counters never start ticking down, but remain stuck at 30 seconds, meaning they give you endless fire immunity. In addition, both the Obsidian Skull Shield and the Eternal Obsidian Skull are uncraftable, and the texture for the Obsidian Skull shield is broken, it's just black with a purple handle.

**To Reproduce**
1. Launch the game with F&A installed.
2. Equip Obsidian Skull or Obsidian Skull Shield and start taking fire damage
3. Fire damage timer remains stuck at 30 seconds, never starts ticking down.

**Expected behavior**
Fire damage timer should tick down and Obsidian Skull Shield and Eternal Obsidian Skull should be craftable.

**Screenshots**

**Versions**
 - Forbidden & Arcanus: 1.20.1-2.2.6
 - Valhelsia Core: 1.20.1-1.1.2
 - Forge: 47.2.23

**Additional context**

**Comment by HeroBrianMack** [comment]
I've been working on this, but is there meant to be a recharge time or not, as I've fixed the counter not ticking down.

**Comment by stal111** [comment]
This has been fixed in the 1.21 versions of the mod.
