### ISSUE TITLE
Suggestion: Dimension config for world gen

### ISSUE THREAD

**Issue by Yamza** [stal111/Forbidden-Arcanus#41]
Would it be possible to have the oregen spawn in a specific dimension set by the config? Reason being, I want to be able to set magic mod items into their own dimension and not in the overworld.

 I see you have the trees set to specific biomes. If possible can that be configurable also?

**Comment by Yamza** [comment]
Would it be possible to at least be able to disable default ore generation?

**Comment by stal111** [comment]
You can already disable the generation of ores in the config

**Comment by stal111** [comment]
Dimension config options for world gen have been added now in version 16.2.0.
