### ISSUE TITLE
[1.20.1] Game Crash after hovering over the Tier of HF - JEI recipe of the Hephaestus Forge

### ISSUE THREAD

**Issue by ReeCodes** [stal111/Forbidden-Arcanus#411]
**Describe the bug**
Hovering over any of the JEI recipes from the Hephaestus Forge Tier part crashes the game

**To Reproduce**
1. Open your inventory inside your world.
2. Hover over the bottom line/right tier part of any JEI recipe of the Hephaestus Forge.
3. Crash.

**Expected behavior**
Show the required

**Screenshots**
![image](https://github.com/stal111/Forbidden-Arcanus/assets/50622547/35c08921-cc78-4be9-9b7e-c426b317df5c)

**Versions**
 - Forbidden & Arcanus: forbidden_arcanus-1.20.1-2.2.6
 - Valhelsia Core: valhelsia_core-forge-1.20.1-1.1.2
 - Forge: 47.2.32

**Additional context**
Log: https://mclo.gs/fuXjbyo

**Comment by parmleyhunt** [comment]
I was having this same issue however if you follow the Stacktrace the method that actually caused the out of bounds has the coldsweat mods namespace. Leading me to believe it is actually ColdSweat causing the crash and not forbidden. I have since removed ColdSweat and have no longer experienced this crash.

**Comment by HeroBrianMack** [comment]
Hello I'm trying to replicate this issue, what version of JEI were you using?
@ReeCodes 
I also agree with parmley based on your logs it wasn't Forbidden & Arcanus by itself that caused this crash

**Comment by IJuanTM** [comment]
You can disable Advanced Tooltips using F3+H, that stops the crashing for me.

**Comment by stal111** [comment]
Please report this on the ColdSweat GitHub if you haven't already.
