### ISSUE TITLE
Missing required datapack registries

### ISSUE THREAD

**Issue by Caffeinatedrat1** [stal111/Forbidden-Arcanus#412]
**Describe the bug**
Upon attempting to connect to my minecraft server, which has the mod installed on it- I recieve the error message 
"Failed to connect to the server 
Missing required datapack registries: forbidden_arcanus:hephaestus_forge/input, forbidden_arcanus:hephaestus_forge/ritual, forbidden_arcanus:enhancer/definition"

**To Reproduce**
1. Click multiplayer
2. Attempt to connect to the server
3. See error message

**Expected behavior**
I expected to connect to the server, and be able to play minecraft.

**Screenshots**
![Minecraft__Forge_Loading _22_05_2024_13_22_34](https://github.com/stal111/Forbidden-Arcanus/assets/170529768/787826d2-274e-47ab-b452-ee8b33b87b42)

**Versions**
 - Forbidden & Arcanus: 1.20.1-2.2.6
 - Valhelsia Core: 1.20.1-1.1.2
 - Forge: 47.2.0

**Additional context**
I am using a curseforge modpack I made myself. The pack worked fine until adding forbidden and arcanus, could be a mod conflict?
[guh.zip](https://github.com/stal111/Forbidden-Arcanus/files/15403338/guh.zip)

**Comment by PUrE-elF** [comment]
I have got the same issue. How did it fixed?
