### ISSUE TITLE
Can't remove eternal stella recipe through datapack

### ISSUE THREAD

**Issue by ivxvm** [stal111/Forbidden-Arcanus#415]
**Describe the bug**
I tried removing/modifying eternal stella recipe by using traditional method of placing a changed file here:
`data/forbidden_arcanus/forbidden_arcanus/hephaestus_forge/ritual/eternal_stella.json`

**To Reproduce**
Place file containing "{}" or changed recipe here:
`data/forbidden_arcanus/forbidden_arcanus/hephaestus_forge/ritual/eternal_stella.json`

**Expected behavior**
Hephaestus forge recipe should be changed or removed (if file has empty json object)

**Screenshots**

**Versions**
 - Forbidden & Arcanus: forbidden_arcanus-1.20.1-2.2.6
 - Valhelsia Core: valhelsia_core-forge-1.20.1-1.1.2
 - Forge: 47.2.20

**Additional context**

**Comment by Inteleonyx** [comment]
I had the same problem.

**Comment by stal111** [comment]
You can use the "filter" option in the pack.mcmeta to filter out files from other data packs.
See https://minecraft.wiki/w/Pack.mcmeta

**Comment by Shibva** [comment]
Can you please provide an example @stal111, ive been trying for hours but I cant seem to get the damn syntax right wtihout it breaking shit and unloading custom stuff
