### ISSUE TITLE
Add Information About 1.12 Version to Wiki

### ISSUE THREAD

**Issue by Bereim** [stal111/Forbidden-Arcanus#416]
**Is your feature request related to a problem? Please describe.**
The wiki lacks information, notably about the 1.12 version.

**Describe the solution you'd like**
Specific pages or categories on the wiki for version-specific functionality and items, such as:
- Corrupt Pixi
- Rotten Dragon Scale
- Leather of the Sea
- Cherry Peach
- Colored Feathers
- Sacred Scepter
- Battle Skull
- Runic Tenebris Frame/Core
- Ender Crystal Gem

**Describe alternatives you've considered**
I considered sifting through the source code to see what corrupted pixies do in 1.12, but I didn't see it as an option in the branch selection.

**Comment by stal111** [comment]
Not going to happen, 1.12.2 is heavily outdated by now. I don't even remember the features f&a had five years ago.
