### ISSUE TITLE
Quantum Catcher Locked to Entity: minecraft:pig

### ISSUE THREAD

**Issue by usersicon** [stal111/Forbidden-Arcanus#419]
I'm running forbidden_arcanus-1.20.1-2.2.6 with better minecraft 4 modpack and cobblemon modpack.
I installed forbidden & arcanus after creating the quantum catcher it has Minecraft pig locked to the catcher

ive tryed removing the mod and reinstalling it in both modpacks stated above by using forge successfully.  when i create a new quantum catcher the problem persists, having a pig already in the quantum catcher, in Creative and Survival.  ive updated Forbidden & Arcanus,  Valhelsia Core, forge to most recents.

Am i missing a required mod or why wont the quantum catch be empty? i can spawn infiniate pigs with on quantum catch even in a new survival world.

**Versions**
 - Forbidden & Arcanus: 1.20.1-2.2.6
 - Valhelsia Core: 1.20.1-1.1.2
 - Forge: 47.3.0

**Additional context**

**Comment by stal111** [comment]
I cannot reproduce this with just F&A. I guess it's some mod conflict.
