### ISSUE TITLE
'Doggy Talents' dogs are locked inside quantum catcher

### ISSUE THREAD

**Issue by Agret-Brisignr** [stal111/Forbidden-Arcanus#421]
**Describe the bug**
Entity: doggytalents:dog, once inside the quantum catcher, is unable to be released

**To Reproduce**
1. Convert a wolf into doggytalents:dog via training treat
2. Use a quantum catcher on entity doggytalents:dog
3. Attempt to release doggytalents:dog from catcher

**Expected behavior**
When attempting to release doggytalents:dog, the entity should be summoned

**Screenshots**
N/A

**Versions**
 - Forbidden & Arcanus: 1.19.2-2.1.5
 - Valhelsia Core: 1.19.2-0.5.0
 - Forge: 43.3.8

**Comment by HeroBrianMack** [comment]
This is also occurring in 1.20.1 with Doggy Talents Next

**Comment by HeroBrianMack** [comment]
Although the error is caused by Doggy Talents rather than this mod since they're not friendly with things holding the dogs.

**Comment by stal111** [comment]
Have you also reported this to the Doggy Talents GitHub? I guess we can't really do much on our side to fix this.
