### ISSUE TITLE
Mod crashes when searching in JEI/EMi

### ISSUE THREAD

**Issue by Saereth** [stal111/Forbidden-Arcanus#423]
**Describe the bug**
When searching "Ste" in JEI the mod causes the game to crash

**To Reproduce**
1. Install the mod and jei/emi
2. search ste
3. crash

**Expected behavior**
Not to crash

**Versions**
 - Forbidden & Arcanus: forbidden_arcanus-2.5.1-beta
 - Valhelsia Core: valhelsia_core-neoforge-1.21-1.1.3
 - NeoForge: 21.0.114

**Additional context**
Crashlog:
https://mclo.gs/muhCLWU

**Comment by stal111** [comment]
Fixed in 2.5.2-beta
