### ISSUE TITLE
[1.21-117NeoForge]too many error about this mod's Recipe

### ISSUE THREAD

**Issue by ootwclyhe** [stal111/Forbidden-Arcanus#424]
[latest.log](https://github.com/user-attachments/files/16356572/latest.log)

**Versions**
 - Forbidden & Arcanus: forbidden_arcanus-2.5.1-beta
 - Valhelsia Core: valhelsia_core-neoforge-1.21-1.1.3
 - NeoForge: neoforge-21.0.117-beta

**Comment by stal111** [comment]
Fixed in 1.21.1-2.5.4-beta
