### ISSUE TITLE
[1.21] Edelwood and Nipa dont spawn in worlds

### ISSUE THREAD

**Issue by CubeTwo** [stal111/Forbidden-Arcanus#425]
**Describe the bug**
Edelwood and Nipa dont spawn in worlds

**To Reproduce**
1.create world
2. search for Edelwood and Nipa
3. See error

**Expected behavior**
Edelwood and Nipa spawn in worlds

**Versions**
 - Forbidden & Arcanus:forbidden_arcanus-2.5.2-beta
 - Valhelsia Core:valhelsia_core-neoforge-1.21-1.1.3
 - Forge:NeoForge: 21.0.147

**Additional context**

**Comment by stal111** [comment]
Nipa has been removed in the latest release and Edelwood is intended to no longer generate in Dark Oak Forests. In order to get it you can use a Dark Soul on an Oak Sapling.
