### ISSUE TITLE
Missing Forge Tags

### ISSUE THREAD

**Issue by TheBedrockMaster** [stal111/Forbidden-Arcanus#426]
**Describe the solution you'd like**
Add the following item tags to the following items:

Runic Stone:
`forge:ores_in_ground/stone`
`forge:ores`

Runic Deepslate:
`forge:ores_in_ground/deepslate`
`forge:ores`

Runic Darkstone:
`forge:ores`

Xpetrified Ore:
`forge:ores_in_ground/stone`

Arcane Crystal Ore:
`forge:ores_in_ground/stone`

Deepslate Arcane Crystal Ore:
`forge:ores`
`forge:ores/arcane_crystal`
`forge:ores_in_ground/deepslate`

Stella Arcanum:
`forge:ores_in_ground/stone`

Deorum Glass:
`forge:glass`
`forge:glass/colorless` (Runic Glass has this tag)

Deorum Glass Pane:
`forge:glass_panes`
`forge:glass_panes/colorless`

Corrupted Arcane Crystal:
`forge:gems`

Deorum Nugget:
`forge:nuggets`

Aurum Boat:
`minecraft:boats`

Aurum Boat with Chest:
`minecraft:boats`
`minecraft:chest_boats`

Edelwood Boat:
`minecraft:boats`

Edelwood Boat with Chest:
`minecraft:boats`
`minecraft:chest_boats`

Corrupted Arcane Crystal Block:
`forge:storage_blocks`

Growing Edelwood:
`minecraft:saplings`

Fungyss:
`forge:mushrooms`

**Comment by stal111** [comment]
Fixed in 1.21.1-2.5.9
