### ISSUE TITLE
Obsidian Skull not Working

### ISSUE THREAD

**Issue by Megafoan** [stal111/Forbidden-Arcanus#427]
**Describe the bug**
The Obsidian Skull does not provide lava or fire immunity. I take damage from those sources while having it in my inventory, equipped as a helmet, or on my hot bar. I am playing Forbidden and Arcanus as part of the Valhelsia 6 modpack.

**To Reproduce**
1. Download the Valhelsia 6 modpack.
2. Acquire Obsidian Skull.
3. Attempt to use Obsidian Skull as intended.

**Expected behavior**
The Obsidian Skull would protect me from lava and fire damage for 30 seconds before going on cooldown.

**Screenshots**
I do not have a screenshot of the issue.

**Versions**
 - Forbidden & Arcanus: 1.20.1-2.2.6
 - Valhelsia Core: 1.20.1-1.1.2
 - Forge: 47.3.5

**Additional context**
I have not tested the issue with just Forbidden and Arcanus or as part of other modpacks aside from Valhelsia 6.

**Comment by stal111** [comment]
Are you sure that you're actually taking damage? With the Obsidian Skull in your inventory you won't lose hearts but still hear the damage sound.

**Comment by Megafoan** [comment]
I was unaware of this fact. Further testing shows that I am not, in fact, taking damage, although I will note that the timer still doesn't count down and my armor does, in fact, take damage.
