### ISSUE TITLE
Obsidian skull shield missing textures

### ISSUE THREAD

**Issue by polykatt** [stal111/Forbidden-Arcanus#428]
The obsidian skull shield has missing textures. Minecraft version 1.20.1, Forge 47.3.0, Valhelsia Core 1.1.2, Forbidden and Arcanus 2.2.6
![2024-08-19_07 53 52](https://github.com/user-attachments/assets/6381a953-5d3f-4325-a51c-cad3f6fbf1a0)
![2024-08-19_07 53 30](https://github.com/user-attachments/assets/d790416d-0d35-4b40-957d-9cd16b80aeea)

**Comment by stal111** [comment]
The Obsidian Skull Shield has been removed in 1.21, a fix for this in 1.20.1 is currently not planned.
