### ISSUE TITLE
[Question] Update backport to 1.20.1?

### ISSUE THREAD

**Issue by Luningor** [stal111/Forbidden-Arcanus#429]
As stated. Will the mod still update for 1.20.1 after the betas end?
I'm kinda worried I'll be missing out on features on future updates, as this mod is a core feature in a modpack of mine.

**Comment by stal111** [comment]
Currently not planned. Biggest reason is that my available time is currently relative low and the changes between minecraft 1.20 and 1.21 are quite large meaning that backporting isn't as easy and straightforward.
Furthermore, the goal of v2.5 is to overhaul most of the existing content, remove unused items, and in general to create a better base for future content. I don't think making such drastic changes on a version that is considered stable by now for pack creators is a good idea.
