### ISSUE TITLE
error

### ISSUE THREAD

**Issue by howthefudoiplayflameoutonmobile** [stal111/Forbidden-Arcanus#430]
I get this error:
Forbidden Arcanus cforbidden_arcanus) encountered an error while dispatching the net.neoforged.neoforge.event.entity.EntitynttributeCreationEvent event
I use neoforge 1.21
![Screenshot_20240914_141303_PojavLauncher (Minecraft Java Edition for Android)](https://github.com/user-attachments/assets/6238806d-73e5-4e5c-bff8-13d78d5317aa)

**Comment by stal111** [comment]
What NeoForge version are you using? My guess is that you need to use a newer one.
