### ISSUE TITLE
[1.21.1] There is no Arcane Chiseled Polished Darkstone

### ISSUE THREAD

**Issue by JWTHDYTWA** [stal111/Forbidden-Arcanus#431]
In the last version for 1.21.1 there is no `Arcane Chiseled Polished Darkstone`. There is a block named `Gilded Chiseled Polished Darkstone` with the same texture, but it's not craftable. At least not shown in JEI. There is also no guide book in this version. So I can't build Hephaestus Forge.

**Screenshots**
![изображение](https://github.com/user-attachments/assets/895fbc80-e225-48bc-9bf2-02a0ea122ac6)
No recipes for `Gilded Chiseled Polished Darkstone` but this:
![изображение](https://github.com/user-attachments/assets/38ff54e1-d1be-44dd-b463-a51f62cd330b)

**Versions**
 - Forbidden & Arcanus: `1.21.1-2.5.3-beta`
 - Valhelsia Core: `neoforge-1.21-1.1.3`
 - Neoforge: `21.1.50`

**Comment by stal111** [comment]
The block got renamed to Gilded Chiseled Polished Darkstone in 1.21. 
The missing recipe is now available again in 1.21.1-2.5.4-beta.
