### ISSUE TITLE
Too hard to figure out

### ISSUE THREAD

**Issue by akitasiffu** [stal111/Forbidden-Arcanus#432]
Cisco's RPG pack doesn't have the quest line for forbidden and arcanus. Without a guide book I'm stuck at trying to upgrade the forge. I follow the wiki but it lacks in any viable information. Cisco's mod pack if for 1.19.2. I see a book is in the works and maybe Cisco himself altered your mod, but there is no info relevant to me anywhere. If i could atleast get a little more detail on how to upgrade the forge and yes i've looked at the guide and it doesn't explain well. Like the wiki says 500 arcanus, 10 souls, 6000 blood, and 3 xp lvl. The GUI on mine says my max limits are 200 arcanus, 1 soul, 5000 blood and 200 xp. SO im lost and frustrated.

**Comment by stal111** [comment]
The higher Hephaestus Forge tiers are only available starting in 1.19.4+.
