### ISSUE TITLE
Mod not using the C name space for Deorum Ingot on NeoForge 1.21.1

### ISSUE THREAD

**Issue by ModernGamingWorld** [stal111/Forbidden-Arcanus#433]
**Describe the bug**

**To Reproduce**
1. Go to 'JEI 
2. Check tags
3. See error

**Expected behavior**

I'm looking for a quick fix because NeoForge uses the c namespace in your mod. Your currently using forge:ingots/deoruum instead of c:ingots/deorum.

**Screenshots**

**Versions**
 - Forbidden & Arcanus: 1.21.1-2.5.4-beta.jar
 - Valhelsia Core: neoforge-1.21-1.1.3
 - Forge: Neoforge -21.1.57

**Additional context**

**Comment by TheBedrockMaster** [comment]
This should have been fixed.

**Comment by stal111** [comment]
Fixed in 1.21.1-2.5.9
