### ISSUE TITLE
Worldgen: no Xpetrified Ore and EdelWood

### ISSUE THREAD

**Issue by dennis6981** [stal111/Forbidden-Arcanus#434]
**Describe the bug**
Worldgen: no Xpetrified Ore and Edelwood.
Xpetrified Ore is also not shown in EMI. Only Xpetrified Orb

**Versions**
 - Forbidden & Arcanus: 1.21.1-2.5.4-beta
 - Valhelsia Core: [NeoForge] Valhelsia Core 1.1.3
 - Forge: Neoforge 21.1.61

**Comment by stal111** [comment]
This is intended. The way of obtaining Xpetrified Orbs through the Black Hole seems more interesting than having a xp ore. 
Edelwood can currently only be obtained through the Wandering Trader or by using a Dark Soul on an Oak Sapling.

**Comment by uhloin** [comment]
What is Dark Soul? There are only Souls and Corrupted Souls.
