### ISSUE TITLE
Aurum Leaves Missing Perffered Tool (Outside Sheers)

### ISSUE THREAD

**Issue by Brenilla** [stal111/Forbidden-Arcanus#435]
**Describe the bug**
When mining Aurum leaves there is no preferred tool outside sheers so mining with Hoes, Pickaxe, or empty handed is the same amount. 

**To Reproduce**
1. Get/find Aurum Leaves
2.  Try Mining with tool. (Hoe traditionally for leaves)
3. See error

**Expected behavior**
A Hoe should mine the leaves considerably faster and be effected by efficiency. (Or A pickaxe if you want the gold angle)

**Versions** (Sorry I am unfamiliar with what you are asking)
 - Forbidden & Arcanus: 1.21.1-2.5.4-beta
 - Valhelsia Core:
 - Forge: 1.20.1

**Comment by stal111** [comment]
Fixed in 1.21.1-2.5.9
