### ISSUE TITLE
Memory Leak of Client Level

### ISSUE THREAD

**Issue by pietro-lopes** [stal111/Forbidden-Arcanus#437]
https://github.com/stal111/Forbidden-Arcanus/blob/71ca3ee32206390795847d51d17a1b92e300fe35/src/main/java/com/stal111/forbidden_arcanus/client/ClientPayloadHandler.java#L35

Can you rework to not store level here, this is causing leak? replace `this.level` with `this.minecraft.level` and you will be fine

**Comment by stal111** [comment]
Thanks for pointing this out. Fixed in 2.5.5-beta.
