### ISSUE TITLE
Forbidden Arcanus Can't Load

### ISSUE THREAD

**Issue by ReaperOfShadows** [stal111/Forbidden-Arcanus#440]
Description of the Bug:

I've tried several methods now to get the mod to work, and it simply crashes on my end, i've made it to where it is the only mod Installed and it just crashes (yes Valhelsia core is installed.) :P

**To Reproduce**

Download these mods:

forbidden_arcanus-1.21.1-2.5.5-beta.jar           |Forbidden Arcanus             |forbidden_arcanus             |2.5.5-beta 
valhelsia_core-neoforge-1.21-1.1.2.jar            |Valhelsia Core                |valhelsia_core                |1.1.2
Neoforge version: 21.1.65 and/or 21.1.66

Start the game.

**Expected behavior**

Just an error screen with this message: java.lang.IllegalStateException: Registry entry for key ResourceKey[minecraft:entity_type / forbidden_arcanus:lost_soul] is not bound. 		

**Screenshots**
Tried and Failed

**Versions**
(all up above)
 - Forbidden & Arcanus:
 - Valhelsia Core:
 - Forge:

**Additional context**
Tried this with a multitude of mods and thought it was just an incompatibility but no, the mod just won't load.

**Comment by stal111** [comment]
Please update to Valhelsia Core 1.1.3, that should fix that issue.
