### ISSUE TITLE
Placing corrupted arcane crystal obelisk at the hephaestus forge multiblock crash the game

### ISSUE THREAD

**Issue by YocyCraft** [stal111/Forbidden-Arcanus#442]
**Describe the bug**
Placing it on other position don't crash the game.

**To Reproduce**
1. Build a hephaestus forge multiblock
2. Place a corrupted arcane crystal obelisk at any position of pedestals
3. Game crushed

**Expected behavior**
Game should not crash

**Screenshots**
Crash report: [](https://mclo.gs/ncL4n2B)

**Versions**
 - Forbidden & Arcanus: 1.21.1-2.5.5-beta
 - Valhelsia Core: 1.21-1.1.3
 - Forge: Neoforge 21.1.65

**Comment by stal111** [comment]
Please share the crash report.

Also what exactly are you trying to do with the corrupted obelisk? it's not fully implemented yet

**Comment by YocyCraft** [comment]
> Please share the crash report.
> 
> Also what exactly are you trying to do with the corrupted obelisk? it's not fully implemented yet

https://gist.github.com/YocyCraft/d108e82bf086c3a17cfea6bce0f978d7

**Comment by stal111** [comment]
Fixed in 1.21.1-2.5.8-beta
