### ISSUE TITLE
Cannot craft black dye from sac

### ISSUE THREAD

**Issue by uhloin** [stal111/Forbidden-Arcanus#445]
**To Reproduce**
Kill a squid, get a sac, try craft black dye -> impossible

**Versions**
 - Forbidden & Arcanus: forbidden_arcanus-1.21.1-2.5.7-beta.jar
 - Valhelsia Core: valhelsia_core-neoforge-1.21-1.1.3.jar 
 - Forge: neoforge-21.1.68-installer.jar

**Comment by stal111** [comment]
Fixed in 1.21.1-2.5.8-beta
