### ISSUE TITLE
Blacksmith Gavels do not show the tooltip with remaining uses

### ISSUE THREAD

**Issue by pr0saic** [stal111/Forbidden-Arcanus#446]
**Describe the bug**
Blacksmith Gavels do not show the tooltip with remaining uses

**To Reproduce**
Make a Blacksmith Gavel

**Expected behavior**
The tooltip to show remaining uses

**Screenshots**
![image](https://github.com/user-attachments/assets/4f28a1aa-d958-48ce-ad93-1fd3abae50ed)

**Versions**
 - Forbidden & Arcanus: 1.21.1-2.5.7
 - Valhelsia Core: 1.21-1.1.3
 - Neoforge: 21.1.72

**Additional context**
On modpack ATM10 v1.6

**Comment by stal111** [comment]
Fixed in 1.21.1-2.5.8-beta
