### ISSUE TITLE
Inventory Sorting places inventory items in UI

### ISSUE THREAD

**Issue by Column01** [stal111/Forbidden-Arcanus#452]
**Describe the bug**
When using a Inventory Tweaks Refoxed to sort your inventory while in any GUI from your mod, it will place your items in your UI. I have already reported this to the mod developer (see link below)

**To Reproduce**
1. Open any GUI with the Inventory Tweaks Refoxed (or maybe other inv sorter mods?)
2. Sort your inventory with some items in it
3. They get placed in the GUI of the block you are using

**Expected behavior**
I would like the items to not get placed in the UI when sorting my inventory

**Screenshots**
![image](https://github.com/user-attachments/assets/5692b9d8-8cdc-42b3-aa96-ac3735da5df2)

**Versions**
 - Forbidden & Arcanus: `2.5.9`
 - Valhelsia Core: `1.1.4`
 - NeoForge: `21.1.77`
 - Inventory Tweaks Refoxxed: `1.21.0-1.1.4`

**Additional context**
[Issue reported to inventory tweaks refoxxed also](https://github.com/JDKDigital/InvTweaksRefoxed/issues/19)

**Comment by stal111** [comment]
This seems to have been fixed by InventoryTweaksRefoxed.
