### ISSUE TITLE
**Minecraft Verison (1.16.5) Mod Issue Error Type: java.lang.NullPointerException**

### ISSUE THREAD

**Issue by bananacomputer** [stal111/Forbidden-Arcanus#455]
**Minecraft Verison (1.16.5) Mod Issue Error Type: java.lang.NullPointerException**
Cause:The crash happens in the Item.handler$bdg000$forbiddenArcanus_inventoryTick method.
This is likely from the Forbidden & Arcanus mod.

Ive Allocated 8GB of RAM of my 16GBs on my laptop

**To Reproduce**
Steps to reproduce the behavior: it happens to me everytime without fail
Download these mods in a new folder under 1.16.5 and try to reload any of the weapons
Mods:             Release Date:
Crafting Dead:Core
Crafting Dead:Survival
Forbidden and Arcanus
Valhesia Core

**Expected behavior**
When trying to reload or load any firearm from the crafting dead pack its causes a NPE
NullPointerException; But when I turn off Forbidden and Arcanus the weapon reloads without fail

**Screenshots**
![image](https://github.com/user-attachments/assets/85517242-5e53-4b25-a432-601c965d6ca4)
This is with F&A disabled
When I turn it on this is what i get in the crash log
[crash-2024-12-01_05.48.14-server.txt](https://github.com/user-attachments/files/17969549/crash-2024-12-01_05.48.14-server.txt)

**Versions**
 - Forbidden & Arcanus: 16.2.3
 - Valhelsia Core: 16.0.15
 - Forge: 36.2.42

**Additional context**
Im expanding my modpack and I was looking for incompatibilities in my mods and found this

**Comment by stal111** [comment]
Support for 1.16.5 has ended years ago. Please use a newer version of F&A.

**Comment by bananacomputer** [comment]
I Cant cause all of my mods would break do you at least have a suggestion on how to fix it?
