### ISSUE TITLE
Interaction with Forge

### ISSUE THREAD

**Issue by Teamerman** [stal111/Forbidden-Arcanus#456]
Interaction with the Forge

**To Reproduce**

Fill the pedestals with a recipe.
Put the Item in the middle like ATM Ingot/Darkstone
Network Protocol Error

**Expected behavior**

Not crash

**Screenshots**
Entangloporter resembles Item being put in
![Bild_2024-12-05_215858676](https://github.com/user-attachments/assets/9a35567e-7b79-43da-8be2-bae203e8f3df)

**Versions**
 - Forbidden & Arcanus: in ATM10 1.27

**Additional context**
And the Forge completely resets ressource wise. Forge Tier is still there

**Comment by stal111** [comment]
Should be fixed in version 2.5.11
