### ISSUE TITLE
Eternal Obsidian Skull not working in Create: Arcane Engineering

### ISSUE THREAD

**Issue by Dreadzillla** [stal111/Forbidden-Arcanus#457]
**Describe the bug**
The eternal obsidian skull is supposed to “grant complete immunity against fire damage” however in the modpack Create: Arcane Engineering it doesn’t negate any fire damage.

**To Reproduce**
1. Download and play the Create: Arcane Engineering modpack.
2. Create an Eternal Obsidian Skull.
3. Take fire damage (via lava, fire, magma block, blazes, etc) while holding Eternal Obsidian Skull in inventory.
4. Notice that fire damage is not blocked.

**Expected behavior**
All fire damage should be blocked by the Eternal Obsidian Skull from all sources of fire damage while the object is in the inventory.

**Screenshots**
N/A

**Versions**
 - Forbidden & Arcanus: 1.18.2 from 8/30/2023
 - Valhelsia Core: 1.18.2 from 7/20/2022
 - Forge: 40.2.9

**Additional context**
The Eternal Obsidian Skull worked well and as intended in the modpack Create: Above & Beyond, however has not worked in Create: Arcane Engineering for some time. It is not cheap to make in this modpack, so please fix this bug.

**Comment by stal111** [comment]
1.18.2 is heavily outdated by now, please only open issues for the latest version.
