### ISSUE TITLE
Catching a companion from the mod human companions on 1.20.1 with quantam catcher crashes the game

### ISSUE THREAD

**Issue by lSherozl** [stal111/Forbidden-Arcanus#458]
Just have this mod https://www.curseforge.com/minecraft/mc-mods/human-companions and catch a person in HC and leads to a crash. 
[12Dec2024 19:23:23.112] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: [ISherozI: Set own game mode to Creative Mode]
[12Dec2024 19:23:23.112] [Render thread/INFO] [net.minecraft.client.gui.components.ChatComponent/]: [CHAT] Set own game mode to Creative Mode
[12Dec2024 19:23:47.326] [Render thread/ERROR] [net.minecraftforge.eventbus.EventBus/EVENTBUS]: Exception caught during firing event: Saving entity NBT
	Index: 73
	Listeners:
		0: HIGHEST
		1: ASM: xaero.pac.common.event.CommonEventsForge@649ee3e4 onEntityInteract(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$EntityInteract;)V
		2: ASM: class com.github.tartaricacid.touhoulittlemaid.compat.domesticationinnovation.EnchantmentRefuse onInteractMaid(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$EntityInteract;)V
		3: ASM: class net.sodiumzh.nff.girls.eventlisteners.NFFGirlsEntityEventListeners onEntityInteract_PriorityHighest(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$EntityInteract;)V
		4: HIGH
		5: ASM: class tschipp.carryon.events.CommonEvents onEntityRightClick(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$EntityInteract;)V
		6: ASM: class net.sodiumzh.nff.girls.entity.vanillatrade.NFFGirlsTradeEventHandlers onMobInteract(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$EntityInteract;)V
		7: ASM: class dev.architectury.event.forge.EventHandlerImplCommon eventPlayerInteractEvent(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$EntityInteract;)V
		8: ASM: class com.simibubi.create.content.contraptions.minecart.MinecartCouplingItem handleInteractionWithMinecart(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$EntityInteract;)V
		9: NORMAL
		10: ASM: class net.gigabit101.shrink.events.PlayerEvents itemInteractionForEntity(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$EntityInteract;)V
		11: ASM: class net.mcreator.mgsecretsofmermaids.procedures.SitsetProcedure onRightClickEntity(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$EntityInteract;)V
		12: ASM: class cech12.extendedmushrooms.ExtendedMushrooms onEntityInteract(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$EntityInteract;)V
		13: net.minecraftforge.eventbus.EventBus$$Lambda$2104/0x0000000800a26d08@c3b4b27
		14: ASM: net.orcinus.galosphere.events.MobEvents@186a8d1c onRightClickEntity(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$EntityInteract;)V
		15: ASM: class com.klikli_dev.occultism.handlers.PlayerEventHandler onPlayerRightClickEntity(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$EntityInteract;)V
		16: ASM: class net.mcreator.seadwellers.procedures.VillagerTurnIntoMermorphProcedure onRightClickEntity(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$EntityInteract;)V
		17: ASM: class net.mcreator.seadwellers.procedures.SeashellUseProcedure onRightClickEntity(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$EntityInteract;)V
		18: ASM: class net.mcreator.seadwellers.procedures.MermorphTipsProcedure onRightClickEntity(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$EntityInteract;)V
		19: ASM: class net.sodiumzh.nff.services.eventlisteners.NFFEntityEventListeners onEntityInteract(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$EntityInteract;)V
		20: ASM: class tallestegg.guardvillagers.VillagerToGuard onEntityInteract(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$EntityInteract;)V
		21: ASM: class com.github.tartaricacid.touhoulittlemaid.event.InstallChairEvent onPlayerEntityInteract(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$EntityInteract;)V
		22: ASM: com.github.L_Ender.cataclysm.event.ServerEventHandler@6170ad8a onPlayerInteract(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$EntityInteract;)V
		23: ASM: class com.github.tartaricacid.touhoulittlemaid.event.CopyEntityIdEvent copyEntityId(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$EntityInteract;)V
		24: ASM: class net.mcreator.oceansenhancements.procedures.YellowSeahorseRightClickedOnEntityProcedure onRightClickEntity(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$EntityInteract;)V
		25: ASM: class net.mcreator.oceansenhancements.procedures.RedSeahorseRightClickedOnEntityProcedure onRightClickEntity(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$EntityInteract;)V
		26: ASM: class net.mcreator.oceansenhancements.procedures.PinkSeahorseRightClickedOnEntityProcedure onRightClickEntity(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$EntityInteract;)V
		27: ASM: class net.mcreator.oceansenhancements.procedures.LuminiscentYellowSeahorseRightClickedOnEntityProcedure onRightClickEntity(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$EntityInteract;)V
		28: ASM: class net.mcreator.oceansenhancements.procedures.LuminiscentPinkSeahorseRightClickedOnEntityProcedure onRightClickEntity(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$EntityInteract;)V
		29: ASM: class net.mcreator.oceansenhancements.procedures.LuminiscentGreenSeahorseRightClickedOnEntityProcedure onRightClickEntity(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$EntityInteract;)V
		30: ASM: class net.mcreator.oceansenhancements.procedures.GreenSeahorseRightClickedOnEntityProcedure onRightClickEntity(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$EntityInteract;)V
		31: ASM: class net.mcreator.oceansenhancements.procedures.GoldenFishRightClickedOnEntityProcedure onRightClickEntity(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$EntityInteract;)V
		32: ASM: class net.mcreator.oceansenhancements.procedures.ClownFishRightClickedOnEntityProcedure onRightClickEntity(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$EntityInteract;)V
		33: ASM: class net.mcreator.oceansenhancements.procedures.BlueTangFishRightClickedOnEntityProcedure onRightClickEntity(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$EntityInteract;)V
		34: ASM: class net.mcreator.oceansenhancements.procedures.BlueSeaHorseRightClickedOnEntityProcedure onRightClickEntity(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$EntityInteract;)V
		35: ASM: class net.sodiumzh.nff.girls.eventlisteners.NFFGirlsEntityEventListeners onEntityInteract(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$EntityInteract;)V
		36: ASM: com.bobmowzie.mowziesmobs.server.ServerEventHandler@f4646ab onPlayerInteract(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$EntityInteract;)V
		37: ASM: com.bobmowzie.mowziesmobs.server.ability.AbilityCommonEventHandler@312f4f1c onPlayerRightClickEntity(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$EntityInteract;)V
		38: net.minecraftforge.eventbus.EventBus$$Lambda$2104/0x0000000800a26d08@3ef51d42
		39: ASM: class dev.mayaqq.estrogen.forge.EstrogenForgeEvents entityInteractEvent(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$EntityInteract;)V
		40: ASM: class com.github.eterdelta.crittersandcompanions.CrittersAndCompanionsForge$ForgeEvents onPlayerEntityInteract(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$EntityInteract;)V
		41: ASM: com.feywild.feywild.EventListener@74d1740d entityInteract(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$EntityInteract;)V
		42: ASM: class dev.xkmc.cuisinedelight.events.SkilletUseEventListeners onEntityRightClick(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$EntityInteract;)V
		43: ASM: mob_grinding_utils.events.EntityInteractionEvent@7ff32359 clickOnEntity(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$EntityInteract;)V
		44: ASM: class vectorwing.farmersdelight.common.item.HorseFeedItem$HorseFeedEvent onHorseFeedApplied(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$EntityInteract;)V
		45: ASM: class vectorwing.farmersdelight.common.item.DogFoodItem$DogFoodEvent onDogFoodApplied(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$EntityInteract;)V
		46: ASM: class net.mcreator.monstersandgirls.procedures.EntityMovementOnClickProcedure onRightClickEntity(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$EntityInteract;)V
		47: ASM: com.github.alexthe666.alexsmobs.event.ServerEvents@68653c34 onInteractWithEntity(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$EntityInteract;)V
		48: ASM: class net.mcreator.notenoughgolems.procedures.PlayerIndividualCallProcedure onRightClickEntity(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$EntityInteract;)V
		49: ASM: class net.mcreator.glowroot.procedures.RightClickGolemIntoDrillProcedure onRightClickEntity(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$EntityInteract;)V
		50: ASM: class com.scouter.netherdepthsupgrade.events.ForgeEvents frogFeed(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$EntityInteract;)V
		51: ASM: class com.teamabnormals.abnormals_delight.core.other.ADEvents onEntityInteract(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$EntityInteract;)V
		52: ASM: class net.mcreator.enderwyrmlings.procedures.TestingProcedure onRightClickEntity(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$EntityInteract;)V
		53: ASM: class net.mcreator.enderwyrmlings.procedures.MushroomWyrmlingInteractProcedure onRightClickEntity(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$EntityInteract;)V
		54: ASM: class net.mcreator.enderwyrmlings.procedures.MossyWyrmlingInteractProcedure onRightClickEntity(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$EntityInteract;)V
		55: ASM: class net.mcreator.enderwyrmlings.procedures.LavaWyrmlingInteractProcedure onRightClickEntity(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$EntityInteract;)V
		56: ASM: class net.mcreator.enderwyrmlings.procedures.IceWyrmlingInteractProcedure onRightClickEntity(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$EntityInteract;)V
		57: ASM: class net.mcreator.enderwyrmlings.procedures.EnderWyrmlingInteractProcedure onRightClickEntity(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$EntityInteract;)V
		58: ASM: com.github.alexmodguy.alexscaves.server.event.CommonEvents@3f133e98 playerEntityInteract(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$EntityInteract;)V
		59: ASM: class net.mcreator.sharks.procedures.TigerSharkRightClickedOnEntityProcedure onRightClickEntity(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$EntityInteract;)V
		60: ASM: class com.teamabnormals.environmental.core.other.EnvironmentalEvents onEntityInteract(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$EntityInteract;)V
		61: ASM: class net.mcreator.sharks.procedures.SuckerRightClickedOnEntityProcedure onRightClickEntity(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$EntityInteract;)V
		62: ASM: class net.mcreator.sharks.procedures.ShrakRightClickedOnEntityProcedure onRightClickEntity(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$EntityInteract;)V
		63: ASM: class net.mcreator.sharks.procedures.SharkMealRightclickedProcedure onRightClickEntity(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$EntityInteract;)V
		64: ASM: class net.mcreator.sharks.procedures.RightClickSpeedProcedure onRightClickEntity(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$EntityInteract;)V
		65: ASM: class net.mcreator.sharks.procedures.ParasiteCollectProcedure onRightClickEntity(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$EntityInteract;)V
		66: ASM: class net.mcreator.sharks.procedures.NurseSharkRightClickedOnEntityProcedure onRightClickEntity(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$EntityInteract;)V
		67: ASM: class net.mcreator.sharks.procedures.BullSharkRightClickedOnEntityProcedure onRightClickEntity(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$EntityInteract;)V
		68: ASM: class net.mcreator.sharks.procedures.BaskingSharkRightClickedOnEntityProcedure onRightClickEntity(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$EntityInteract;)V
		69: ASM: class com.teamabnormals.upgrade_aquatic.core.other.UAEvents onInteractEntity(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$EntityInteract;)V
		70: ASM: class net.fabricmc.fabric.impl.event.interaction.InteractionEventHooks onEntityInteract(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$EntityInteract;)V
		71: ASM: class net.miauczel.legendary_monsters.item.custom.CustomItemEvents.WandOfCloudsRightClickEvent onRightClickEntity(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$EntityInteract;)V
		72: ASM: class net.miauczel.legendary_monsters.item.custom.CustomItemEvents.WandOfCloudsRightClickEffect onRightClickEntity(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$EntityInteract;)V
		73: ASM: class com.stal111.forbidden_arcanus.common.event.PlayerEvents onEntityInteract(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$EntityInteract;)V
		74: net.minecraftforge.eventbus.EventBus$$Lambda$2104/0x0000000800a26d08@24673b80
		75: net.minecraftforge.eventbus.EventBus$$Lambda$2104/0x0000000800a26d08@1666e371
		76: net.minecraftforge.eventbus.EventBus$$Lambda$2104/0x0000000800a26d08@40d2e0e9
		77: net.minecraftforge.eventbus.EventBus$$Lambda$2104/0x0000000800a26d08@56dbfabc
		78: net.minecraftforge.eventbus.EventBus$$Lambda$2104/0x0000000800a26d08@4b7d70dc
		79: ASM: class net.mcreator.borninchaosv.procedures.TransmutingElixirclicProcedure onRightClickEntity(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$EntityInteract;)V
		80: ASM: class net.mcreator.borninchaosv.procedures.ThornshellCrabPriShchielchkiePKMPoSushchnostiProcedure onRightClickEntity(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$EntityInteract;)V
		81: ASM: class net.mcreator.borninchaosv.procedures.SwarmerPreparationProcedure onRightClickEntity(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$EntityInteract;)V
		82: ASM: class net.mcreator.borninchaosv.procedures.DreadHoundPriNazhatiiPravoiKnopkiNaSushchnostProcedure onRightClickEntity(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$EntityInteract;)V
		83: ASM: class net.mcreator.borninchaosv.procedures.DarkRitualDaggerPProcedure onRightClickEntity(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$EntityInteract;)V
		84: ASM: class com.Polarice3.Goety.common.events.StunnedEvents cancelInteract(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$EntityInteract;)V
		85: ASM: class com.Polarice3.Goety.common.events.SoulEnergyEvents onLivingInteract(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$EntityInteract;)V
		86: ASM: class com.Polarice3.Goety.common.events.PotionEvents PlayerInteractEntityEvents(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$EntityInteract;)V
		87: ASM: class com.simibubi.create.content.equipment.extendoGrip.ExtendoGripItem notifyServerOfLongRangeInteractions(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$EntityInteract;)V
		88: ASM: class com.simibubi.create.content.contraptions.mounted.MinecartContraptionItem wrenchCanBeUsedToPickUpMinecartContraptions(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$EntityInteract;)V
		89: ASM: com.github.alexthe666.iceandfire.event.ServerEvents@783e0f59 onEntityInteract(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$EntityInteract;)V
		90: ASM: class tictim.paraglider.forge.event.ParagliderEventHandler onPlayerInteract(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
		91: ASM: class com.aetherteam.aether.event.listeners.abilities.ToolAbilityListener onEntityInteract(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
		92: ASM: class twilightforest.events.ToolEvents onEntityInteract(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
		93: ASM: mob_grinding_utils.events.ChickenFuseEvent@36dcafa2 startChickenFuse(Lnet/minecraftforge/event/entity/living/LivingEvent;)V
		94: LOW
		95: ASM: class net.mehvahdjukaar.supplementaries.common.events.forge.ServerEventsForge onEntityInteract(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$EntityInteract;)V
net.minecraft.ReportedException: Saving entity NBT
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.entity.Entity.m_20240_(Entity.java:1679)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.entity.Entity.m_20086_(Entity.java:1584)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.entity.Entity.m_20223_(Entity.java:1591)
	at TRANSFORMER/forbidden_arcanus@1.20.1-2.2.6/com.stal111.forbidden_arcanus.common.item.QuantumCatcherItem.setEntity(QuantumCatcherItem.java:157)
	at TRANSFORMER/forbidden_arcanus@1.20.1-2.2.6/com.stal111.forbidden_arcanus.common.item.QuantumCatcherItem.onEntityInteract(QuantumCatcherItem.java:101)
	at TRANSFORMER/forbidden_arcanus@1.20.1-2.2.6/com.stal111.forbidden_arcanus.common.event.PlayerEvents.tryPickupMob(PlayerEvents.java:186)
	at TRANSFORMER/forbidden_arcanus@1.20.1-2.2.6/com.stal111.forbidden_arcanus.common.event.PlayerEvents.onEntityInteract(PlayerEvents.java:101)
	at TRANSFORMER/forbidden_arcanus@1.20.1-2.2.6/com.stal111.forbidden_arcanus.common.event.__PlayerEvents_onEntityInteract_EntityInteract.invoke(.dynamic)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:315)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:296)
	at TRANSFORMER/forge@47.1.101/net.minecraftforge.common.ForgeHooks.onInteractEntity(ForgeHooks.java:767)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.entity.player.Player.m_36157_(Player.java:976)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.multiplayer.MultiPlayerGameMode.m_105226_(MultiPlayerGameMode.java:405)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.Minecraft.m_91277_(Minecraft.java:1684)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.Minecraft.redirect$cib000$betterthirdperson$onDoItemUse(Minecraft.java:10973)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.Minecraft.m_91279_(Minecraft.java:1976)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.Minecraft.m_91398_(Minecraft.java:1795)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1112)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.Minecraft.m_91374_(Minecraft.java:718)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.main.Main.main(Main.java:218)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at MC-BOOTSTRAP/fml_loader@47.2.2/net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:126)
	at MC-BOOTSTRAP/fml_loader@47.2.2/net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:114)
	at MC-BOOTSTRAP/fml_loader@47.2.2/net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.runService(CommonClientLaunchHandler.java:24)
	at MC-BOOTSTRAP/fml_loader@47.2.2/net.minecraftforge.fml.loading.targets.CommonLaunchHandler.lambda$launchService$4(CommonLaunchHandler.java:108)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.Launcher.run(Launcher.java:108)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.Launcher.main(Launcher.java:78)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
	at cpw.mods.bootstraplauncher@1.1.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141)
Caused by: java.lang.NullPointerException: Cannot invoke "String.isEmpty()" because "p_129298_" is null
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.nbt.StringTag.m_129297_(StringTag.java:57)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.nbt.CompoundTag.m_128359_(CompoundTag.java:213)
	at TRANSFORMER/humancompanions@1.20.1-1.7.5/com.github.justinwon777.humancompanions.entity.AbstractHumanCompanionEntity.m_7380_(AbstractHumanCompanionEntity.java:208)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.entity.Entity.m_20240_(Entity.java:1658)
	... 36 more

**Comment by lSherozl** [comment]
[crash-2024-12-12_19.23.55-client.txt](https://github.com/user-attachments/files/18120003/crash-2024-12-12_19.23.55-client.txt)

**Comment by stal111** [comment]
Please report this to the HumanCompanions Github, they somehow try to save a null food String. Might also be caused by things like Sinytra Connector but not sure.

**Comment by lSherozl** [comment]
> Please report this to the HumanCompanions Github, they somehow try to save a null food String. Might also be caused by things like Sinytra Connector but not sure.

Thanks for the quick reply, I will report it, and its not caused by connector aha. Just their mod then.
