### ISSUE TITLE
server crash on launch-1.15.2

### ISSUE THREAD

**Issue by SDUBZ** [stal111/Forbidden-Arcanus#46]
forge-1.15.2-31.1.16
forbidden_arcanus-1.15.2-1.2-beta-1

logs:
[latest.log](https://github.com/stal111/Forbidden-Arcanus/files/4272494/latest.log)

[crash-2020-03-02_09.03.00-server.txt](https://github.com/stal111/Forbidden-Arcanus/files/4272500/crash-2020-03-02_09.03.00-server.txt)

**Comment by stal111** [comment]
Fixed in forbidden_arcanus-1.15.2-1.2-beta-2
