### ISSUE TITLE
Entities glow sometimes (unprompted)

### ISSUE THREAD

**Issue by ghost** [stal111/Forbidden-Arcanus#48]
I don't have the item that makes this happen at start but mobs in a specific radius glow for no reason

**Comment by ghost** [comment]
I don't now how to tag it as a bug...

**Comment by stal111** [comment]
Are you sure that no other mod causes it? Also I would need more information (mod version, forge version...)

**Comment by ghost** [comment]
It happens only rarely, (probably another mod)
ill give more info if I encounter it in the future.

**Comment by DoCharlcate** [comment]
I was also getting this as soon as making a new world after installing 'forbidden_arcanus-1.14.4-1.5.jar' using forge-28.2.1 but after updating to forge-28.2.3 it seems to have stopped.

**Comment by DoCharlcate** [comment]
Actually scrub that. The glow effect happened again when starting a new world with 'forbidden_arcanus-1.14.4-1.5.jar' using the latest forge-28.2.3. It does seem to be coming from this mod as well as disabling this mod clears glow effect.

**Comment by kreezxil** [comment]
I've been struggling with this too for about 3 months now and decided today to start disabling mod groups. disabling forbidden arcanus made the glow effect go away. It is most definitely this mod causing it.

**Comment by stal111** [comment]
Please reopen if this still happens with the most recent version.
