### ISSUE TITLE
Crash of the client when you open the Forbiddenmicon

### ISSUE THREAD

**Issue by jinkhya** [stal111/Forbidden-Arcanus#49]
Hello opening the Forbiddenmicon crashes the client. 
Here's the crash-log : 
https://paste.gg/p/anonymous/d215689e97b04e29a1b318aa1d31a473

**Comment by jinkhya** [comment]
Forgot to specify : 
Pack ATM5
forge 31.1.18
forbidden_arcanus-1.15.2-1.2-beta-2.jar

**Comment by stal111** [comment]
Should be fixed
