### ISSUE TITLE
Ore Block Textures Altered When Applying A Resource Pack

### ISSUE THREAD

**Issue by harperj0** [stal111/Forbidden-Arcanus#50]
I found that using resource packs that add more Model JSON files than what Minecraft usually handles alters the textures of the ore blocks (ex: bushy leaves textures that not only use a leaves.json but also a leaves_busy.json or unique textures for double slab blocks)  
It seems like it is an issue with how forge registers the textures dynamically since restarting minecraft seems to correct the issue pretty consistently.
Bringing the Modded Textures resourcepack to the top does not change the outcome.
Tested on 1.15.2 Forge ver. 31.1.19 Mod ver.  1.1

no texture pack
![No Texture Pack](https://user-images.githubusercontent.com/62157558/76657449-4bae8280-6548-11ea-8aab-87cd6aeb0bf0.png)
texture pack 1
![Texture Pack 1](https://user-images.githubusercontent.com/62157558/76657450-4c471900-6548-11ea-8b74-640905c822f5.png)
texture pack 2
![Texture Pack 2](https://user-images.githubusercontent.com/62157558/76657451-4c471900-6548-11ea-8b8c-c8763d9d29c9.png)

**Comment by stal111** [comment]
Finally fixed in 16.2.0-beta-1.
