### ISSUE TITLE
Enchanting via anvil is broken

### ISSUE THREAD

**Issue by pa1nki113r** [stal111/Forbidden-Arcanus#55]
Certain items like the obsidian axe and sword bug out when trying to enchant them on an anvil.

I lose an XP level for the enchantment cost after I click the resulting item but its never added to my inventory.

Could be because of a compatibility issue with either:

Apotheosis
Quark

Is there any way to fix this or a reason why this is happening?

**Comment by stal111** [comment]
Looks like a mod conflict. Does this only happen with tools from forbidden & arcanus or also from tools added by other mods?
