### ISSUE TITLE
[1.14.4] Potential client-side function violation in Edelwood bucket tick

### ISSUE THREAD

**Issue by noobanidus** [stal111/Forbidden-Arcanus#57]
I got an edelwood bucket with lava from a loot chest and was kicked from t he server.

There wasn't an actual crash report, I only have this from the log: https://gist.github.com/noobanidus/74817cc4c809cf785d12cc6b1b8c7906

From my K9 instance:

```
MC 1.14.4: net/minecraft/item/Item.getDefaultInstance
Name: q => func_190903_i => getDefaultInstance
Comment: None
Side: CLIENT
AT: public net.minecraft.item.Item func_190903_i()Lnet/minecraft/item/ItemStack; # getDefaultInstance
```

It looks like this is a client-side only function. I haven't dug into your code specifically to learn more or be more helpful, sorry!

**Comment by stal111** [comment]
Sorry but 1.14.4 is no longer supported. I don't have the time to support multiple version for my projects so only 1.15.2 will receive new content/bug fixes.

**Comment by noobanidus** [comment]
That's fair. DevCraft is only running 1.14.4 at the minute to a) test out the new Create and b) because I haven't finished porting all of my mods to 1.15.
