### ISSUE TITLE
1.3 makes mining ores giving ingots instead of the ore block

### ISSUE THREAD

**Issue by Onigeshi** [stal111/Forbidden-Arcanus#59]
I don't even know how to debug this to give you more details.. with 1.15.2-1.3 mining ores gives the smelting outputs instead of the 'raw' ore block.. rolled back to 1.15.2-1.2-beta-4 and I have no issues :)).. config files untouched..

here is the instance, it has a new world i've created to test it again: ** removed as its not needed anymore **

**Comment by DoCharlcate** [comment]
Can confirm the above issue using forge-311.45 and the latest 311.47

**Comment by DoCharlcate** [comment]
Could be an Issue with the Infernum Pickaxe again. Seems like vanilla pickaxes (enchanted or not), have its special smelting ability now. Curiously though, the golden pickaxe drops nothing but I'm not sure if that is related.

**Comment by JurnyJudasz** [comment]
it's even breaking the new pickaxes from other mods and negates silktouch, all ores also involved, Even from extra mods

**Comment by stal111** [comment]
Fixed in 1.15.2-1.3.1. Thank you for reporting :)
