### ISSUE TITLE
Infernum Pickaxe not working 1.14.3-1.0-Beta-2

### ISSUE THREAD

**Issue by jstsmthrgk** [stal111/Forbidden-Arcanus#6]
The Infernum Pickaxe does not smelt ores. I tested it with iron and gold.

**Comment by litjohn50** [comment]
I am having the same problems. 

Doesn't work with any ores. Let alone vanilla.

Video to show proof: https://gyazo.com/36888dd0bc67770f665574721c626aa7

**Comment by stal111** [comment]
Will be fixed as soon as forge provides a new way of modifying block loot tables

**Comment by EledrinMods** [comment]
Can this be fixed yet? @stal111

**Comment by stal111** [comment]
Finally fixed in 1.15.2-1.3 :)
