### ISSUE TITLE
[Suggestion] CTM for Arcane Edelwood Planks

### ISSUE THREAD

**Issue by lamoyrl90** [stal111/Forbidden-Arcanus#61]
First off: I love the aesthetics of this mod SO much.

On placing the Arcane Edelwood Planks I was kind've expecting to see the ornate texture stay in the corners, but alas, it simply tiled. Not a big deal, really, but it's the little things, right?

**Comment by stal111** [comment]
If CTM ever updates to 1.15.2 then sure, but we wont update the 1.12.2 version.
