### ISSUE TITLE
No Config Options for xPetrified Ore and Stella Arcanum

### ISSUE THREAD

**Issue by dankfrog** [stal111/Forbidden-Arcanus#67]
Forgive me if this option exists and I am not seeing it but I was wondering if there was a way to configure the xPetrified Ore as well as the Stella Arcanum Ore. 

I am trying to use the Geolysis mod to generate ores. 

I have disabled the other ones however, these ones keep generating and I don't an option to disable or change the generation in any way.

here is my config: https://pastebin.com/BLmcANgj

I tried trashing the configs to regenerate them but nothing changed.

I apologize if this is an inconvenient post, I appreciate your work. 

Thank you.

**Comment by TheUntamed** [comment]
There is no config for those ores right now. I hope they will be added soon.
I would also appreciate if Stella Arcanum also generates in the Nether, maybe with a dimension or biome blacklist so people can decide if they want that.

**Comment by stal111** [comment]
Added new Config Options in 1.15.2-1.4

**Comment by EricBuist** [comment]
This is quite surprising and annoying. I'm having the EXACT opposite problem: there should be these kinds of ores generated but they are missing. I'm searching, searching and searching, to no avail. Tiref of searching without finding anything, I'm trying on Google and for the 100th time if not more, getting the reverse problem again. I'm about to give up and cheat but I'm really annoyed and pissed off. This ore generation mechanic really ruins my Minecraft gameplay. I worked around by picking skyblock packs, but nowadays, these packs tend to go the hybrid way and require mining some ores.
