### ISSUE TITLE
disable ore spawns

### ISSUE THREAD

**Issue by FrostCreeper07** [stal111/Forbidden-Arcanus#71]
This isn't an issue per se rather a question. I'm currently developing a modpack that has 99% of ores disabled and i'm just wondering how to if possible how to disable the ores generated by this mod?

**Comment by stal111** [comment]
There is a config file (forbidden_arcanus-server.toml) in which you can disable everything that has to do with world gen

**Comment by FrostCreeper07** [comment]
where might that be, i'm using the 1.12.2 version and i don't see it. Am i just missing it?

**Comment by stal111** [comment]
Oh, i dont know if there was already a config in 1.12.2. Best would be if you could update to a newer version as there is definetly a config but also forbidden & arcanus got many new features since 1.12.2.

**Comment by FrostCreeper07** [comment]
I know but my pack is built on 1.12.2 since alot of people are unable to play modded newer versions it's not a big deal but thanks anyways.
