### ISSUE TITLE
[1.16.1] Crash while rendering Forbidden And Arcanus items in JEI.

### ISSUE THREAD

**Issue by Gbergz** [stal111/Forbidden-Arcanus#74]
Title^

**MC Version:** 1.16.1
**Mod Version:** 1.16.1-1.0-beta-1
**Forge:** 32.0.59

Crash-Report: https://hastebin.com/udogipoliz.pl

**Comment by stal111** [comment]
Does this still crash in the newest beta?

**Comment by Gbergz** [comment]
Nope looks like its fixed!
