### ISSUE TITLE
1.16.1 - Orb of Temporary Flight - No indicators showing the duration. 

### ISSUE THREAD

**Issue by Vanblam** [stal111/Forbidden-Arcanus#75]
Not really an issue I suppose but I think it should be required (Unless you're already working on that lol)? Would be kind of scary when you are up high and you have no idea how much longer it's going to last. Mod looks very very nice though, can't wait to see the finished product, keep up the good work :D

**Comment by stal111** [comment]
Fixed in 1.16-1.0
