### ISSUE TITLE
1.16.1 Cherrywood Sapling growing Acacia Trees

### ISSUE THREAD

**Issue by KingHearts5** [stal111/Forbidden-Arcanus#77]
I am using version 1.16.1-1.0-beta-2 and while trying to grow cherrywood saplings for more logs I only get acacia trees to grow from the cherrywood saplings. Since the tree is fair common in spawns I don't mind the loss too much, but was curious as to why it was occurring.

I am running the mod in the valhesia 3 modpack and in a lavender fields biome from biomes of plenty in case those or another mod is conflicting with the sapping growth.

**Comment by xXspudicusXx** [comment]
Yeah I just noticed this too and this is the only mod pack I have applied at the moment. So I don't think it's an overlapping mod issue.

**Comment by 666Code666** [comment]
Hello,

I have this same problem with Cherrywood Sapling and Mysterwood Sapling ;/

**Comment by Fawkes6** [comment]
With the Biomes O'Plenty mod, it was able to generate Cherrywood and Mysterywood Trees upon world generation. Forge build: .66 for 1.16.1, on Java platform. 

Both Saplings produce Acacia trees despite successful world generation.

**Comment by stal111** [comment]
Fixed in 1.16-1.0
