### ISSUE TITLE
Indestructible Enchantment doesn't work on armors

### ISSUE THREAD

**Issue by AcaliaDesu** [stal111/Forbidden-Arcanus#79]
Armors are losing durability even though they are enchanted with the Indestructible enchantment. 

I've tried it on a few armors, vanilla and modded (iron, gold, diamond, and steel & refined obsidian from mekanism), all the armors i've tried it on lose durability when i'm hit, regardless of Indestructible or not.

**Comment by stal111** [comment]
Fixed in 1.16-1.0
