### ISSUE TITLE
1.15.2 - "indestructible" enchantment doesn't prevent Turtle Shell from breaking with Upgrade Aquatic installed

### ISSUE THREAD

**Issue by Aiva418** [stal111/Forbidden-Arcanus#80]
I'm playing Valhelsia 2, and I enchanted a turtle shell with "indestructible," hoping it would prevent the item from breaking. Unfortunately, it seems that "indestructible" items can break if they aren't equipped in a hand slot, and Upgrade Aquatic tweaks the turtle shell so that it takes damage while you're underwater. It might be the same issue as the one I saw about armor not being properly affected by the enchantment, but I'm making a separate one in case fixing that issue doesn't prevent Upgrade Aquatic from breaking turtle shells. 

Upgrade Aquatic - 1.15.2-1.7.1
Forbidden & Arcanus - 1.15.2-1.4

**Comment by stal111** [comment]
Should be fixed in 1.16-1.0
