### ISSUE TITLE
[Suggestion] 1.14+ Please Add Crafttweaker Support

### ISSUE THREAD

**Issue by Silverrain2004** [stal111/Forbidden-Arcanus#83]
Hi Guys, since there is a wonderful CT-API , why not to add Crafttweaker Support? so we can Change, Machinebehavior, Recipes and more?

Crafttweaker is avaible from 1.12-1.16 ;)

**Comment by stal111** [comment]
All Recipes added by the mod will be defined through json files, so no need for Crafttweaker support.
