### ISSUE TITLE
Random Crashes: Cannot set property BooleanProperty on DarkStone

### ISSUE THREAD

**Issue by surfersmurf** [stal111/Forbidden-Arcanus#86]
Hello,

the game crashes randomly (playing the ATM 6 pack). Also reported at ATM6:

https://github.com/AllTheMods/ATM-6/issues/42

Here's the pastebin:

https://pastebin.com/az8Y9004

This happens as I copied over my old save, where forbidden & arcanus 1.0-beta-2 was previously installed.

**Comment by PotatoPresident** [comment]
Experiencing this on valhelsia 3.

https://hastebin.com/biqujugofi.sql

**Comment by Gallaf** [comment]
I'm experiencing this as well on Valhesia 3
