### ISSUE TITLE
Missing items?

### ISSUE THREAD

**Issue by bloodconfetti** [stal111/Forbidden-Arcanus#9]
![arcanus missing](https://user-images.githubusercontent.com/53692357/62755987-57c2e680-ba33-11e9-9af9-291da181e8f7.png)
Hi there, as per this github topic, I have no idea what's going on: https://github.com/VsnGamer/ElevatorMod/issues/36#issue-478792480
[latest.log](https://github.com/stal111/Forbidden-Arcanus/files/3484864/latest.log)

If you can shed any light, it'd be much appreciated.

**Comment by stal111** [comment]
Should be fixed in forbidden-arcanus-1.14.4-1.0-Beta-3. It was due a bigger change in forge 28.0.45 which broke some mods.
